In [1]:
import pandas as pd

import seaborn as sb
import matplotlib.pyplot as plt

In [2]:
DATA_PATH = "../Data"

In [ ]:
NINETY_DAYS_T1_PATH = "churn_dataset_90_1.csv"
NINETY_DAYS_T2_PATH = "churn_dataset_90_days2.csv"
NINETY_DAYS_T3_PATH = "churn_dataset_90_3.csv"
ONE_HUNDRED_TWENTY_T1_PATH = "churn_dataset_120_1.csv"
ONE_HUNDRED_TWENTY_T2_PATH = "churn_dataset_120_2.csv"
ONE_HUNDRED_FIFTY_T1_PATH = "churn_dataset_150_1.csv"
ONE_HUNDRED_FIFTY_T2_PATH = "churn_dataset_150_2.csv"

In [5]:
churn_dataset_90_days1 = pd.read_csv(DATA_PATH + "/" + NINETY_DAYS_T1_PATH) 
churn_dataset_90_days2 = pd.read_csv(DATA_PATH + "/" + NINETY_DAYS_T2_PATH)
churn_dataset_90_days3 = pd.read_csv(DATA_PATH + "/" + NINETY_DAYS_T3_PATH)
churn_dataset_120_days1 = pd.read_csv(DATA_PATH + "/" + ONE_HUNDRED_TWENTY_T1_PATH)
churn_dataset_120_days2 = pd.read_csv(DATA_PATH + "/" + ONE_HUNDRED_TWENTY_T2_PATH)
churn_dataset_150_days1 = pd.read_csv(DATA_PATH + "/" + ONE_HUNDRED_FIFTY_T1_PATH)
churn_dataset_150_days2 = pd.read_csv(DATA_PATH + "/" + ONE_HUNDRED_FIFTY_T2_PATH)

-----
-----

# Vertical union of columns

## 90 days

In [6]:
train_90_df = pd.concat([churn_dataset_90_days1,churn_dataset_90_days2,churn_dataset_90_days3], axis= 0, ignore_index= True)

train_90_df

,customer_unique_id,price,freight_ratio,payment_value,dates_diff,review_score,customer_city,customer_state,order_status,payment_sequential,payment_type,payment_installments,product_cat,churn_90
0,00115fc7123b5310cf6d3a3aa932699e,59.99,0.268711,76.11,-33.0,4.0,brasilia,DF,delivered,1.0,credit_card,1.0,sports_leisure,1
1,002b4cd83fabaffaa475f78ea5ef3e08,49.90,0.290982,64.42,-28.0,2.0,sao sebastiao do paraiso,MG,delivered,1.0,credit_card,1.0,fashion,1
2,0087eede471173af78d789df249c3a45,126.99,0.189936,151.11,-19.0,5.0,porto alegre,RS,delivered,1.0,boleto,1.0,miscellaneous,1
3,008f3d5f45a11059239a5c452cd00006,309.90,0.086028,336.56,-28.0,5.0,sao pedro da agua branca,MA,delivered,1.0,boleto,1.0,beauty,1
4,012b8001e47392df808a454083a74b74,65.60,0.497793,197.68,-28.0,5.0,capitao eneas,MG,delivered,1.0,credit_card,1.0,sports_leisure,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32850,ffe9e41fbd14db4a7361347c56af5447,199.00,0.109950,220.88,-9.0,5.0,vila velha,ES,delivered,1.0,credit_card,2.0,beauty,1
32851,fff7219c86179ca6441b8f37823ba3d3,245.80,0.081367,531.60,-12.0,4.0,cachoeiras de macacu,RJ,delivered,1.0,debit_card,1.0,household,1
32852,fffb09418989a0dbff854a28163e47c6,58.00,0.261379,73.16,-23.0,5.0,veranopolis,RS,delivered,1.0,boleto,1.0,beauty,1
32853,fffbf87b7a1a6fa8b03f081c5f51a201,149.00,0.122953,167.32,-14.0,5.0,fortaleza,CE,delivered,1.0,credit_card,2.0,unknown,1
32854,fffea47cd6d3cc0a88bd621562a9d061,64.89,0.303437,84.58,-3.0,4.0,feira de santana,BA,delivered,1.0,credit_card,1.0,babies,1

In [8]:
train_90_df.to_csv(r"C:\Users\Hallen\Documents\mis_cosas\silvana\master\tfm-uned-churn\Data\Train_test\train_90.csv", index=False)

## 120 days

In [9]:
train_120_df = pd.concat([churn_dataset_120_days1,churn_dataset_120_days2], axis= 0, ignore_index= True)

train_120_df

,customer_unique_id,price,freight_ratio,payment_value,dates_diff,review_score,customer_city,customer_state,order_status,payment_sequential,payment_type,payment_installments,product_cat,churn_120
0,0000f46a3911fa3c0805444483337064,69.00,0.249565,86.22,-2.0,3.0,sao jose,SC,delivered,1.0,credit_card,8.0,office,1
1,0005e1862207bf6ccc02e4228effd9a0,135.00,0.112000,150.12,-28.0,4.0,teresopolis,RJ,delivered,1.0,credit_card,3.0,fashion,1
2,00115fc7123b5310cf6d3a3aa932699e,59.99,0.268711,76.11,-33.0,4.0,brasilia,DF,delivered,1.0,credit_card,1.0,sports_leisure,1
3,001f3c4211216384d5fe59b041ce1461,24.88,0.440514,35.84,-11.0,3.0,sao paulo,SP,delivered,1.0,credit_card,3.0,household,1
4,002043098f10ba39a4600b6c52fbfe3c,176.99,0.343635,237.81,-16.0,4.0,aracaju,SE,delivered,1.0,credit_card,4.0,office,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23693,ffeefd086fc667aaf6595c8fe3d22d54,55.00,0.144364,62.94,-8.0,4.0,japeri,RJ,delivered,1.0,credit_card,3.0,beauty,1
23694,fff1afc79f6b5db1e235a4a6c30ceda7,34.99,0.431552,50.09,-16.0,5.0,erechim,RS,delivered,1.0,credit_card,4.0,beauty,1
23695,fff3a9369e4b7102fab406a334a678c3,84.90,0.210130,102.74,-7.0,5.0,brasilia,DF,delivered,1.0,credit_card,2.0,fashion,1
23696,fff699c184bcc967d62fa2c6171765f7,39.90,0.378446,55.00,-7.0,4.0,santos,SP,delivered,1.0,boleto,1.0,entertainment,1
23697,fffa431dd3fcdefea4b1777d114144f2,64.99,0.249423,81.20,-7.0,5.0,bom jardim,RJ,delivered,1.0,boleto,1.0,entertainment,1

In [10]:
train_120_df.to_csv(r"C:\Users\Hallen\Documents\mis_cosas\silvana\master\tfm-uned-churn\Data\Train_test\train_120.csv", index=False)

## 110 days

In [11]:
train_150_df = pd.concat([churn_dataset_150_days1,churn_dataset_150_days2], axis= 0, ignore_index= True)

train_150_df

,customer_unique_id,price,freight_ratio,payment_value,dates_diff,review_score,customer_city,customer_state,order_status,payment_sequential,payment_type,payment_installments,product_cat,churn_150
0,0000f46a3911fa3c0805444483337064,69.00,0.249565,86.22,-2.0,3.0,sao jose,SC,delivered,1.0,credit_card,8.0,office,1
1,0005e1862207bf6ccc02e4228effd9a0,135.00,0.112000,150.12,-28.0,4.0,teresopolis,RJ,delivered,1.0,credit_card,3.0,fashion,1
2,00115fc7123b5310cf6d3a3aa932699e,59.99,0.268711,76.11,-33.0,4.0,brasilia,DF,delivered,1.0,credit_card,1.0,sports_leisure,1
3,0011805441c0d1b68b48002f1d005526,269.00,0.104610,297.14,-13.0,3.0,goianesia do para,PA,delivered,1.0,credit_card,10.0,electronics,1
4,00191a9719ef48ebb5860b130347bf33,47.90,0.228810,58.86,-19.0,3.0,jarinu,SP,delivered,1.0,credit_card,2.0,household,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25735,fff1afc79f6b5db1e235a4a6c30ceda7,34.99,0.431552,50.09,-16.0,5.0,erechim,RS,delivered,1.0,credit_card,4.0,beauty,1
25736,fff3a9369e4b7102fab406a334a678c3,84.90,0.210130,102.74,-7.0,5.0,brasilia,DF,delivered,1.0,credit_card,2.0,fashion,1
25737,fff699c184bcc967d62fa2c6171765f7,39.90,0.378446,55.00,-7.0,4.0,santos,SP,delivered,1.0,boleto,1.0,entertainment,1
25738,fffcf5a5ff07b0908bd4e2dbc735a684,1570.00,0.320939,4134.84,-27.0,5.0,sanharo,PE,delivered,1.0,credit_card,10.0,beauty,1
25739,ffffd2657e2aad2907e67c3e9daecbeb,56.99,0.255659,71.56,-16.0,5.0,campo largo,PR,delivered,1.0,credit_card,4.0,beauty,1

In [12]:
train_150_df.to_csv(r"C:\Users\Hallen\Documents\mis_cosas\silvana\master\tfm-uned-churn\Data\Train_test\train_150.csv", index=False)