In [1]:
import pandas as pd

import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
olist_path = "../Data/olist_dataset.csv"

In [3]:
olist_df = pd.read_csv(olist_path)

olist_df

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,...,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,seller_zip_code_prefix,seller_city,seller_state,product_category_name_english
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP,00e7ee1b050b8499577073aeb2a297a1,delivered,2017-05-16 15:05:35,2017-05-16 15:22:12,2017-05-23 10:47:57,...,1141.0,1.0,8683.0,54.0,64.0,31.0,8577.0,itaquaquecetuba,SP,office_furniture
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP,29150127e6685892b6eab3eec79f59c7,delivered,2018-01-12 20:48:24,2018-01-12 20:58:32,2018-01-15 17:14:59,...,1002.0,3.0,10150.0,89.0,15.0,40.0,88303.0,itajai,SC,housewares
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP,b2059ed67ce144a36e2aa97d2c9e9ad2,delivered,2018-05-19 16:07:45,2018-05-20 16:19:10,2018-06-11 14:31:00,...,955.0,1.0,8267.0,52.0,52.0,17.0,8577.0,itaquaquecetuba,SP,office_furniture
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP,951670f92359f4fe4a63112aa7306eba,delivered,2018-03-13 16:06:38,2018-03-13 17:29:19,2018-03-27 23:22:42,...,1066.0,1.0,12160.0,56.0,51.0,28.0,8577.0,itaquaquecetuba,SP,office_furniture
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP,6b7d50bd145f6fc7f33cebabd7e49d0f,delivered,2018-07-29 09:51:30,2018-07-29 10:10:09,2018-07-30 15:16:00,...,407.0,1.0,5200.0,45.0,15.0,35.0,14940.0,ibitinga,SP,home_confort
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119138,17ddf5dd5d51696bb3d7c6291687be6f,1a29b476fee25c95fbafc67c5ac95cf8,3937,sao paulo,SP,6760e20addcf0121e9d58f2f1ff14298,delivered,2018-04-07 15:48:17,2018-04-07 16:08:45,2018-04-11 02:08:36,...,489.0,2.0,611.0,22.0,22.0,23.0,17400.0,garca,SP,books_general_interest
119139,e7b71a9017aa05c9a7fd292d714858e8,d52a67c98be1cf6a5c84435bd38d095d,6764,taboao da serra,SP,9ec0c8947d973db4f4e8dcf1fbfa8f1b,delivered,2018-04-04 08:20:22,2018-04-04 08:35:12,2018-04-05 18:42:35,...,1193.0,1.0,1211.0,25.0,24.0,22.0,14802.0,araraquara,SP,sports_leisure
119140,5e28dfe12db7fb50a4b2f691faecea5e,e9f50caf99f032f0bf3c55141f019d99,60115,fortaleza,CE,fed4434add09a6f332ea398efd656a5c,delivered,2018-04-08 20:11:50,2018-04-08 20:30:03,2018-04-09 17:52:17,...,575.0,1.0,870.0,25.0,20.0,18.0,3304.0,sao paulo,SP,health_beauty
119141,56b18e2166679b8a959d72dd06da27f9,73c2643a0a458b49f58cea58833b192e,92120,canoas,RS,e31ec91cea1ecf97797787471f98a8c2,delivered,2017-11-03 21:08:33,2017-11-03 21:31:20,2017-11-06 18:24:41,...,452.0,1.0,710.0,19.0,13.0,14.0,14840.0,guariba,SP,watches_gifts
119142,274fa6071e5e17fe303b9748641082c8,84732c5050c01db9b23e19ba39899398,6703,cotia,SP,28db69209a75e59f20ccbb5c36a20b90,delivered,2017-12-19 14:27:23,2017-12-19 18:50:39,2017-12-21 19:17:21,...,933.0,1.0,50.0,16.0,5.0,11.0,3804.0,sao paulo,SP,perfumery

In [4]:
olist_df["order_purchase_timestamp"] = pd.to_datetime(olist_df["order_purchase_timestamp"])

-------
-------

# Training data set by days

## 90 days

### 90 days term 1

In [ ]:
pd.to_datetime("2017-09-01")

In [5]:
CHURN_DAYS = 90

In [6]:
start_date_90 = olist_df["order_purchase_timestamp"].min()

start_date_90

Timestamp('2016-09-04 21:15:19')

In [7]:
ninety_days_later = start_date_90 + pd.Timedelta(days= CHURN_DAYS)

ninety_days_later

Timestamp('2016-12-03 21:15:19')

In [8]:
# Suming 90 days more to the variable ninety days later

end_date = ninety_days_later + pd.Timedelta(days= CHURN_DAYS)

end_date

Timestamp('2017-03-03 21:15:19')

In [9]:
# Make a dataframe for the total 180 days of observation:
# 90 days to determine customers, and the other to observe if they have churned of not

obs_90_df = olist_df[(olist_df["order_purchase_timestamp"]>= start_date_90) & (olist_df["order_purchase_timestamp"] < end_date)]

obs_90_df

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,...,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,seller_zip_code_prefix,seller_city,seller_state,product_category_name_english
55,4d27341acd30a36bca39008ee9bb9050,e021e698833bdeb89dfef3acb2e91f37,89254,jaragua do sul,SC,38e2829123a2bd1cbe111564824d0abb,delivered,2017-01-26 11:14:58,2017-01-26 11:25:21,2017-01-27 12:19:14,...,1236.0,1.0,340.0,17.0,7.0,16.0,85801.0,cascavel,PR,consoles_games
132,eb67e9bd3357fbacdbef99759f919573,4bc7250d4b42b3374eb6f41b12429592,4710,sao paulo,SP,42a5f0ddbf1e377e7d31ef5957b62c0a,delivered,2017-02-06 16:49:19,2017-02-06 17:02:40,2017-02-09 10:53:47,...,589.0,2.0,500.0,16.0,13.0,13.0,13170.0,sumare,SP,watches_gifts
140,b0964d76975dbc174b623b5a300973d5,24a5c2b24a4467c37e2f54c1b311de93,86990,marialva,PR,56b50d57e6b735968a48a170b8364893,delivered,2017-02-08 16:06:47,2017-02-09 02:55:45,2017-02-09 10:52:15,...,1256.0,7.0,3300.0,32.0,29.0,51.0,13324.0,salto,SP,housewares
151,7e468d618e16c6e1373fb2c4a522c969,96b1c916f245f2462efcde3fce04bc3e,30421,belo horizonte,MG,c8f50df8a3e4fc40685c137dd2253eac,delivered,2017-02-13 07:34:18,2017-02-13 07:45:15,2017-02-13 11:11:01,...,1066.0,6.0,600.0,35.0,7.0,40.0,81560.0,curitiba,PR,baby
166,d6ea00d4a2dca6a01c708931b325a9e5,1d4626b197f66aa6129c135ab09f1a7b,73020,brasilia,DF,5860cc6e7b232e3c597af193d7760d1a,delivered,2017-02-13 10:20:42,2017-02-14 03:45:17,2017-02-17 10:46:21,...,812.0,1.0,17325.0,35.0,40.0,40.0,3029.0,sao paulo,SP,small_appliances
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119037,800ae98df618c84cf1dae67ea96644c5,a7941a8ddbfe8fde0bd23ae272484043,26381,queimados,RJ,4e44d7b0462e32a51de74a16eac6534e,delivered,2017-02-02 16:18:44,2017-02-02 16:30:10,2017-02-03 10:15:58,...,137.0,2.0,100.0,16.0,4.0,11.0,3237.0,sao paulo,SP,telephony
119038,800ae98df618c84cf1dae67ea96644c5,a7941a8ddbfe8fde0bd23ae272484043,26381,queimados,RJ,4e44d7b0462e32a51de74a16eac6534e,delivered,2017-02-02 16:18:44,2017-02-02 16:30:10,2017-02-03 10:15:58,...,137.0,2.0,100.0,16.0,4.0,11.0,3237.0,sao paulo,SP,telephony
119039,800ae98df618c84cf1dae67ea96644c5,a7941a8ddbfe8fde0bd23ae272484043,26381,queimados,RJ,4e44d7b0462e32a51de74a16eac6534e,delivered,2017-02-02 16:18:44,2017-02-02 16:30:10,2017-02-03 10:15:58,...,137.0,2.0,100.0,16.0,4.0,11.0,3237.0,sao paulo,SP,telephony
119044,bf9a4770691ff9b2ddb07f4beb77d4ad,95a3dcd03d8086e8510d9fe16f875ec7,76105,firminopolis,GO,996936689b68af80b51ef3c429a4f386,delivered,2017-03-02 08:17:50,2017-03-03 02:15:17,2017-03-03 11:49:20,...,1084.0,2.0,200.0,41.0,2.0,29.0,31255.0,belo horizonte,MG,computers_accessories
119118,be631308cb609ff74d0e0fb54815e18c,1c137fe37df712015f6488edafe8ece4,36255,aracitaba,MG,b7ae7c643ef9274727f48dcb0ba08593,delivered,2017-01-25 16:51:27,2017-01-27 11:50:24,2017-01-30 16:22:11,...,419.0,4.0,200.0,16.0,5.0,11.0,2252.0,sao paulo,SP,fashion_bags_accessories

In [10]:
obs_90_df["is_customer"] = (
    (obs_90_df["order_purchase_timestamp"] >= start_date_90) & 
    (obs_90_df["order_purchase_timestamp"] < ninety_days_later)
).astype(int)

obs_90_df["is_customer"].value_counts()

is_customer
0    3447
1     408
Name: count, dtype: int64

In [11]:
future_active_ids = obs_90_df[
    (obs_90_df["order_purchase_timestamp"] >= ninety_days_later) & 
    (obs_90_df["order_purchase_timestamp"] < end_date)
]["customer_unique_id"].unique()

future_active_ids

<StringArray>
['e021e698833bdeb89dfef3acb2e91f37', '4bc7250d4b42b3374eb6f41b12429592',
 '24a5c2b24a4467c37e2f54c1b311de93', '96b1c916f245f2462efcde3fce04bc3e',
 '1d4626b197f66aa6129c135ab09f1a7b', 'de53649541ad2006de823720ad65ca77',
 'c68949b701afe5343ce845dd492772e8', 'dc77e5e1396c807043f506f794d8fd1e',
 '0071f46a072a9ae25bbe4438b15efe9c', '6b7e1090d106aaee31d5ed12d2bbc2af',
 ...
 'b4a76bacd02c4823afd23c34e8ea92e4', '408aee96c75632a92e5079eee61da399',
 '60dce986762313a6e0b5d1ff0ecde379', '203443313490c84f08aadead1dbde82f',
 '7f6b0883d50738296c75dba682da3a3c', '205a1c797b2c6e626d560900a3ebde6b',
 'adc5def00980baefc876eb8023fb053d', 'a7941a8ddbfe8fde0bd23ae272484043',
 '95a3dcd03d8086e8510d9fe16f875ec7', '1c137fe37df712015f6488edafe8ece4']
Length: 2747, dtype: str

In [12]:
obs_90_df["churn_90"] = (
    (obs_90_df["is_customer"] == 1) & 
    (~obs_90_df["customer_unique_id"].isin(future_active_ids))
).astype(int)

obs_90_df["churn_90"]

55        0
132       0
140       0
151       0
166       0
         ..
119037    0
119038    0
119039    0
119044    0
119118    0
Name: churn_90, Length: 3855, dtype: int64

In [13]:
print(obs_90_df["churn_90"].value_counts())

churn_90
0    3447
1     408
Name: count, dtype: int64

In [14]:
dataset_90_df = obs_90_df.groupby(['customer_unique_id', 'order_purchase_timestamp', 'customer_city', 'customer_state', 'order_status']).agg({
    'price': 'sum',            # Total spent on the order (47.40 + 39.90)
    'freight_value': 'sum',    # Total shipping cost
    'payment_value': 'sum',    # Total amount charged to credit card
    'product_weight_g': 'sum', # Combined weight of the package


    # Categorical and indicator columns to pull forward
    'product_category_name_english': 'first',
    'is_customer': 'first',
    'churn_90': 'max',          # Keeps 1 if they churned, 0 otherwise
    'payment_sequential': 'max',
    'payment_type': 'first',
    'payment_installments': 'max'
}).reset_index()

dataset_90_df

,customer_unique_id,order_purchase_timestamp,customer_city,customer_state,order_status,price,freight_value,payment_value,product_weight_g,product_category_name_english,is_customer,churn_90,payment_sequential,payment_type,payment_installments
0,00115fc7123b5310cf6d3a3aa932699e,2017-01-21 21:58:35,brasilia,DF,delivered,59.99,16.12,76.11,525.0,sports_leisure,0,0,1.0,credit_card,1.0
1,002b4cd83fabaffaa475f78ea5ef3e08,2017-02-01 13:53:16,sao sebastiao do paraiso,MG,delivered,49.90,14.52,64.42,150.0,fashion_bags_accessories,0,0,1.0,credit_card,1.0
2,0032c76b20340da25249092a268ce66c,2016-10-06 11:32:00,charqueada,SP,delivered,128.90,16.04,144.94,5470.0,toys,1,1,1.0,credit_card,1.0
3,0055b522bc89cbfbf376d8b59a628470,2017-03-03 15:48:57,fortaleza,CE,delivered,328.00,36.75,364.75,1500.0,small_appliances,0,0,1.0,boleto,1.0
4,0071f46a072a9ae25bbe4438b15efe9c,2017-02-01 00:04:17,aracatuba,SP,unavailable,0.00,0.00,174.54,0.0,NaN,0,0,1.0,credit_card,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3132,ffa46fd1f769dfbdd6c039550b420949,2017-02-17 11:27:22,florianopolis,SC,delivered,79.90,15.77,95.67,825.0,cool_stuff,0,0,1.0,credit_card,1.0
3133,ffb973f2bb1c0cb807a99341a9b20dcd,2016-10-09 23:25:13,sao paulo,SP,delivered,87.30,21.72,218.04,3150.0,furniture_decor,1,1,1.0,credit_card,6.0
3134,ffba9f9dff87b05e310ecc46c8591044,2017-02-27 15:39:41,tailandia,PA,delivered,1591.20,35.63,1626.83,500.0,watches_gifts,0,0,1.0,credit_card,5.0
3135,ffebb6424578e7bb153322da9d65634f,2017-01-16 14:04:11,guarulhos,SP,delivered,629.00,36.70,665.70,7100.0,cool_stuff,0,0,1.0,credit_card,8.0
3136,ffff371b4d645b6ecea244b27531430a,2017-02-07 15:49:16,sinop,MT,delivered,89.90,22.56,112.46,600.0,auto,0,0,1.0,credit_card,1.0

In [15]:
dataset_90_df["is_customer"].value_counts()

is_customer
0    2809
1     328
Name: count, dtype: int64

In [16]:
dataset_90_df.to_csv(r"C:\Users\Hallen\Documents\mis_cosas\silvana\master\tfm-uned-churn\Data\churn_dataset_90_days1.csv", index=False)

------------------------------------

### **90 days term 2**

In [17]:
start_date_90_t2 = pd.to_datetime(end_date)

start_date_90_t2

Timestamp('2017-03-03 21:15:19')

In [18]:
ninety_days_later_t2 = start_date_90_t2 + pd.Timedelta(days= CHURN_DAYS)

ninety_days_later_t2

Timestamp('2017-06-01 21:15:19')

In [19]:
end_date_t2 = ninety_days_later_t2 + pd.Timedelta(days= CHURN_DAYS)

end_date_t2

Timestamp('2017-08-30 21:15:19')

In [20]:
obs_90_t2_df = olist_df[(olist_df["order_purchase_timestamp"]>= start_date_90_t2) & (olist_df["order_purchase_timestamp"] < end_date_t2)]

obs_90_t2_df

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,...,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,seller_zip_code_prefix,seller_city,seller_state,product_category_name_english
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP,00e7ee1b050b8499577073aeb2a297a1,delivered,2017-05-16 15:05:35,2017-05-16 15:22:12,2017-05-23 10:47:57,...,1141.0,1.0,8683.0,54.0,64.0,31.0,8577.0,itaquaquecetuba,SP,office_furniture
18,9b8ce803689b3562defaad4613ef426f,7f3a72e8f988c6e735ba118d54f47458,5416,sao paulo,SP,17825f24877a9289214c301ae0c9424b,delivered,2017-05-11 13:48:47,2017-05-13 11:55:16,2017-05-15 15:30:02,...,245.0,1.0,1383.0,50.0,10.0,40.0,14940.0,ibitinga,SP,bed_bath_table
19,9b8ce803689b3562defaad4613ef426f,7f3a72e8f988c6e735ba118d54f47458,5416,sao paulo,SP,17825f24877a9289214c301ae0c9424b,delivered,2017-05-11 13:48:47,2017-05-13 11:55:16,2017-05-15 15:30:02,...,245.0,1.0,1383.0,50.0,10.0,40.0,14940.0,ibitinga,SP,bed_bath_table
21,154c4ded6991bdfa3cd249d11abf4130,e607ede0e63436308660236f5a52da5e,88034,florianopolis,SC,830d8b3e6875ef6165ffc33219ab4fea,delivered,2017-08-13 10:03:36,2017-08-13 10:24:04,2017-08-14 18:43:45,...,60.0,1.0,2800.0,40.0,15.0,40.0,90230.0,porto alegre,RS,computers_accessories
26,237098a64674ae89babdc426746260fc,4390ddbb6276a66ff1736a6710205dca,82820,curitiba,PR,eac4ffbe456464bdc3ce5f001b6439c5,delivered,2017-04-14 11:24:56,2017-04-14 11:35:23,2017-04-17 10:43:50,...,1158.0,2.0,400.0,30.0,10.0,30.0,9350.0,maua,SP,baby
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119122,e5ed7280cd1a3ac2ba29fd6650d8867c,206e64e8af2633a2ebe158a7fcb860db,8560,poa,SP,53cbf33b674d602f6746cb90a9d874fd,delivered,2017-05-15 17:42:38,2017-05-16 03:25:20,2017-05-16 16:02:08,...,176.0,1.0,1825.0,53.0,10.0,40.0,14940.0,ibitinga,SP,home_confort
119128,ffa6d90c36a9c7004692ca50761c69d6,874c93d867b18eb09a5e2f071ee89458,13140,paulinia,SP,2816b0ec050fb4a136c32a6bda007a91,delivered,2017-03-27 16:26:18,2017-03-27 16:35:19,2017-03-29 16:27:26,...,567.0,1.0,1150.0,30.0,10.0,30.0,37540.0,santa rita do sapucai,MG,furniture_decor
119131,27b9b32173455ef32167540451749d0b,277490f0d435b602fe4475d4b89e9181,6727,cotia,SP,326c29ec5b89834b17aea7d85302fd70,delivered,2017-05-24 11:54:31,2017-05-25 02:50:25,2017-05-26 16:12:26,...,245.0,1.0,1383.0,50.0,10.0,40.0,14940.0,ibitinga,SP,bed_bath_table
119134,14308d2303a3e2bdf4939b86c46d2679,e7f8760e2bbd2f1986bebd99596c088e,66033,belem,PA,ec3a75fb0ac595e461765d2d854b1d08,delivered,2017-03-15 21:04:08,2017-03-15 21:04:08,2017-03-20 08:34:12,...,621.0,1.0,600.0,16.0,6.0,11.0,4256.0,sao paulo,SP,stationery
119135,14308d2303a3e2bdf4939b86c46d2679,e7f8760e2bbd2f1986bebd99596c088e,66033,belem,PA,ec3a75fb0ac595e461765d2d854b1d08,delivered,2017-03-15 21:04:08,2017-03-15 21:04:08,2017-03-20 08:34:12,...,621.0,1.0,600.0,16.0,6.0,11.0,4256.0,sao paulo,SP,stationery

In [21]:
obs_90_t2_df["is_customer"] = (
    (obs_90_t2_df["order_purchase_timestamp"] >= start_date_90_t2) & 
    (obs_90_t2_df["order_purchase_timestamp"] < ninety_days_later_t2)
).astype(int)

obs_90_t2_df["is_customer"].value_counts()

is_customer
0    13738
1    10452
Name: count, dtype: int64

In [22]:
future_active_ids_t2 = obs_90_t2_df[
    (obs_90_t2_df["order_purchase_timestamp"] >= ninety_days_later_t2) & 
    (obs_90_t2_df["order_purchase_timestamp"] < end_date_t2)
]["customer_unique_id"].unique()

future_active_ids_t2

<StringArray>
['e607ede0e63436308660236f5a52da5e', 'e079b18794454de9d2be5c12b4392294',
 '40febde16f4718a5def537786473b0be', 'd85547cd859833520b311b4458a14c1c',
 'b03e9d9818ee170e9d6b983803c7d406', '94b731a41867b47c3856e324840c4c99',
 '2b6082a140c439e2df870c85b0aa5e88', '7b24d0e6584ac5a21ec1256d96965500',
 'fa7e6f153b7724fda5c1d7cc7b9ae4ec', 'eabd76f3506262b0db0dda1d48394a9b',
 ...
 'd5f2fa89cdc594e8ea58a0c630a95c65', 'f60fe3cb5de099b3055c4cefada6c1c7',
 '7dc0dfe8b96d050f7189970017a693e8', '514f2a78d07928478ac9212b21b7acbc',
 '9b03f2721fb73962781bae9322b0c071', '8c8173e547e020f411aa55b2fceed861',
 'a5ba329297100ea689fa263768b35b8b', '81720bfb69887fe95390723af9748e9f',
 'db634985638ec4b6abf8734d7adde1ab', 'a2325193ac2e95b805642e3100f80af3']
Length: 11045, dtype: str

In [23]:
obs_90_t2_df["churn_90"] = (
    (obs_90_t2_df["is_customer"] == 1) & 
    (~obs_90_t2_df["customer_unique_id"].isin(future_active_ids_t2))
).astype(int)

obs_90_t2_df["churn_90"]

0         1
18        1
19        1
21        0
26        1
         ..
119122    1
119128    1
119131    1
119134    1
119135    1
Name: churn_90, Length: 24190, dtype: int64

In [24]:
print(obs_90_t2_df["churn_90"].value_counts())

churn_90
0    13853
1    10337
Name: count, dtype: int64

In [25]:
obs_90_t2_df = obs_90_t2_df.groupby(['customer_unique_id', 'order_purchase_timestamp', 'customer_city', 'customer_state', 'order_status']).agg({
    'price': 'sum',            # Total spent on the order (47.40 + 39.90)
    'freight_value': 'sum',    # Total shipping cost
    'payment_value': 'sum',    # Total amount charged to credit card
    'product_weight_g': 'sum', # Combined weight of the package


    # Categorical and indicator columns to pull forward
    'product_category_name_english': 'first',
    'is_customer': 'first',
    'churn_90': 'max',          # Keeps 1 if they churned, 0 otherwise
    'payment_sequential': 'max',
    'payment_type': 'first',
    'payment_installments': 'max'
}).reset_index()

obs_90_t2_df

,customer_unique_id,order_purchase_timestamp,customer_city,customer_state,order_status,price,freight_value,payment_value,product_weight_g,product_category_name_english,is_customer,churn_90,payment_sequential,payment_type,payment_installments
0,0000f46a3911fa3c0805444483337064,2017-03-10 21:05:03,sao jose,SC,delivered,69.00,17.22,86.22,1500.0,stationery,1,1,1.0,credit_card,8.0
1,0005e1862207bf6ccc02e4228effd9a0,2017-03-04 23:32:12,teresopolis,RJ,delivered,135.00,15.12,150.12,2250.0,fashion_bags_accessories,1,1,1.0,credit_card,3.0
2,0006fdc98a402fceb4eb0ee528f6a8d4,2017-07-18 09:23:10,mimoso do sul,ES,delivered,13.90,15.10,29.00,200.0,bed_bath_table,0,0,1.0,credit_card,2.0
3,000a5ad9c4601d2bbdd9ed765d5213b3,2017-08-11 13:45:15,porto alegre,RS,delivered,76.99,14.29,91.28,600.0,health_beauty,0,0,1.0,credit_card,3.0
4,000de6019bb59f34c099a907c151d855,2017-08-17 19:10:33,sao sebastiao,SP,delivered,229.80,27.64,514.88,3100.0,bed_bath_table,0,0,1.0,credit_card,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19901,ffedff0547d809c90c05c2691c51f9b7,2017-03-30 14:50:26,ribeirao preto,SP,delivered,17.90,14.52,32.42,225.0,housewares,1,1,1.0,credit_card,3.0
19902,ffef0ffa736c7b3d9af741611089729b,2017-05-29 22:07:05,nova venecia,ES,delivered,109.90,29.17,139.07,1136.0,sports_leisure,1,1,1.0,credit_card,1.0
19903,fff3a9369e4b7102fab406a334a678c3,2017-08-11 10:26:38,brasilia,DF,delivered,84.90,17.84,102.74,1450.0,luggage_accessories,0,0,1.0,credit_card,2.0
19904,fffcf5a5ff07b0908bd4e2dbc735a684,2017-06-08 21:00:36,sanharo,PE,delivered,1570.00,497.42,4134.84,60000.0,health_beauty,0,0,1.0,credit_card,10.0
19905,ffffd2657e2aad2907e67c3e9daecbeb,2017-05-02 20:18:45,campo largo,PR,delivered,56.99,14.57,71.56,400.0,perfumery,1,1,1.0,credit_card,4.0

In [26]:
obs_90_t2_df.to_csv(r"C:\Users\Hallen\Documents\mis_cosas\silvana\master\tfm-uned-churn\Data\churn_dataset_90_days2.csv", index=False)

-----

### **90 days term 3**

In [27]:
start_date_90_t3 = pd.to_datetime(end_date_t2)

start_date_90_t3

Timestamp('2017-08-30 21:15:19')

In [28]:
ninety_days_later_t3 = start_date_90_t3 + pd.Timedelta(days= CHURN_DAYS)

ninety_days_later_t3

Timestamp('2017-11-28 21:15:19')

In [29]:
end_date_t3 = ninety_days_later_t3 + pd.Timedelta(days= CHURN_DAYS)

end_date_t3

Timestamp('2018-02-26 21:15:19')

In [30]:
obs_90_t3_df = olist_df[(olist_df["order_purchase_timestamp"]>= start_date_90_t3) & (olist_df["order_purchase_timestamp"] < end_date_t3)]

obs_90_t3_df

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,...,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,seller_zip_code_prefix,seller_city,seller_state,product_category_name_english
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP,29150127e6685892b6eab3eec79f59c7,delivered,2018-01-12 20:48:24,2018-01-12 20:58:32,2018-01-15 17:14:59,...,1002.0,3.0,10150.0,89.0,15.0,40.0,88303.0,itajai,SC,housewares
5,879864dab9bc3047522c92c82e1212b8,4c93744516667ad3b8f1fb645a3116a4,89254,jaragua do sul,SC,5741ea1f91b5fbab2bd2dc653a5b5099,delivered,2017-09-14 18:14:31,2017-09-14 18:25:11,2017-09-18 21:27:40,...,282.0,2.0,4450.0,60.0,15.0,15.0,5141.0,pirituba,SP,sports_leisure
6,fd826e7cf63160e536e0908c76c3f441,addec96d2e059c80c30fe6871d30d177,4534,sao paulo,SP,36e694cf4cbc2a4803200c35e84abdc4,delivered,2018-02-19 14:38:35,2018-02-19 14:50:37,2018-02-20 00:03:39,...,322.0,3.0,100.0,16.0,3.0,13.0,4102.0,sao paulo,SP,computers_accessories
7,5e274e7a0c3809e14aba7ad5aae0d407,57b2a98a409812fe9618067b6b8ebe4f,35182,timoteo,MG,1093c8304c7a003280dd34598194913d,delivered,2017-11-16 19:29:02,2017-11-16 19:55:41,2017-11-22 16:46:33,...,NaN,NaN,250.0,15.0,8.0,20.0,4142.0,sao paulo,SP,NaN
8,5adf08e34b2e993982a47070956c5c65,1175e95fb47ddff9de6b2b06188f7e0d,81560,curitiba,PR,1ebeea841c590e86a14a0d7a48e7d062,delivered,2018-01-18 12:35:44,2018-01-18 12:56:32,2018-01-18 23:25:35,...,739.0,5.0,350.0,28.0,10.0,12.0,21210.0,rio de janeiro,RJ,toys
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119129,1ed0c832c2dd99570a59260e71768bdf,82d46759af0369aad49084bacf85a6c3,37610,bom repouso,MG,51c6d2f460589fa7b65f2da51e860206,delivered,2017-11-14 12:04:09,2017-11-14 12:15:25,2017-11-27 20:44:47,...,63.0,1.0,6185.0,63.0,11.0,20.0,12914.0,braganca paulista,SP,electronics
119130,1ed0c832c2dd99570a59260e71768bdf,82d46759af0369aad49084bacf85a6c3,37610,bom repouso,MG,51c6d2f460589fa7b65f2da51e860206,delivered,2017-11-14 12:04:09,2017-11-14 12:15:25,2017-11-27 20:44:47,...,63.0,1.0,6185.0,63.0,11.0,20.0,12914.0,braganca paulista,SP,electronics
119137,7fe2e80252a9ea476f950ae8f85b0f8f,4b5820135d360a45552b5163835b1d89,35500,divinopolis,MG,c9aea907527f5d4f5fb44955c18a79fb,delivered,2017-12-17 23:13:41,2017-12-18 00:17:27,2017-12-20 18:52:08,...,210.0,2.0,1100.0,48.0,24.0,23.0,4773.0,sao paulo,SP,housewares
119141,56b18e2166679b8a959d72dd06da27f9,73c2643a0a458b49f58cea58833b192e,92120,canoas,RS,e31ec91cea1ecf97797787471f98a8c2,delivered,2017-11-03 21:08:33,2017-11-03 21:31:20,2017-11-06 18:24:41,...,452.0,1.0,710.0,19.0,13.0,14.0,14840.0,guariba,SP,watches_gifts
119142,274fa6071e5e17fe303b9748641082c8,84732c5050c01db9b23e19ba39899398,6703,cotia,SP,28db69209a75e59f20ccbb5c36a20b90,delivered,2017-12-19 14:27:23,2017-12-19 18:50:39,2017-12-21 19:17:21,...,933.0,1.0,50.0,16.0,5.0,11.0,3804.0,sao paulo,SP,perfumery

In [31]:
obs_90_t3_df["is_customer"] = (
    (obs_90_t3_df["order_purchase_timestamp"] >= start_date_90_t3) & 
    (obs_90_t3_df["order_purchase_timestamp"] < ninety_days_later_t3)
).astype(int)

obs_90_t3_df["is_customer"].value_counts()

is_customer
0    23362
1    19479
Name: count, dtype: int64

In [32]:
future_active_ids_t3 = obs_90_t3_df[
    (obs_90_t3_df["order_purchase_timestamp"] >= ninety_days_later_t3) & 
    (obs_90_t3_df["order_purchase_timestamp"] < end_date_t3)
]["customer_unique_id"].unique()

future_active_ids_t3

<StringArray>
['290c77bc529b7ac935b93aa66c333dc3', 'addec96d2e059c80c30fe6871d30d177',
 '1175e95fb47ddff9de6b2b06188f7e0d', '9afe194fb833f79e300e37e580171f22',
 '2a46fb94aef5cbeeb850418118cee090', '21f748a16f4e1688a9014eb3ee6fa325',
 '5f102dd37243f152aec3607970aad100', 'dd992305cba295d997f263dbdf4e8c2e',
 '5ad58a4e6a1a656b6bed070cadbaa003', 'c9158d089637ab443c78984d20da7fc0',
 ...
 '5cbfdb85ec130898108b32c50d619c39', '3011394a1b8d1b04e425dd5dc77cbaaf',
 '3cc6f2e1b9199837fabb35ff4bf24884', '6667649dc575c65058507349be078d4f',
 'c64ede6d0ae8901b1b6fb03528c1b7e6', '522e244a96d13876c5bac4985a8d5075',
 'b96d6a178adbabf269fd843b37327798', '15637b62dfa4c5a9df846b22beef0994',
 '4b5820135d360a45552b5163835b1d89', '84732c5050c01db9b23e19ba39899398']
Length: 19289, dtype: str

In [33]:
obs_90_t3_df["churn_90"] = (
    (obs_90_t3_df["is_customer"] == 1) & 
    (~obs_90_t3_df["customer_unique_id"].isin(future_active_ids_t3))
).astype(int)

obs_90_t3_df["churn_90"]

1         0
5         1
6         0
7         1
8         0
         ..
119129    1
119130    1
119137    0
119141    1
119142    0
Name: churn_90, Length: 42841, dtype: int64

In [34]:
print(obs_90_t3_df["churn_90"].value_counts())

churn_90
0    23574
1    19267
Name: count, dtype: int64

In [35]:
obs_90_t3_df = obs_90_t3_df.groupby(['customer_unique_id', 'order_purchase_timestamp', 'customer_city', 'customer_state', 'order_status']).agg({
    'price': 'sum',            # Total spent on the order (47.40 + 39.90)
    'freight_value': 'sum',    # Total shipping cost
    'payment_value': 'sum',    # Total amount charged to credit card
    'product_weight_g': 'sum', # Combined weight of the package


    # Categorical and indicator columns to pull forward
    'product_category_name_english': 'first',
    'is_customer': 'first',
    'churn_90': 'max',          # Keeps 1 if they churned, 0 otherwise
    'payment_sequential': 'max',
    'payment_type': 'first',
    'payment_installments': 'max'
}).reset_index()

obs_90_t3_df

,customer_unique_id,order_purchase_timestamp,customer_city,customer_state,order_status,price,freight_value,payment_value,product_weight_g,product_category_name_english,is_customer,churn_90,payment_sequential,payment_type,payment_installments
0,0000f6ccb0745a6a4b88665a16c9f078,2017-10-12 20:29:41,belem,PA,delivered,25.99,17.63,43.62,150.0,telephony,1,1,1.0,credit_card,4.0
1,0004aac84e0df4da2b147fca70cf8255,2017-11-14 19:45:42,sorocaba,SP,delivered,180.00,16.89,196.89,6050.0,telephony,1,1,1.0,credit_card,6.0
2,00082cbe03e478190aadbea78542e933,2017-11-19 15:22:02,itapeva,SP,delivered,79.00,47.26,126.26,20900.0,luggage_accessories,1,1,1.0,boleto,1.0
3,000bfa1d2f1a41876493be685390d6d3,2017-09-29 14:46:58,santos,SP,delivered,70.00,23.70,93.70,300.0,fashion_bags_accessories,1,1,1.0,credit_card,4.0
4,000c8bdb58a29e7115cfc257230fb21b,2017-12-12 22:53:35,belo horizonte,MG,delivered,13.90,15.10,29.00,175.0,bed_bath_table,0,0,1.0,credit_card,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35549,fff7219c86179ca6441b8f37823ba3d3,2017-12-27 18:57:38,cachoeiras de macacu,RJ,delivered,245.80,20.00,531.60,3500.0,bed_bath_table,0,0,1.0,debit_card,1.0
35550,fffa431dd3fcdefea4b1777d114144f2,2017-10-30 20:39:50,bom jardim,RJ,delivered,64.99,16.21,81.20,3585.0,cool_stuff,1,1,1.0,boleto,1.0
35551,fffb09418989a0dbff854a28163e47c6,2017-12-17 19:14:35,veranopolis,RS,delivered,58.00,15.16,73.16,213.0,watches_gifts,0,0,1.0,boleto,1.0
35552,fffbf87b7a1a6fa8b03f081c5f51a201,2017-12-27 22:36:41,fortaleza,CE,delivered,149.00,18.32,167.32,350.0,NaN,0,0,1.0,credit_card,2.0
35553,fffea47cd6d3cc0a88bd621562a9d061,2017-12-10 20:07:56,feira de santana,BA,delivered,64.89,19.69,84.58,1720.0,baby,0,0,1.0,credit_card,1.0

In [36]:
obs_90_t3_df.to_csv(r"C:\Users\Hallen\Documents\mis_cosas\silvana\master\tfm-uned-churn\Data\churn_dataset_90_days3.csv", index=False)

----------------------------------------------------------------------
----------------------------------

## 120 days

### **120 days term 1**

In [37]:
CHURN_DAYS = 120

In [38]:
start_date_120 = olist_df["order_purchase_timestamp"].min()

start_date_120

Timestamp('2016-09-04 21:15:19')

In [39]:
one_hundred_twenty_days_later = start_date_120 + pd.Timedelta(days= CHURN_DAYS)

one_hundred_twenty_days_later

Timestamp('2017-01-02 21:15:19')

In [40]:
end_date_one_hundred_twenty = one_hundred_twenty_days_later + pd.Timedelta(days= CHURN_DAYS)

end_date_one_hundred_twenty

Timestamp('2017-05-02 21:15:19')

In [41]:
obs_120_df = olist_df[(olist_df["order_purchase_timestamp"]>= start_date_120) & (olist_df["order_purchase_timestamp"] < end_date_one_hundred_twenty)]

obs_120_df

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,...,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,seller_zip_code_prefix,seller_city,seller_state,product_category_name_english
26,237098a64674ae89babdc426746260fc,4390ddbb6276a66ff1736a6710205dca,82820,curitiba,PR,eac4ffbe456464bdc3ce5f001b6439c5,delivered,2017-04-14 11:24:56,2017-04-14 11:35:23,2017-04-17 10:43:50,...,1158.0,2.0,400.0,30.0,10.0,30.0,9350.0,maua,SP,baby
55,4d27341acd30a36bca39008ee9bb9050,e021e698833bdeb89dfef3acb2e91f37,89254,jaragua do sul,SC,38e2829123a2bd1cbe111564824d0abb,delivered,2017-01-26 11:14:58,2017-01-26 11:25:21,2017-01-27 12:19:14,...,1236.0,1.0,340.0,17.0,7.0,16.0,85801.0,cascavel,PR,consoles_games
75,8276de07ef25225d412b8462d73f8664,332cf4e83e16004ba7dca932ce82475b,90010,porto alegre,RS,b63fff1ef8b6201df68bb611ee41129e,delivered,2017-04-02 22:15:27,2017-04-04 05:55:19,2017-04-13 16:28:06,...,154.0,1.0,2600.0,40.0,45.0,39.0,8577.0,itaquaquecetuba,SP,office_furniture
90,0aae2862f8eac77f10a34f44860720ac,cd076285a12f40041b32f5ad8c98699f,5890,sao paulo,SP,0c65b54ed2c147ffd0092eb2308ee63d,delivered,2017-03-23 11:07:12,2017-03-23 11:07:12,2017-03-24 10:36:22,...,472.0,1.0,4300.0,50.0,20.0,20.0,37706.0,pocos de caldas,MG,drinks
91,0aae2862f8eac77f10a34f44860720ac,cd076285a12f40041b32f5ad8c98699f,5890,sao paulo,SP,0c65b54ed2c147ffd0092eb2308ee63d,delivered,2017-03-23 11:07:12,2017-03-23 11:07:12,2017-03-24 10:36:22,...,472.0,1.0,4300.0,50.0,20.0,20.0,37706.0,pocos de caldas,MG,drinks
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119117,a1b5ca506b592bb72d4caadcbfe71385,c811311629fd3d76f5ca5eeb2abfa7e8,17511,marilia,SP,65f3d65b89d1fdde15dc314858c9c161,delivered,2017-04-10 00:08:56,2017-04-10 01:02:42,2017-04-10 12:33:22,...,179.0,6.0,200.0,16.0,2.0,20.0,5849.0,sao paulo,SP,fashion_bags_accessories
119118,be631308cb609ff74d0e0fb54815e18c,1c137fe37df712015f6488edafe8ece4,36255,aracitaba,MG,b7ae7c643ef9274727f48dcb0ba08593,delivered,2017-01-25 16:51:27,2017-01-27 11:50:24,2017-01-30 16:22:11,...,419.0,4.0,200.0,16.0,5.0,11.0,2252.0,sao paulo,SP,fashion_bags_accessories
119128,ffa6d90c36a9c7004692ca50761c69d6,874c93d867b18eb09a5e2f071ee89458,13140,paulinia,SP,2816b0ec050fb4a136c32a6bda007a91,delivered,2017-03-27 16:26:18,2017-03-27 16:35:19,2017-03-29 16:27:26,...,567.0,1.0,1150.0,30.0,10.0,30.0,37540.0,santa rita do sapucai,MG,furniture_decor
119134,14308d2303a3e2bdf4939b86c46d2679,e7f8760e2bbd2f1986bebd99596c088e,66033,belem,PA,ec3a75fb0ac595e461765d2d854b1d08,delivered,2017-03-15 21:04:08,2017-03-15 21:04:08,2017-03-20 08:34:12,...,621.0,1.0,600.0,16.0,6.0,11.0,4256.0,sao paulo,SP,stationery
119135,14308d2303a3e2bdf4939b86c46d2679,e7f8760e2bbd2f1986bebd99596c088e,66033,belem,PA,ec3a75fb0ac595e461765d2d854b1d08,delivered,2017-03-15 21:04:08,2017-03-15 21:04:08,2017-03-20 08:34:12,...,621.0,1.0,600.0,16.0,6.0,11.0,4256.0,sao paulo,SP,stationery

In [42]:
obs_120_df["is_customer"] = (
    (obs_120_df["order_purchase_timestamp"] >= start_date_120) & 
    (obs_120_df["order_purchase_timestamp"] < one_hundred_twenty_days_later)
).astype(int)

obs_120_df["is_customer"]

26        0
55        0
75        0
90        0
91        0
         ..
119117    0
119118    0
119128    0
119134    0
119135    0
Name: is_customer, Length: 9957, dtype: int64

In [43]:
future_active_ids = obs_120_df[
    (obs_120_df["order_purchase_timestamp"] >= one_hundred_twenty_days_later) & 
    (obs_120_df["order_purchase_timestamp"] < end_date_one_hundred_twenty)
]["customer_unique_id"].unique()

future_active_ids

<StringArray>
['4390ddbb6276a66ff1736a6710205dca', 'e021e698833bdeb89dfef3acb2e91f37',
 '332cf4e83e16004ba7dca932ce82475b', 'cd076285a12f40041b32f5ad8c98699f',
 'd491a65a6ef3c04e145d37395996bad7', '90d479448b39ad9586d05da64cfb695b',
 '4bc7250d4b42b3374eb6f41b12429592', '24a5c2b24a4467c37e2f54c1b311de93',
 '96b1c916f245f2462efcde3fce04bc3e', '1d4626b197f66aa6129c135ab09f1a7b',
 ...
 'adc5def00980baefc876eb8023fb053d', 'a7941a8ddbfe8fde0bd23ae272484043',
 '95a3dcd03d8086e8510d9fe16f875ec7', 'a662a415dbbb5a154b3d38aa4fc86e57',
 'e097d846931763789c3fd00b27f3c325', '5f2971f9805e3ccb030226e30c8e8390',
 'c811311629fd3d76f5ca5eeb2abfa7e8', '1c137fe37df712015f6488edafe8ece4',
 '874c93d867b18eb09a5e2f071ee89458', 'e7f8760e2bbd2f1986bebd99596c088e']
Length: 7724, dtype: str

In [44]:
obs_120_df["churn_120"] = (
    (obs_120_df["is_customer"] == 1) & 
    (~obs_120_df["customer_unique_id"].isin(future_active_ids))
).astype(int)

obs_120_df["churn_120"]

26        0
55        0
75        0
90        0
91        0
         ..
119117    0
119118    0
119128    0
119134    0
119135    0
Name: churn_120, Length: 9957, dtype: int64

In [45]:
dataset_120_df = obs_120_df.groupby(['customer_unique_id', 'order_purchase_timestamp', 'customer_city', 'customer_state', 'order_status']).agg({
    'price': 'sum',            # Total spent on the order (47.40 + 39.90)
    'freight_value': 'sum',    # Total shipping cost
    'payment_value': 'sum',    # Total amount charged to credit card
    'product_weight_g': 'sum', # Combined weight of the package


    # Categorical and indicator columns to pull forward
    'product_category_name_english': 'first',
    'is_customer': 'first',
    'churn_120': 'max',          # Keeps 1 if they churned, 0 otherwise
    'payment_sequential': 'max',
    'payment_type': 'first',
    'payment_installments': 'max'
}).reset_index()

dataset_120_df

,customer_unique_id,order_purchase_timestamp,customer_city,customer_state,order_status,price,freight_value,payment_value,product_weight_g,product_category_name_english,is_customer,churn_120,payment_sequential,payment_type,payment_installments
0,0000f46a3911fa3c0805444483337064,2017-03-10 21:05:03,sao jose,SC,delivered,69.00,17.22,86.22,1500.0,stationery,0,0,1.0,credit_card,8.0
1,0005e1862207bf6ccc02e4228effd9a0,2017-03-04 23:32:12,teresopolis,RJ,delivered,135.00,15.12,150.12,2250.0,fashion_bags_accessories,0,0,1.0,credit_card,3.0
2,00115fc7123b5310cf6d3a3aa932699e,2017-01-21 21:58:35,brasilia,DF,delivered,59.99,16.12,76.11,525.0,sports_leisure,0,0,1.0,credit_card,1.0
3,0011805441c0d1b68b48002f1d005526,2017-04-24 13:36:48,goianesia do para,PA,delivered,269.00,28.14,297.14,200.0,computers_accessories,0,0,1.0,credit_card,10.0
4,00191a9719ef48ebb5860b130347bf33,2017-04-19 11:32:09,jarinu,SP,delivered,47.90,10.96,58.86,600.0,bed_bath_table,0,0,1.0,credit_card,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8193,ffe3e199b9d0b7fb7d2d29a5b9498447,2017-03-15 17:16:36,uberlandia,MG,delivered,146.90,15.20,162.10,350.0,home_construction,0,0,1.0,boleto,1.0
8194,ffebb6424578e7bb153322da9d65634f,2017-01-16 14:04:11,guarulhos,SP,delivered,629.00,36.70,665.70,7100.0,cool_stuff,0,0,1.0,credit_card,8.0
8195,ffedff0547d809c90c05c2691c51f9b7,2017-03-30 14:50:26,ribeirao preto,SP,delivered,17.90,14.52,32.42,225.0,housewares,0,0,1.0,credit_card,3.0
8196,ffff371b4d645b6ecea244b27531430a,2017-02-07 15:49:16,sinop,MT,delivered,89.90,22.56,112.46,600.0,auto,0,0,1.0,credit_card,1.0
8197,ffffd2657e2aad2907e67c3e9daecbeb,2017-05-02 20:18:45,campo largo,PR,delivered,56.99,14.57,71.56,400.0,perfumery,0,0,1.0,credit_card,4.0

In [46]:
dataset_120_df.to_csv(r"C:\Users\Hallen\Documents\mis_cosas\silvana\master\tfm-uned-churn\Data\churn_dataset_120_days1.csv", index=False)

-------

### **120 days term 2**

In [47]:
start_date_120_t2 = end_date_one_hundred_twenty

start_date_120_t2

Timestamp('2017-05-02 21:15:19')

In [48]:
one_hundred_twenty_days_later_t2 = start_date_120_t2 + pd.Timedelta(days= CHURN_DAYS)

one_hundred_twenty_days_later_t2

Timestamp('2017-08-30 21:15:19')

In [49]:
end_date_one_hundred_twenty_t2 = one_hundred_twenty_days_later_t2 + pd.Timedelta(days= CHURN_DAYS)

end_date_one_hundred_twenty_t2

Timestamp('2017-12-28 21:15:19')

In [50]:
obs_120_df_t2 = olist_df[(olist_df["order_purchase_timestamp"]>= start_date_120_t2) & (olist_df["order_purchase_timestamp"] < end_date_one_hundred_twenty_t2)]

obs_120_df_t2

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,...,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,seller_zip_code_prefix,seller_city,seller_state,product_category_name_english
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP,00e7ee1b050b8499577073aeb2a297a1,delivered,2017-05-16 15:05:35,2017-05-16 15:22:12,2017-05-23 10:47:57,...,1141.0,1.0,8683.0,54.0,64.0,31.0,8577.0,itaquaquecetuba,SP,office_furniture
5,879864dab9bc3047522c92c82e1212b8,4c93744516667ad3b8f1fb645a3116a4,89254,jaragua do sul,SC,5741ea1f91b5fbab2bd2dc653a5b5099,delivered,2017-09-14 18:14:31,2017-09-14 18:25:11,2017-09-18 21:27:40,...,282.0,2.0,4450.0,60.0,15.0,15.0,5141.0,pirituba,SP,sports_leisure
7,5e274e7a0c3809e14aba7ad5aae0d407,57b2a98a409812fe9618067b6b8ebe4f,35182,timoteo,MG,1093c8304c7a003280dd34598194913d,delivered,2017-11-16 19:29:02,2017-11-16 19:55:41,2017-11-22 16:46:33,...,NaN,NaN,250.0,15.0,8.0,20.0,4142.0,sao paulo,SP,NaN
10,9fb35e4ed6f0a14a4977cd9aea4042bb,2a7745e1ed516b289ed9b29c7d0539a5,39400,montes claros,MG,8428e578bb1cf839ae26a6b7615502b9,delivered,2017-11-27 17:23:20,2017-11-27 18:01:20,2017-11-28 23:04:41,...,1117.0,8.0,300.0,31.0,17.0,27.0,13405.0,piracicaba,SP,auto
12,b2d1536598b73a9abd18e0d75d92f0a3,918dc87cd72cd9f6ed4bd442ed785235,18682,lencois paulista,SP,83d8f70418eefd96f37b483dff430305,delivered,2017-09-09 09:54:57,2017-09-09 10:10:17,2017-09-12 12:42:43,...,624.0,5.0,2000.0,20.0,10.0,20.0,37590.0,jacutinga,MG,air_conditioning
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119130,1ed0c832c2dd99570a59260e71768bdf,82d46759af0369aad49084bacf85a6c3,37610,bom repouso,MG,51c6d2f460589fa7b65f2da51e860206,delivered,2017-11-14 12:04:09,2017-11-14 12:15:25,2017-11-27 20:44:47,...,63.0,1.0,6185.0,63.0,11.0,20.0,12914.0,braganca paulista,SP,electronics
119131,27b9b32173455ef32167540451749d0b,277490f0d435b602fe4475d4b89e9181,6727,cotia,SP,326c29ec5b89834b17aea7d85302fd70,delivered,2017-05-24 11:54:31,2017-05-25 02:50:25,2017-05-26 16:12:26,...,245.0,1.0,1383.0,50.0,10.0,40.0,14940.0,ibitinga,SP,bed_bath_table
119137,7fe2e80252a9ea476f950ae8f85b0f8f,4b5820135d360a45552b5163835b1d89,35500,divinopolis,MG,c9aea907527f5d4f5fb44955c18a79fb,delivered,2017-12-17 23:13:41,2017-12-18 00:17:27,2017-12-20 18:52:08,...,210.0,2.0,1100.0,48.0,24.0,23.0,4773.0,sao paulo,SP,housewares
119141,56b18e2166679b8a959d72dd06da27f9,73c2643a0a458b49f58cea58833b192e,92120,canoas,RS,e31ec91cea1ecf97797787471f98a8c2,delivered,2017-11-03 21:08:33,2017-11-03 21:31:20,2017-11-06 18:24:41,...,452.0,1.0,710.0,19.0,13.0,14.0,14840.0,guariba,SP,watches_gifts
119142,274fa6071e5e17fe303b9748641082c8,84732c5050c01db9b23e19ba39899398,6703,cotia,SP,28db69209a75e59f20ccbb5c36a20b90,delivered,2017-12-19 14:27:23,2017-12-19 18:50:39,2017-12-21 19:17:21,...,933.0,1.0,50.0,16.0,5.0,11.0,3804.0,sao paulo,SP,perfumery

In [51]:
obs_120_df_t2["is_customer"] = (
    (obs_120_df_t2["order_purchase_timestamp"] >= start_date_120_t2) & 
    (obs_120_df_t2["order_purchase_timestamp"] < one_hundred_twenty_days_later_t2)
).astype(int)

obs_120_df_t2["is_customer"]

0         1
5         0
7         0
10        0
12        0
         ..
119130    0
119131    1
119137    0
119141    0
119142    0
Name: is_customer, Length: 44600, dtype: int64

In [ ]:
future_active_ids_t2 = obs_120_df_t2[
    (obs_120_df_t2["order_purchase_timestamp"] >= one_hundred_twenty_days_later_t2) & 
    (obs_120_df_t2["order_purchase_timestamp"] < end_date_one_hundred_twenty_t2)
]["customer_unique_id"].unique()

future_active_ids_t2

<StringArray>
['4c93744516667ad3b8f1fb645a3116a4', '918dc87cd72cd9f6ed4bd442ed785235',
 'e607ede0e63436308660236f5a52da5e', '424aca6872c5bab80780a8dec03b7516',
 '40febde16f4718a5def537786473b0be', '66cc90195ca44cc7ac6a1cd0e1e1e7b2',
 'b03e9d9818ee170e9d6b983803c7d406', 'b3548d0cec408ae13d143bb4eeebaa6c',
 'd89e05e2d23c3d8247aeecd07758004b', 'dad5018ffc0de85eb72f72575b552784',
 ...
 '54795167137a9242b5f13793c78f99aa', 'd5f2fa89cdc594e8ea58a0c630a95c65',
 '514f2a78d07928478ac9212b21b7acbc', '81978a4296d6dfda023d617d7695a9f5',
 '24c3223c7a70060b70168a0d8594c8a7', '9b03f2721fb73962781bae9322b0c071',
 '8c8173e547e020f411aa55b2fceed861', 'a10c0d1e68e919e3d91ed940a0ba6aed',
 'a5ba329297100ea689fa263768b35b8b', '81720bfb69887fe95390723af9748e9f']
Length: 13521, dtype: str

In [52]:
obs_120_df_t2["churn_120"] = (
    (obs_120_df_t2["is_customer"] == 1) & 
    (~obs_120_df_t2["customer_unique_id"].isin(future_active_ids_t2))
).astype(int)

obs_120_df_t2["churn_120"]

0         1
5         0
7         0
10        0
12        0
         ..
119130    0
119131    1
119137    0
119141    0
119142    0
Name: churn_120, Length: 44600, dtype: int64

In [53]:
dataset_120_df_t2 = obs_120_df_t2.groupby(['customer_unique_id', 'order_purchase_timestamp', 'customer_city', 'customer_state', 'order_status']).agg({
    'price': 'sum',            # Total spent on the order (47.40 + 39.90)
    'freight_value': 'sum',    # Total shipping cost
    'payment_value': 'sum',    # Total amount charged to credit card
    'product_weight_g': 'sum', # Combined weight of the package


    # Categorical and indicator columns to pull forward
    'product_category_name_english': 'first',
    'is_customer': 'first',
    'churn_120': 'max',          # Keeps 1 if they churned, 0 otherwise
    'payment_sequential': 'max',
    'payment_type': 'first',
    'payment_installments': 'max'
}).reset_index()

dataset_120_df_t2

,customer_unique_id,order_purchase_timestamp,customer_city,customer_state,order_status,price,freight_value,payment_value,product_weight_g,product_category_name_english,is_customer,churn_120,payment_sequential,payment_type,payment_installments
0,0000f6ccb0745a6a4b88665a16c9f078,2017-10-12 20:29:41,belem,PA,delivered,25.99,17.63,43.62,150.0,telephony,0,0,1.0,credit_card,4.0
1,0004aac84e0df4da2b147fca70cf8255,2017-11-14 19:45:42,sorocaba,SP,delivered,180.00,16.89,196.89,6050.0,telephony,0,0,1.0,credit_card,6.0
2,0006fdc98a402fceb4eb0ee528f6a8d4,2017-07-18 09:23:10,mimoso do sul,ES,delivered,13.90,15.10,29.00,200.0,bed_bath_table,1,0,1.0,credit_card,2.0
3,00082cbe03e478190aadbea78542e933,2017-11-19 15:22:02,itapeva,SP,delivered,79.00,47.26,126.26,20900.0,luggage_accessories,0,0,1.0,boleto,1.0
4,000a5ad9c4601d2bbdd9ed765d5213b3,2017-08-11 13:45:15,porto alegre,RS,delivered,76.99,14.29,91.28,600.0,health_beauty,1,0,1.0,credit_card,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36751,fffa431dd3fcdefea4b1777d114144f2,2017-10-30 20:39:50,bom jardim,RJ,delivered,64.99,16.21,81.20,3585.0,cool_stuff,0,0,1.0,boleto,1.0
36752,fffb09418989a0dbff854a28163e47c6,2017-12-17 19:14:35,veranopolis,RS,delivered,58.00,15.16,73.16,213.0,watches_gifts,0,0,1.0,boleto,1.0
36753,fffbf87b7a1a6fa8b03f081c5f51a201,2017-12-27 22:36:41,fortaleza,CE,delivered,149.00,18.32,167.32,350.0,NaN,0,0,1.0,credit_card,2.0
36754,fffcf5a5ff07b0908bd4e2dbc735a684,2017-06-08 21:00:36,sanharo,PE,delivered,1570.00,497.42,4134.84,60000.0,health_beauty,1,0,1.0,credit_card,10.0
36755,fffea47cd6d3cc0a88bd621562a9d061,2017-12-10 20:07:56,feira de santana,BA,delivered,64.89,19.69,84.58,1720.0,baby,0,0,1.0,credit_card,1.0

In [54]:
dataset_120_df_t2.to_csv(r"C:\Users\Hallen\Documents\mis_cosas\silvana\master\tfm-uned-churn\Data\churn_dataset_120_days2.csv", index=False)

-------
-------

## 110 days

### **110 days term 1**

In [55]:
CHURN_DAYS = 150

In [56]:
start_date_150 = olist_df["order_purchase_timestamp"].min()

start_date_150

Timestamp('2016-09-04 21:15:19')

In [57]:
one_hundred_fifty_days_later = start_date_150 + pd.Timedelta(days= CHURN_DAYS)

one_hundred_fifty_days_later

Timestamp('2017-02-01 21:15:19')

In [58]:
end_date_hundred_fifty = one_hundred_fifty_days_later + pd.Timedelta(days= CHURN_DAYS)

end_date_hundred_fifty

Timestamp('2017-07-01 21:15:19')

In [59]:
obs_150_df = olist_df[(olist_df["order_purchase_timestamp"]>= start_date_150) & (olist_df["order_purchase_timestamp"] < end_date_hundred_fifty)]

obs_150_df

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,...,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,seller_zip_code_prefix,seller_city,seller_state,product_category_name_english
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP,00e7ee1b050b8499577073aeb2a297a1,delivered,2017-05-16 15:05:35,2017-05-16 15:22:12,2017-05-23 10:47:57,...,1141.0,1.0,8683.0,54.0,64.0,31.0,8577.0,itaquaquecetuba,SP,office_furniture
18,9b8ce803689b3562defaad4613ef426f,7f3a72e8f988c6e735ba118d54f47458,5416,sao paulo,SP,17825f24877a9289214c301ae0c9424b,delivered,2017-05-11 13:48:47,2017-05-13 11:55:16,2017-05-15 15:30:02,...,245.0,1.0,1383.0,50.0,10.0,40.0,14940.0,ibitinga,SP,bed_bath_table
19,9b8ce803689b3562defaad4613ef426f,7f3a72e8f988c6e735ba118d54f47458,5416,sao paulo,SP,17825f24877a9289214c301ae0c9424b,delivered,2017-05-11 13:48:47,2017-05-13 11:55:16,2017-05-15 15:30:02,...,245.0,1.0,1383.0,50.0,10.0,40.0,14940.0,ibitinga,SP,bed_bath_table
26,237098a64674ae89babdc426746260fc,4390ddbb6276a66ff1736a6710205dca,82820,curitiba,PR,eac4ffbe456464bdc3ce5f001b6439c5,delivered,2017-04-14 11:24:56,2017-04-14 11:35:23,2017-04-17 10:43:50,...,1158.0,2.0,400.0,30.0,10.0,30.0,9350.0,maua,SP,baby
30,6e359a57a91f84095cc64e1b351aef8c,2e6a42a9b5cbb0da62988694f18ee295,4571,sao paulo,SP,a8f5a2b22f55e0af45b300929d1fdc7d,delivered,2017-05-15 17:58:25,2017-05-15 18:10:18,2017-05-16 15:41:37,...,445.0,1.0,1000.0,34.0,25.0,25.0,85900.0,toledo,PR,kitchen_dining_laundry_garden_furniture
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119122,e5ed7280cd1a3ac2ba29fd6650d8867c,206e64e8af2633a2ebe158a7fcb860db,8560,poa,SP,53cbf33b674d602f6746cb90a9d874fd,delivered,2017-05-15 17:42:38,2017-05-16 03:25:20,2017-05-16 16:02:08,...,176.0,1.0,1825.0,53.0,10.0,40.0,14940.0,ibitinga,SP,home_confort
119128,ffa6d90c36a9c7004692ca50761c69d6,874c93d867b18eb09a5e2f071ee89458,13140,paulinia,SP,2816b0ec050fb4a136c32a6bda007a91,delivered,2017-03-27 16:26:18,2017-03-27 16:35:19,2017-03-29 16:27:26,...,567.0,1.0,1150.0,30.0,10.0,30.0,37540.0,santa rita do sapucai,MG,furniture_decor
119131,27b9b32173455ef32167540451749d0b,277490f0d435b602fe4475d4b89e9181,6727,cotia,SP,326c29ec5b89834b17aea7d85302fd70,delivered,2017-05-24 11:54:31,2017-05-25 02:50:25,2017-05-26 16:12:26,...,245.0,1.0,1383.0,50.0,10.0,40.0,14940.0,ibitinga,SP,bed_bath_table
119134,14308d2303a3e2bdf4939b86c46d2679,e7f8760e2bbd2f1986bebd99596c088e,66033,belem,PA,ec3a75fb0ac595e461765d2d854b1d08,delivered,2017-03-15 21:04:08,2017-03-15 21:04:08,2017-03-20 08:34:12,...,621.0,1.0,600.0,16.0,6.0,11.0,4256.0,sao paulo,SP,stationery
119135,14308d2303a3e2bdf4939b86c46d2679,e7f8760e2bbd2f1986bebd99596c088e,66033,belem,PA,ec3a75fb0ac595e461765d2d854b1d08,delivered,2017-03-15 21:04:08,2017-03-15 21:04:08,2017-03-20 08:34:12,...,621.0,1.0,600.0,16.0,6.0,11.0,4256.0,sao paulo,SP,stationery

In [60]:
obs_150_df["is_customer"] = (
    (obs_150_df["order_purchase_timestamp"] >= start_date_150) & 
    (obs_150_df["order_purchase_timestamp"] < one_hundred_fifty_days_later)
).astype(int)

obs_150_df["is_customer"]

0         0
18        0
19        0
26        0
30        0
         ..
119122    0
119128    0
119131    0
119134    0
119135    0
Name: is_customer, Length: 18116, dtype: int64

In [61]:
future_active_ids_150 = obs_150_df[
    (obs_150_df["order_purchase_timestamp"] >= one_hundred_fifty_days_later) & 
    (obs_150_df["order_purchase_timestamp"] < end_date_hundred_fifty)
]["customer_unique_id"].unique()

future_active_ids_150

<StringArray>
['861eff4711a542e4b93843c6dd7febb0', '7f3a72e8f988c6e735ba118d54f47458',
 '4390ddbb6276a66ff1736a6710205dca', '2e6a42a9b5cbb0da62988694f18ee295',
 'e079b18794454de9d2be5c12b4392294', 'd85547cd859833520b311b4458a14c1c',
 '332cf4e83e16004ba7dca932ce82475b', 'cd076285a12f40041b32f5ad8c98699f',
 'fd2d5fdb84e65fa6b54b98b0e2df5645', 'd491a65a6ef3c04e145d37395996bad7',
 ...
 'a662a415dbbb5a154b3d38aa4fc86e57', 'db634985638ec4b6abf8734d7adde1ab',
 'a2325193ac2e95b805642e3100f80af3', 'e097d846931763789c3fd00b27f3c325',
 '5f2971f9805e3ccb030226e30c8e8390', 'c811311629fd3d76f5ca5eeb2abfa7e8',
 '206e64e8af2633a2ebe158a7fcb860db', '874c93d867b18eb09a5e2f071ee89458',
 '277490f0d435b602fe4475d4b89e9181', 'e7f8760e2bbd2f1986bebd99596c088e']
Length: 13497, dtype: str

In [62]:
obs_150_df["churn_150"] = (
    (obs_150_df["is_customer"] == 1) & 
    (~obs_150_df["customer_unique_id"].isin(future_active_ids_150))
).astype(int)

obs_150_df["churn_150"]

0         0
18        0
19        0
26        0
30        0
         ..
119122    0
119128    0
119131    0
119134    0
119135    0
Name: churn_150, Length: 18116, dtype: int64

In [63]:
dataset_150_df = obs_150_df.groupby(['customer_unique_id', 'order_purchase_timestamp', 'customer_city', 'customer_state', 'order_status']).agg({
    'price': 'sum',            # Total spent on the order (47.40 + 39.90)
    'freight_value': 'sum',    # Total shipping cost
    'payment_value': 'sum',    # Total amount charged to credit card
    'product_weight_g': 'sum', # Combined weight of the package


    # Categorical and indicator columns to pull forward
    'product_category_name_english': 'first',
    'is_customer': 'first',
    'churn_150': 'max',          # Keeps 1 if they churned, 0 otherwise
    'payment_sequential': 'max',
    'payment_type': 'first',
    'payment_installments': 'max'
}).reset_index()

dataset_150_df

,customer_unique_id,order_purchase_timestamp,customer_city,customer_state,order_status,price,freight_value,payment_value,product_weight_g,product_category_name_english,is_customer,churn_150,payment_sequential,payment_type,payment_installments
0,0000f46a3911fa3c0805444483337064,2017-03-10 21:05:03,sao jose,SC,delivered,69.00,17.22,86.22,1500.0,stationery,0,0,1.0,credit_card,8.0
1,0005e1862207bf6ccc02e4228effd9a0,2017-03-04 23:32:12,teresopolis,RJ,delivered,135.00,15.12,150.12,2250.0,fashion_bags_accessories,0,0,1.0,credit_card,3.0
2,00115fc7123b5310cf6d3a3aa932699e,2017-01-21 21:58:35,brasilia,DF,delivered,59.99,16.12,76.11,525.0,sports_leisure,1,1,1.0,credit_card,1.0
3,0011805441c0d1b68b48002f1d005526,2017-04-24 13:36:48,goianesia do para,PA,delivered,269.00,28.14,297.14,200.0,computers_accessories,0,0,1.0,credit_card,10.0
4,0011857aff0e5871ce5eb429f21cdaf5,2017-06-28 11:08:38,santo andre,SP,delivered,174.33,18.50,192.83,483.0,luggage_accessories,0,0,1.0,credit_card,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14962,ffedff0547d809c90c05c2691c51f9b7,2017-03-30 14:50:26,ribeirao preto,SP,delivered,17.90,14.52,32.42,225.0,housewares,0,0,1.0,credit_card,3.0
14963,ffef0ffa736c7b3d9af741611089729b,2017-05-29 22:07:05,nova venecia,ES,delivered,109.90,29.17,139.07,1136.0,sports_leisure,0,0,1.0,credit_card,1.0
14964,fffcf5a5ff07b0908bd4e2dbc735a684,2017-06-08 21:00:36,sanharo,PE,delivered,1570.00,497.42,4134.84,60000.0,health_beauty,0,0,1.0,credit_card,10.0
14965,ffff371b4d645b6ecea244b27531430a,2017-02-07 15:49:16,sinop,MT,delivered,89.90,22.56,112.46,600.0,auto,0,0,1.0,credit_card,1.0
14966,ffffd2657e2aad2907e67c3e9daecbeb,2017-05-02 20:18:45,campo largo,PR,delivered,56.99,14.57,71.56,400.0,perfumery,0,0,1.0,credit_card,4.0

In [64]:
dataset_150_df.to_csv(r"C:\Users\Hallen\Documents\mis_cosas\silvana\master\tfm-uned-churn\Data\churn_dataset_150_days1.csv", index=False)

-----

### **110 days term 2**

In [68]:
start_date_150_t2 = one_hundred_fifty_days_later

start_date_150_t2

Timestamp('2017-02-01 21:15:19')

In [69]:
one_hundred_fifty_days_later_t2 = start_date_150_t2 + pd.Timedelta(days= CHURN_DAYS)

one_hundred_fifty_days_later_t2

Timestamp('2017-07-01 21:15:19')

In [70]:
end_date_hundred_fifty_t2 = one_hundred_fifty_days_later_t2 + pd.Timedelta(days= CHURN_DAYS)

end_date_hundred_fifty_t2

Timestamp('2017-11-28 21:15:19')

In [71]:
obs_150_df_t2 = olist_df[(olist_df["order_purchase_timestamp"]>= start_date_150_t2) & (olist_df["order_purchase_timestamp"] < end_date_hundred_fifty_t2)]

obs_150_df_t2

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,...,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,seller_zip_code_prefix,seller_city,seller_state,product_category_name_english
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP,00e7ee1b050b8499577073aeb2a297a1,delivered,2017-05-16 15:05:35,2017-05-16 15:22:12,2017-05-23 10:47:57,...,1141.0,1.0,8683.0,54.0,64.0,31.0,8577.0,itaquaquecetuba,SP,office_furniture
5,879864dab9bc3047522c92c82e1212b8,4c93744516667ad3b8f1fb645a3116a4,89254,jaragua do sul,SC,5741ea1f91b5fbab2bd2dc653a5b5099,delivered,2017-09-14 18:14:31,2017-09-14 18:25:11,2017-09-18 21:27:40,...,282.0,2.0,4450.0,60.0,15.0,15.0,5141.0,pirituba,SP,sports_leisure
7,5e274e7a0c3809e14aba7ad5aae0d407,57b2a98a409812fe9618067b6b8ebe4f,35182,timoteo,MG,1093c8304c7a003280dd34598194913d,delivered,2017-11-16 19:29:02,2017-11-16 19:55:41,2017-11-22 16:46:33,...,NaN,NaN,250.0,15.0,8.0,20.0,4142.0,sao paulo,SP,NaN
10,9fb35e4ed6f0a14a4977cd9aea4042bb,2a7745e1ed516b289ed9b29c7d0539a5,39400,montes claros,MG,8428e578bb1cf839ae26a6b7615502b9,delivered,2017-11-27 17:23:20,2017-11-27 18:01:20,2017-11-28 23:04:41,...,1117.0,8.0,300.0,31.0,17.0,27.0,13405.0,piracicaba,SP,auto
12,b2d1536598b73a9abd18e0d75d92f0a3,918dc87cd72cd9f6ed4bd442ed785235,18682,lencois paulista,SP,83d8f70418eefd96f37b483dff430305,delivered,2017-09-09 09:54:57,2017-09-09 10:10:17,2017-09-12 12:42:43,...,624.0,5.0,2000.0,20.0,10.0,20.0,37590.0,jacutinga,MG,air_conditioning
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119130,1ed0c832c2dd99570a59260e71768bdf,82d46759af0369aad49084bacf85a6c3,37610,bom repouso,MG,51c6d2f460589fa7b65f2da51e860206,delivered,2017-11-14 12:04:09,2017-11-14 12:15:25,2017-11-27 20:44:47,...,63.0,1.0,6185.0,63.0,11.0,20.0,12914.0,braganca paulista,SP,electronics
119131,27b9b32173455ef32167540451749d0b,277490f0d435b602fe4475d4b89e9181,6727,cotia,SP,326c29ec5b89834b17aea7d85302fd70,delivered,2017-05-24 11:54:31,2017-05-25 02:50:25,2017-05-26 16:12:26,...,245.0,1.0,1383.0,50.0,10.0,40.0,14940.0,ibitinga,SP,bed_bath_table
119134,14308d2303a3e2bdf4939b86c46d2679,e7f8760e2bbd2f1986bebd99596c088e,66033,belem,PA,ec3a75fb0ac595e461765d2d854b1d08,delivered,2017-03-15 21:04:08,2017-03-15 21:04:08,2017-03-20 08:34:12,...,621.0,1.0,600.0,16.0,6.0,11.0,4256.0,sao paulo,SP,stationery
119135,14308d2303a3e2bdf4939b86c46d2679,e7f8760e2bbd2f1986bebd99596c088e,66033,belem,PA,ec3a75fb0ac595e461765d2d854b1d08,delivered,2017-03-15 21:04:08,2017-03-15 21:04:08,2017-03-20 08:34:12,...,621.0,1.0,600.0,16.0,6.0,11.0,4256.0,sao paulo,SP,stationery
119141,56b18e2166679b8a959d72dd06da27f9,73c2643a0a458b49f58cea58833b192e,92120,canoas,RS,e31ec91cea1ecf97797787471f98a8c2,delivered,2017-11-03 21:08:33,2017-11-03 21:31:20,2017-11-06 18:24:41,...,452.0,1.0,710.0,19.0,13.0,14.0,14840.0,guariba,SP,watches_gifts

In [72]:
obs_150_df_t2["is_customer"] = (
    (obs_150_df_t2["order_purchase_timestamp"] >= start_date_150_t2) & 
    (obs_150_df_t2["order_purchase_timestamp"] < one_hundred_fifty_days_later_t2)
).astype(int)

obs_150_df_t2["is_customer"]

0         1
5         0
7         0
10        0
12        0
         ..
119130    0
119131    1
119134    1
119135    1
119141    0
Name: is_customer, Length: 46013, dtype: int64

In [73]:
future_active_ids_150_t2 = obs_150_df_t2[
    (obs_150_df_t2["order_purchase_timestamp"] >= one_hundred_fifty_days_later_t2) & 
    (obs_150_df_t2["order_purchase_timestamp"] < end_date_hundred_fifty_t2)
]["customer_unique_id"].unique()

future_active_ids_150_t2

<StringArray>
['4c93744516667ad3b8f1fb645a3116a4', '57b2a98a409812fe9618067b6b8ebe4f',
 '2a7745e1ed516b289ed9b29c7d0539a5', '918dc87cd72cd9f6ed4bd442ed785235',
 '3e6fd6b2f0d499456a6a6820a40f2d79', 'e607ede0e63436308660236f5a52da5e',
 'a96d5cfa0d3181817e2b946f921ea021', '4d221875624017bc47b4d1ce7314a5b7',
 '424aca6872c5bab80780a8dec03b7516', 'bf4862777db128507e9efcc789215e9b',
 ...
 '9ef4905006f939a993f4794df18564c7', 'a5ba329297100ea689fa263768b35b8b',
 '81720bfb69887fe95390723af9748e9f', 'c6f8e1db66045b7e49203b47b5ce816f',
 '10674cc49bd68773d186d496d8ed071d', '065b9e6198f11dbdf7fc1250f9e08afc',
 'aaf22868003377e859049dcf5f0b3fdf', '4452b8ef472646c4cc042cb31a291f3b',
 '82d46759af0369aad49084bacf85a6c3', '73c2643a0a458b49f58cea58833b192e']
Length: 23488, dtype: str

In [74]:
obs_150_df_t2["churn_150"] = (
    (obs_150_df_t2["is_customer"] == 1) & 
    (~obs_150_df_t2["customer_unique_id"].isin(future_active_ids_150_t2))
).astype(int)

obs_150_df_t2["churn_150"]

0         1
5         0
7         0
10        0
12        0
         ..
119130    0
119131    1
119134    1
119135    1
119141    0
Name: churn_150, Length: 46013, dtype: int64

In [75]:
dataset_150_df_t2 = obs_150_df_t2.groupby(['customer_unique_id', 'order_purchase_timestamp', 'customer_city', 'customer_state', 'order_status']).agg({
    'price': 'sum',            # Total spent on the order (47.40 + 39.90)
    'freight_value': 'sum',    # Total shipping cost
    'payment_value': 'sum',    # Total amount charged to credit card
    'product_weight_g': 'sum', # Combined weight of the package


    # Categorical and indicator columns to pull forward
    'product_category_name_english': 'first',
    'is_customer': 'first',
    'churn_150': 'max',          # Keeps 1 if they churned, 0 otherwise
    'payment_sequential': 'max',
    'payment_type': 'first',
    'payment_installments': 'max'
}).reset_index()

dataset_150_df_t2

,customer_unique_id,order_purchase_timestamp,customer_city,customer_state,order_status,price,freight_value,payment_value,product_weight_g,product_category_name_english,is_customer,churn_150,payment_sequential,payment_type,payment_installments
0,0000f46a3911fa3c0805444483337064,2017-03-10 21:05:03,sao jose,SC,delivered,69.00,17.22,86.22,1500.0,stationery,1,1,1.0,credit_card,8.0
1,0000f6ccb0745a6a4b88665a16c9f078,2017-10-12 20:29:41,belem,PA,delivered,25.99,17.63,43.62,150.0,telephony,0,0,1.0,credit_card,4.0
2,0004aac84e0df4da2b147fca70cf8255,2017-11-14 19:45:42,sorocaba,SP,delivered,180.00,16.89,196.89,6050.0,telephony,0,0,1.0,credit_card,6.0
3,0005e1862207bf6ccc02e4228effd9a0,2017-03-04 23:32:12,teresopolis,RJ,delivered,135.00,15.12,150.12,2250.0,fashion_bags_accessories,1,1,1.0,credit_card,3.0
4,0006fdc98a402fceb4eb0ee528f6a8d4,2017-07-18 09:23:10,mimoso do sul,ES,delivered,13.90,15.10,29.00,200.0,bed_bath_table,0,0,1.0,credit_card,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37790,fff699c184bcc967d62fa2c6171765f7,2017-09-01 17:06:54,santos,SP,delivered,39.90,15.10,55.00,200.0,consoles_games,0,0,1.0,boleto,1.0
37791,fffa431dd3fcdefea4b1777d114144f2,2017-10-30 20:39:50,bom jardim,RJ,delivered,64.99,16.21,81.20,3585.0,cool_stuff,0,0,1.0,boleto,1.0
37792,fffcf5a5ff07b0908bd4e2dbc735a684,2017-06-08 21:00:36,sanharo,PE,delivered,1570.00,497.42,4134.84,60000.0,health_beauty,1,1,1.0,credit_card,10.0
37793,ffff371b4d645b6ecea244b27531430a,2017-02-07 15:49:16,sinop,MT,delivered,89.90,22.56,112.46,600.0,auto,1,1,1.0,credit_card,1.0
37794,ffffd2657e2aad2907e67c3e9daecbeb,2017-05-02 20:18:45,campo largo,PR,delivered,56.99,14.57,71.56,400.0,perfumery,1,1,1.0,credit_card,4.0

In [76]:
dataset_150_df_t2.to_csv(r"C:\Users\Hallen\Documents\mis_cosas\silvana\master\tfm-uned-churn\Data\churn_dataset_150_days2.csv", index=False)

--------
--------

Calculating Max the test dates range

In [82]:
max_date = olist_df["order_purchase_timestamp"].max()

max_date

Timestamp('2018-10-17 17:30:18')

In [83]:
limit_test = max_date - (pd.Timedelta(days= 110)*2)

test_period = limit_test - pd.Timedelta(days= 10)

test_period

Timestamp('2018-03-01 17:30:18')

------
------

# Test data set by days

## 90 days

In [84]:
CHURN_DAYS = 90

In [85]:
start_date_90T = test_period

start_date_90T

Timestamp('2018-03-01 17:30:18')

In [86]:
ninety_days_laterT = start_date_90T + pd.Timedelta(days= CHURN_DAYS)

ninety_days_laterT

Timestamp('2018-05-30 17:30:18')

In [87]:
end_dateT = ninety_days_laterT + pd.Timedelta(days= CHURN_DAYS)

end_dateT

Timestamp('2018-08-28 17:30:18')

In [88]:
obs_90_test_df = olist_df[(olist_df["order_purchase_timestamp"]>= start_date_90T) & (olist_df["order_purchase_timestamp"] < end_dateT)]

obs_90_test_df

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,...,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,seller_zip_code_prefix,seller_city,seller_state,product_category_name_english
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP,b2059ed67ce144a36e2aa97d2c9e9ad2,delivered,2018-05-19 16:07:45,2018-05-20 16:19:10,2018-06-11 14:31:00,...,955.0,1.0,8267.0,52.0,52.0,17.0,8577.0,itaquaquecetuba,SP,office_furniture
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP,951670f92359f4fe4a63112aa7306eba,delivered,2018-03-13 16:06:38,2018-03-13 17:29:19,2018-03-27 23:22:42,...,1066.0,1.0,12160.0,56.0,51.0,28.0,8577.0,itaquaquecetuba,SP,office_furniture
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP,6b7d50bd145f6fc7f33cebabd7e49d0f,delivered,2018-07-29 09:51:30,2018-07-29 10:10:09,2018-07-30 15:16:00,...,407.0,1.0,5200.0,45.0,15.0,35.0,14940.0,ibitinga,SP,home_confort
13,eabebad39a88bb6f5b52376faec28612,295c05e81917928d76245e842748184d,5704,sao paulo,SP,852d2f4d37773bcbc21c8e09a05a4ea5,delivered,2018-03-07 15:57:14,2018-03-07 16:15:30,2018-03-12 23:02:49,...,818.0,6.0,300.0,17.0,4.0,12.0,4160.0,sao paulo,SP,telephony
14,1f1c7bf1c9b041b292af6c1c4470b753,3151a81801c8386361b62277d7fa5ecf,95110,caxias do sul,RS,6c949e670b5d33dc8fb8ad25b6da4860,delivered,2018-04-01 18:59:31,2018-04-02 17:55:19,2018-04-03 19:33:13,...,400.0,2.0,433.0,19.0,14.0,15.0,80220.0,curitiba,PR,health_beauty
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119133,f255d679c7c86c24ef4861320d5b7675,d111b06b6f3a2add0d2241325f65b5ca,13500,rio claro,SP,ca978d2459ea2c5ef6d5fde02be26b9c,delivered,2018-03-06 09:16:56,2018-03-06 09:29:07,2018-03-06 18:51:58,...,407.0,3.0,400.0,16.0,3.0,21.0,4102.0,sao paulo,SP,computers_accessories
119136,f5a0b560f9e9427792a88bec97710212,b3e53d18a997f27a3ffd16da497eaf58,7790,cajamar,SP,97d6c1727b0d36b8d04035e35d86f40f,delivered,2018-05-18 21:42:33,2018-05-18 21:55:14,2018-06-04 16:03:00,...,514.0,2.0,4338.0,17.0,12.0,14.0,13101.0,campinas,SP,watches_gifts
119138,17ddf5dd5d51696bb3d7c6291687be6f,1a29b476fee25c95fbafc67c5ac95cf8,3937,sao paulo,SP,6760e20addcf0121e9d58f2f1ff14298,delivered,2018-04-07 15:48:17,2018-04-07 16:08:45,2018-04-11 02:08:36,...,489.0,2.0,611.0,22.0,22.0,23.0,17400.0,garca,SP,books_general_interest
119139,e7b71a9017aa05c9a7fd292d714858e8,d52a67c98be1cf6a5c84435bd38d095d,6764,taboao da serra,SP,9ec0c8947d973db4f4e8dcf1fbfa8f1b,delivered,2018-04-04 08:20:22,2018-04-04 08:35:12,2018-04-05 18:42:35,...,1193.0,1.0,1211.0,25.0,24.0,22.0,14802.0,araraquara,SP,sports_leisure
119140,5e28dfe12db7fb50a4b2f691faecea5e,e9f50caf99f032f0bf3c55141f019d99,60115,fortaleza,CE,fed4434add09a6f332ea398efd656a5c,delivered,2018-04-08 20:11:50,2018-04-08 20:30:03,2018-04-09 17:52:17,...,575.0,1.0,870.0,25.0,20.0,18.0,3304.0,sao paulo,SP,health_beauty

In [89]:
obs_90_test_df["is_customer"] = (
    (obs_90_test_df["order_purchase_timestamp"] >= start_date_90T) & 
    (obs_90_test_df["order_purchase_timestamp"] < ninety_days_laterT)
).astype(int)

obs_90_test_df["is_customer"]

2         1
3         1
4         0
13        1
14        1
         ..
119133    1
119136    1
119138    1
119139    1
119140    1
Name: is_customer, Length: 47186, dtype: int64

In [90]:
future_active_idsT = obs_90_test_df[
    (obs_90_test_df["order_purchase_timestamp"] >= ninety_days_laterT) & 
    (obs_90_test_df["order_purchase_timestamp"] < end_dateT)
]["customer_unique_id"].unique()

future_active_idsT

<StringArray>
['345ecd01c38d18a9036ed96c73b8d066', '5c2991dbd08bbf3cf410713c4de5a0b5',
 'b6e99561fe6f34a55b0b7da92f8ed775', '9c0096673baf55453a50073f12d1a37f',
 '07d190f123147d9e89d4b922543d7948', '86085586aaa8c5f47ed0b400da64c59d',
 'a302a693d5722d95984e6472150b9391', '95700615deef776ed32faa08f0be634e',
 'cf6d4152d758efc43910e0141ae5b912', '468d559ef2dcd2bea6d8db78959fb90f',
 ...
 '5854a3b6b55a5a77abc18d59772cc3bc', 'b80c1a7b76e8104245be223374df5fd9',
 '64aa56502b9ea3886fb356a259434201', '592134387e7f13de6a9e38eb7d412b3d',
 'e18e1db417f0bc97f9065c4aeae3f9d3', 'fb354969e06f2093c0083cbfbb91864e',
 'ff2331f4155cedbbbca83885595b1208', 'e5cf9da72b751849b7b217f7a943d0fa',
 '57c2cfb4a80b13ed19b5fb258d29c19d', 'ca186065de6e2d01cfc99763e6d62048']
Length: 18876, dtype: str

In [91]:
obs_90_test_df["churn_90"] = (
    (obs_90_test_df["is_customer"] == 1) & 
    (~obs_90_test_df["customer_unique_id"].isin(future_active_idsT))
).astype(int)

obs_90_test_df["churn_90"]

2         1
3         1
4         0
13        0
14        1
         ..
119133    1
119136    1
119138    1
119139    1
119140    1
Name: churn_90, Length: 47186, dtype: int64

In [92]:
obs_90_test_df = obs_90_test_df.groupby(['customer_unique_id', 'order_purchase_timestamp', 'customer_city', 'customer_state', 'order_status']).agg({
    'price': 'sum',            # Total spent on the order (47.40 + 39.90)
    'freight_value': 'sum',    # Total shipping cost
    'payment_value': 'sum',    # Total amount charged to credit card
    'product_weight_g': 'sum', # Combined weight of the package


    # Categorical and indicator columns to pull forward
    'product_category_name_english': 'first',
    'is_customer': 'first',
    'churn_90': 'max',          # Keeps 1 if they churned, 0 otherwise
    'payment_sequential': 'max',
    'payment_type': 'first',
    'payment_installments': 'max'
}).reset_index()

obs_90_test_df

,customer_unique_id,order_purchase_timestamp,customer_city,customer_state,order_status,price,freight_value,payment_value,product_weight_g,product_category_name_english,is_customer,churn_90,payment_sequential,payment_type,payment_installments
0,0000366f3b9a7992bf8c76cfdf3221e2,2018-05-10 10:56:27,cajamar,SP,delivered,129.90,12.00,141.90,1500.0,bed_bath_table,1,1,1.0,credit_card,8.0
1,0000b849f77a49e4a4ce2b2a4ca5be3f,2018-05-07 11:11:27,osasco,SP,delivered,18.90,8.29,27.19,375.0,health_beauty,1,1,1.0,credit_card,1.0
2,0004bd2a26a76fe21f786e4fbd80607f,2018-04-05 19:33:16,sao paulo,SP,delivered,154.00,12.98,166.98,3000.0,garden_tools,1,1,1.0,credit_card,8.0
3,00050ab1314c0e55a6ca13cf7181fecf,2018-04-20 12:57:23,campinas,SP,delivered,27.99,7.39,35.38,300.0,telephony,1,1,1.0,boleto,1.0
4,0005ef4cd20d2893f0d9fbd94d3c0d97,2018-03-12 15:22:12,sao luis,MA,delivered,104.90,24.86,129.76,1136.0,sports_leisure,1,1,1.0,credit_card,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39692,fff3e1d7bc75f11dc7670619b2e61840,2018-07-20 13:47:30,teresina,PI,delivered,54.85,27.66,82.51,100.0,computers_accessories,0,0,1.0,debit_card,1.0
39693,fff5eb4918b2bf4b2da476788d42051c,2018-07-02 16:39:59,campina grande,PB,delivered,1050.00,1794.96,17069.76,112200.0,signaling_and_security,0,0,1.0,boleto,1.0
39694,fff96bc586f78b1f070da28c4977e810,2018-08-15 10:26:57,itu,SP,delivered,45.00,18.42,63.42,200.0,housewares,0,0,1.0,credit_card,2.0
39695,fffcc512b7dfecaffd80f13614af1d16,2018-04-11 00:34:32,cabo frio,RJ,shipped,688.00,22.70,710.70,867.0,watches_gifts,1,1,1.0,credit_card,3.0
39696,ffff5962728ec6157033ef9805bacc48,2018-05-02 15:17:41,bom jesus do norte,ES,delivered,115.00,18.69,133.69,444.0,watches_gifts,1,1,1.0,credit_card,5.0

In [93]:
obs_90_test_df.to_csv(r"C:\Users\Hallen\Documents\mis_cosas\silvana\master\tfm-uned-churn\Data\churn_test_dataset_90.csv", index=False)

___

## 120 days

In [94]:
CHURN_DAYS = 120

In [95]:
one_hundred_twenty_days_laterT120 = start_date_90T + pd.Timedelta(days= CHURN_DAYS)

one_hundred_twenty_days_laterT120

Timestamp('2018-06-29 17:30:18')

In [96]:
end_dateT120 = one_hundred_twenty_days_laterT120 + pd.Timedelta(days= CHURN_DAYS)

end_dateT120

Timestamp('2018-10-27 17:30:18')

In [97]:
obs_120_test_df = olist_df[(olist_df["order_purchase_timestamp"]>= start_date_90T) & (olist_df["order_purchase_timestamp"] < end_dateT120)]

obs_120_test_df

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,...,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,seller_zip_code_prefix,seller_city,seller_state,product_category_name_english
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP,b2059ed67ce144a36e2aa97d2c9e9ad2,delivered,2018-05-19 16:07:45,2018-05-20 16:19:10,2018-06-11 14:31:00,...,955.0,1.0,8267.0,52.0,52.0,17.0,8577.0,itaquaquecetuba,SP,office_furniture
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP,951670f92359f4fe4a63112aa7306eba,delivered,2018-03-13 16:06:38,2018-03-13 17:29:19,2018-03-27 23:22:42,...,1066.0,1.0,12160.0,56.0,51.0,28.0,8577.0,itaquaquecetuba,SP,office_furniture
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP,6b7d50bd145f6fc7f33cebabd7e49d0f,delivered,2018-07-29 09:51:30,2018-07-29 10:10:09,2018-07-30 15:16:00,...,407.0,1.0,5200.0,45.0,15.0,35.0,14940.0,ibitinga,SP,home_confort
13,eabebad39a88bb6f5b52376faec28612,295c05e81917928d76245e842748184d,5704,sao paulo,SP,852d2f4d37773bcbc21c8e09a05a4ea5,delivered,2018-03-07 15:57:14,2018-03-07 16:15:30,2018-03-12 23:02:49,...,818.0,6.0,300.0,17.0,4.0,12.0,4160.0,sao paulo,SP,telephony
14,1f1c7bf1c9b041b292af6c1c4470b753,3151a81801c8386361b62277d7fa5ecf,95110,caxias do sul,RS,6c949e670b5d33dc8fb8ad25b6da4860,delivered,2018-04-01 18:59:31,2018-04-02 17:55:19,2018-04-03 19:33:13,...,400.0,2.0,433.0,19.0,14.0,15.0,80220.0,curitiba,PR,health_beauty
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119133,f255d679c7c86c24ef4861320d5b7675,d111b06b6f3a2add0d2241325f65b5ca,13500,rio claro,SP,ca978d2459ea2c5ef6d5fde02be26b9c,delivered,2018-03-06 09:16:56,2018-03-06 09:29:07,2018-03-06 18:51:58,...,407.0,3.0,400.0,16.0,3.0,21.0,4102.0,sao paulo,SP,computers_accessories
119136,f5a0b560f9e9427792a88bec97710212,b3e53d18a997f27a3ffd16da497eaf58,7790,cajamar,SP,97d6c1727b0d36b8d04035e35d86f40f,delivered,2018-05-18 21:42:33,2018-05-18 21:55:14,2018-06-04 16:03:00,...,514.0,2.0,4338.0,17.0,12.0,14.0,13101.0,campinas,SP,watches_gifts
119138,17ddf5dd5d51696bb3d7c6291687be6f,1a29b476fee25c95fbafc67c5ac95cf8,3937,sao paulo,SP,6760e20addcf0121e9d58f2f1ff14298,delivered,2018-04-07 15:48:17,2018-04-07 16:08:45,2018-04-11 02:08:36,...,489.0,2.0,611.0,22.0,22.0,23.0,17400.0,garca,SP,books_general_interest
119139,e7b71a9017aa05c9a7fd292d714858e8,d52a67c98be1cf6a5c84435bd38d095d,6764,taboao da serra,SP,9ec0c8947d973db4f4e8dcf1fbfa8f1b,delivered,2018-04-04 08:20:22,2018-04-04 08:35:12,2018-04-05 18:42:35,...,1193.0,1.0,1211.0,25.0,24.0,22.0,14802.0,araraquara,SP,sports_leisure
119140,5e28dfe12db7fb50a4b2f691faecea5e,e9f50caf99f032f0bf3c55141f019d99,60115,fortaleza,CE,fed4434add09a6f332ea398efd656a5c,delivered,2018-04-08 20:11:50,2018-04-08 20:30:03,2018-04-09 17:52:17,...,575.0,1.0,870.0,25.0,20.0,18.0,3304.0,sao paulo,SP,health_beauty

In [98]:
obs_120_test_df["is_customer"] = (
    (obs_120_test_df["order_purchase_timestamp"] >= start_date_90T) & 
    (obs_120_test_df["order_purchase_timestamp"] < one_hundred_twenty_days_laterT120)
).astype(int)

obs_120_test_df["is_customer"]

2         1
3         1
4         0
13        1
14        1
         ..
119133    1
119136    1
119138    1
119139    1
119140    1
Name: is_customer, Length: 47250, dtype: int64

In [99]:
future_active_idsT120 = obs_120_test_df[
    (obs_120_test_df["order_purchase_timestamp"] >= one_hundred_twenty_days_laterT120) & 
    (obs_120_test_df["order_purchase_timestamp"] < end_dateT120)
]["customer_unique_id"].unique()

future_active_idsT120

<StringArray>
['345ecd01c38d18a9036ed96c73b8d066', '5c2991dbd08bbf3cf410713c4de5a0b5',
 '9c0096673baf55453a50073f12d1a37f', '07d190f123147d9e89d4b922543d7948',
 '86085586aaa8c5f47ed0b400da64c59d', '95700615deef776ed32faa08f0be634e',
 'cf6d4152d758efc43910e0141ae5b912', '468d559ef2dcd2bea6d8db78959fb90f',
 '914b142462685e3161cf3a9f4152a028', '9dbb05f5577e862337b93feb8f358839',
 ...
 'ca16b60eec34dd3ad011825ff421add5', '2c07381b6d9aef0d1624dd670ec70bee',
 '54038fdafde7c49533a306f961281d9c', 'b80c1a7b76e8104245be223374df5fd9',
 '592134387e7f13de6a9e38eb7d412b3d', 'e18e1db417f0bc97f9065c4aeae3f9d3',
 'fb354969e06f2093c0083cbfbb91864e', 'ff2331f4155cedbbbca83885595b1208',
 'e5cf9da72b751849b7b217f7a943d0fa', '57c2cfb4a80b13ed19b5fb258d29c19d']
Length: 12822, dtype: str

In [100]:
obs_120_test_df["churn_120"] = (
    (obs_120_test_df["is_customer"] == 1) & 
    (~obs_120_test_df["customer_unique_id"].isin(future_active_idsT120))
).astype(int)

obs_120_test_df["churn_120"]

2         1
3         1
4         0
13        1
14        1
         ..
119133    1
119136    1
119138    1
119139    1
119140    1
Name: churn_120, Length: 47250, dtype: int64

In [101]:
obs_120_test_df = obs_120_test_df.groupby(['customer_unique_id', 'order_purchase_timestamp', 'customer_city', 'customer_state', 'order_status']).agg({
    'price': 'sum',            # Total spent on the order (47.40 + 39.90)
    'freight_value': 'sum',    # Total shipping cost
    'payment_value': 'sum',    # Total amount charged to credit card
    'product_weight_g': 'sum', # Combined weight of the package


    # Categorical and indicator columns to pull forward
    'product_category_name_english': 'first',
    'is_customer': 'first',
    'churn_120': 'max',          # Keeps 1 if they churned, 0 otherwise
    'payment_sequential': 'max',
    'payment_type': 'first',
    'payment_installments': 'max'
}).reset_index()

obs_120_test_df

,customer_unique_id,order_purchase_timestamp,customer_city,customer_state,order_status,price,freight_value,payment_value,product_weight_g,product_category_name_english,is_customer,churn_120,payment_sequential,payment_type,payment_installments
0,0000366f3b9a7992bf8c76cfdf3221e2,2018-05-10 10:56:27,cajamar,SP,delivered,129.90,12.00,141.90,1500.0,bed_bath_table,1,1,1.0,credit_card,8.0
1,0000b849f77a49e4a4ce2b2a4ca5be3f,2018-05-07 11:11:27,osasco,SP,delivered,18.90,8.29,27.19,375.0,health_beauty,1,1,1.0,credit_card,1.0
2,0004bd2a26a76fe21f786e4fbd80607f,2018-04-05 19:33:16,sao paulo,SP,delivered,154.00,12.98,166.98,3000.0,garden_tools,1,1,1.0,credit_card,8.0
3,00050ab1314c0e55a6ca13cf7181fecf,2018-04-20 12:57:23,campinas,SP,delivered,27.99,7.39,35.38,300.0,telephony,1,1,1.0,boleto,1.0
4,0005ef4cd20d2893f0d9fbd94d3c0d97,2018-03-12 15:22:12,sao luis,MA,delivered,104.90,24.86,129.76,1136.0,sports_leisure,1,1,1.0,credit_card,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39746,fff3e1d7bc75f11dc7670619b2e61840,2018-07-20 13:47:30,teresina,PI,delivered,54.85,27.66,82.51,100.0,computers_accessories,0,0,1.0,debit_card,1.0
39747,fff5eb4918b2bf4b2da476788d42051c,2018-07-02 16:39:59,campina grande,PB,delivered,1050.00,1794.96,17069.76,112200.0,signaling_and_security,0,0,1.0,boleto,1.0
39748,fff96bc586f78b1f070da28c4977e810,2018-08-15 10:26:57,itu,SP,delivered,45.00,18.42,63.42,200.0,housewares,0,0,1.0,credit_card,2.0
39749,fffcc512b7dfecaffd80f13614af1d16,2018-04-11 00:34:32,cabo frio,RJ,shipped,688.00,22.70,710.70,867.0,watches_gifts,1,1,1.0,credit_card,3.0
39750,ffff5962728ec6157033ef9805bacc48,2018-05-02 15:17:41,bom jesus do norte,ES,delivered,115.00,18.69,133.69,444.0,watches_gifts,1,1,1.0,credit_card,5.0

In [102]:
obs_120_test_df.to_csv(r"C:\Users\Hallen\Documents\mis_cosas\silvana\master\tfm-uned-churn\Data\churn_test_dataset_120.csv", index=False)

-------

## 150 days

In [103]:
CHURN_DAYS = 150

In [104]:
one_hundred_fifty_days_laterT = start_date_90T + pd.Timedelta(days= CHURN_DAYS)

one_hundred_fifty_days_laterT

Timestamp('2018-07-29 17:30:18')

In [105]:
end_dateT150 = one_hundred_fifty_days_laterT + pd.Timedelta(days= CHURN_DAYS)

end_dateT150

Timestamp('2018-12-26 17:30:18')

In [106]:
obs_150_test_df = olist_df[(olist_df["order_purchase_timestamp"]>= start_date_90T) & (olist_df["order_purchase_timestamp"] < end_dateT150)]

obs_150_test_df

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,...,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,seller_zip_code_prefix,seller_city,seller_state,product_category_name_english
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP,b2059ed67ce144a36e2aa97d2c9e9ad2,delivered,2018-05-19 16:07:45,2018-05-20 16:19:10,2018-06-11 14:31:00,...,955.0,1.0,8267.0,52.0,52.0,17.0,8577.0,itaquaquecetuba,SP,office_furniture
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP,951670f92359f4fe4a63112aa7306eba,delivered,2018-03-13 16:06:38,2018-03-13 17:29:19,2018-03-27 23:22:42,...,1066.0,1.0,12160.0,56.0,51.0,28.0,8577.0,itaquaquecetuba,SP,office_furniture
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP,6b7d50bd145f6fc7f33cebabd7e49d0f,delivered,2018-07-29 09:51:30,2018-07-29 10:10:09,2018-07-30 15:16:00,...,407.0,1.0,5200.0,45.0,15.0,35.0,14940.0,ibitinga,SP,home_confort
13,eabebad39a88bb6f5b52376faec28612,295c05e81917928d76245e842748184d,5704,sao paulo,SP,852d2f4d37773bcbc21c8e09a05a4ea5,delivered,2018-03-07 15:57:14,2018-03-07 16:15:30,2018-03-12 23:02:49,...,818.0,6.0,300.0,17.0,4.0,12.0,4160.0,sao paulo,SP,telephony
14,1f1c7bf1c9b041b292af6c1c4470b753,3151a81801c8386361b62277d7fa5ecf,95110,caxias do sul,RS,6c949e670b5d33dc8fb8ad25b6da4860,delivered,2018-04-01 18:59:31,2018-04-02 17:55:19,2018-04-03 19:33:13,...,400.0,2.0,433.0,19.0,14.0,15.0,80220.0,curitiba,PR,health_beauty
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119133,f255d679c7c86c24ef4861320d5b7675,d111b06b6f3a2add0d2241325f65b5ca,13500,rio claro,SP,ca978d2459ea2c5ef6d5fde02be26b9c,delivered,2018-03-06 09:16:56,2018-03-06 09:29:07,2018-03-06 18:51:58,...,407.0,3.0,400.0,16.0,3.0,21.0,4102.0,sao paulo,SP,computers_accessories
119136,f5a0b560f9e9427792a88bec97710212,b3e53d18a997f27a3ffd16da497eaf58,7790,cajamar,SP,97d6c1727b0d36b8d04035e35d86f40f,delivered,2018-05-18 21:42:33,2018-05-18 21:55:14,2018-06-04 16:03:00,...,514.0,2.0,4338.0,17.0,12.0,14.0,13101.0,campinas,SP,watches_gifts
119138,17ddf5dd5d51696bb3d7c6291687be6f,1a29b476fee25c95fbafc67c5ac95cf8,3937,sao paulo,SP,6760e20addcf0121e9d58f2f1ff14298,delivered,2018-04-07 15:48:17,2018-04-07 16:08:45,2018-04-11 02:08:36,...,489.0,2.0,611.0,22.0,22.0,23.0,17400.0,garca,SP,books_general_interest
119139,e7b71a9017aa05c9a7fd292d714858e8,d52a67c98be1cf6a5c84435bd38d095d,6764,taboao da serra,SP,9ec0c8947d973db4f4e8dcf1fbfa8f1b,delivered,2018-04-04 08:20:22,2018-04-04 08:35:12,2018-04-05 18:42:35,...,1193.0,1.0,1211.0,25.0,24.0,22.0,14802.0,araraquara,SP,sports_leisure
119140,5e28dfe12db7fb50a4b2f691faecea5e,e9f50caf99f032f0bf3c55141f019d99,60115,fortaleza,CE,fed4434add09a6f332ea398efd656a5c,delivered,2018-04-08 20:11:50,2018-04-08 20:30:03,2018-04-09 17:52:17,...,575.0,1.0,870.0,25.0,20.0,18.0,3304.0,sao paulo,SP,health_beauty

In [107]:
obs_150_test_df["is_customer"] = (
    (obs_150_test_df["order_purchase_timestamp"] >= start_date_90T) & 
    (obs_150_test_df["order_purchase_timestamp"] < one_hundred_fifty_days_laterT)
).astype(int)

obs_150_test_df["is_customer"]

2         1
3         1
4         1
13        1
14        1
         ..
119133    1
119136    1
119138    1
119139    1
119140    1
Name: is_customer, Length: 47250, dtype: int64

In [108]:
future_active_idsT150 = obs_150_test_df[
    (obs_150_test_df["order_purchase_timestamp"] >= one_hundred_fifty_days_laterT) & 
    (obs_150_test_df["order_purchase_timestamp"] < end_dateT150)
]["customer_unique_id"].unique()

future_active_idsT150

<StringArray>
['5c2991dbd08bbf3cf410713c4de5a0b5', '95700615deef776ed32faa08f0be634e',
 'cf6d4152d758efc43910e0141ae5b912', '468d559ef2dcd2bea6d8db78959fb90f',
 '914b142462685e3161cf3a9f4152a028', '9dbb05f5577e862337b93feb8f358839',
 '87edab6661956d4d2f05e205251cf1a4', '7aeb8dc11cd50c32f37fea0435c4e9b1',
 'be1e99a0c57d7c3c699cfc4db26c8edf', '337691bc9242e1d53d521ed78a12ab8d',
 ...
 'f25d8575129b5291eaec45ee1fe4a60f', '7a372481bc2f6b080c0c860d6836b39b',
 '8c8268a2915979efa64b481617356861', 'e84ac1e802114860d63efeff52694d38',
 '54a2d9cbeb08a11268085529cfe2524f', '5e11d75692add978f3a35d2ce9dee416',
 'cad23192ddc7d98303b035f2a0151673', '54038fdafde7c49533a306f961281d9c',
 'b80c1a7b76e8104245be223374df5fd9', '592134387e7f13de6a9e38eb7d412b3d']
Length: 7153, dtype: str

In [109]:
obs_150_test_df["churn_150"] = (
    (obs_150_test_df["is_customer"] == 1) & 
    (~obs_150_test_df["customer_unique_id"].isin(future_active_idsT150))
).astype(int)

obs_150_test_df["churn_150"]

2         1
3         1
4         1
13        1
14        1
         ..
119133    1
119136    1
119138    1
119139    1
119140    1
Name: churn_150, Length: 47250, dtype: int64

In [110]:
obs_150_test_df = obs_150_test_df.groupby(['customer_unique_id', 'order_purchase_timestamp', 'customer_city', 'customer_state', 'order_status']).agg({
    'price': 'sum',            # Total spent on the order (47.40 + 39.90)
    'freight_value': 'sum',    # Total shipping cost
    'payment_value': 'sum',    # Total amount charged to credit card
    'product_weight_g': 'sum', # Combined weight of the package


    # Categorical and indicator columns to pull forward
    'product_category_name_english': 'first',
    'is_customer': 'first',
    'churn_150': 'max',          # Keeps 1 if they churned, 0 otherwise
    'payment_sequential': 'max',
    'payment_type': 'first',
    'payment_installments': 'max'
}).reset_index()

obs_150_test_df

,customer_unique_id,order_purchase_timestamp,customer_city,customer_state,order_status,price,freight_value,payment_value,product_weight_g,product_category_name_english,is_customer,churn_150,payment_sequential,payment_type,payment_installments
0,0000366f3b9a7992bf8c76cfdf3221e2,2018-05-10 10:56:27,cajamar,SP,delivered,129.90,12.00,141.90,1500.0,bed_bath_table,1,1,1.0,credit_card,8.0
1,0000b849f77a49e4a4ce2b2a4ca5be3f,2018-05-07 11:11:27,osasco,SP,delivered,18.90,8.29,27.19,375.0,health_beauty,1,1,1.0,credit_card,1.0
2,0004bd2a26a76fe21f786e4fbd80607f,2018-04-05 19:33:16,sao paulo,SP,delivered,154.00,12.98,166.98,3000.0,garden_tools,1,1,1.0,credit_card,8.0
3,00050ab1314c0e55a6ca13cf7181fecf,2018-04-20 12:57:23,campinas,SP,delivered,27.99,7.39,35.38,300.0,telephony,1,1,1.0,boleto,1.0
4,0005ef4cd20d2893f0d9fbd94d3c0d97,2018-03-12 15:22:12,sao luis,MA,delivered,104.90,24.86,129.76,1136.0,sports_leisure,1,1,1.0,credit_card,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39746,fff3e1d7bc75f11dc7670619b2e61840,2018-07-20 13:47:30,teresina,PI,delivered,54.85,27.66,82.51,100.0,computers_accessories,1,1,1.0,debit_card,1.0
39747,fff5eb4918b2bf4b2da476788d42051c,2018-07-02 16:39:59,campina grande,PB,delivered,1050.00,1794.96,17069.76,112200.0,signaling_and_security,1,1,1.0,boleto,1.0
39748,fff96bc586f78b1f070da28c4977e810,2018-08-15 10:26:57,itu,SP,delivered,45.00,18.42,63.42,200.0,housewares,0,0,1.0,credit_card,2.0
39749,fffcc512b7dfecaffd80f13614af1d16,2018-04-11 00:34:32,cabo frio,RJ,shipped,688.00,22.70,710.70,867.0,watches_gifts,1,1,1.0,credit_card,3.0
39750,ffff5962728ec6157033ef9805bacc48,2018-05-02 15:17:41,bom jesus do norte,ES,delivered,115.00,18.69,133.69,444.0,watches_gifts,1,1,1.0,credit_card,5.0

In [111]:
obs_150_test_df.to_csv(r"C:\Users\Hallen\Documents\mis_cosas\silvana\master\tfm-uned-churn\Data\churn_test_dataset_150.csv", index=False)