In [16]:
import pandas as pd

import seaborn as sb
import matplotlib.pyplot as plt

In [17]:
DATA_PATH = "../Data/Training_dataset"

In [18]:
NINETY_DAYS_T1_PATH = "churn_dataset_90_days1.csv"
NINETY_DAYS_T2_PATH = "churn_dataset_90_days2.csv"
NINETY_DAYS_T3_PATH = "churn_dataset_90_days3.csv"
ONE_HUNDRED_T1_PATH = "churn_dataset_100_days1.csv"
ONE_HUNDRED_T2_PATH = "churn_dataset_100_days2.csv"
ONE_HUNDRED_ONE_T1_PATH = "churn_dataset_110_days1.csv"
ONE_HUNDRED_ONE_T2_PATH = "churn_dataset_110_days2.csv"

In [19]:
churn_dataset_90_days1 = pd.read_csv(DATA_PATH + "/" + NINETY_DAYS_T1_PATH) 
churn_dataset_90_days2 = pd.read_csv(DATA_PATH + "/" + NINETY_DAYS_T2_PATH)
churn_dataset_90_days3 = pd.read_csv(DATA_PATH + "/" + NINETY_DAYS_T3_PATH)
churn_dataset_100_days1 = pd.read_csv(DATA_PATH + "/" + ONE_HUNDRED_T1_PATH)
churn_dataset_100_days2 = pd.read_csv(DATA_PATH + "/" + ONE_HUNDRED_T2_PATH)
churn_dataset_110_days1 = pd.read_csv(DATA_PATH + "/" + ONE_HUNDRED_ONE_T1_PATH)
churn_dataset_110_days2 = pd.read_csv(DATA_PATH + "/" + ONE_HUNDRED_ONE_T2_PATH)

-----
-----

# Vertical union of columns

## 90 days

In [20]:
train_90_df = pd.concat([churn_dataset_90_days1,churn_dataset_90_days2,churn_dataset_90_days3], axis= 0, ignore_index= True)

train_90_df

,customer_unique_id,order_purchase_timestamp,customer_city,customer_state,order_status,price,freight_value,payment_value,product_weight_g,product_category_name_english,is_customer,churn_90,payment_sequential,payment_type,payment_installments
0,00115fc7123b5310cf6d3a3aa932699e,2017-01-21 21:58:35,brasilia,DF,delivered,59.99,16.12,76.11,525.0,sports_leisure,0,0,1.0,credit_card,1.0
1,002b4cd83fabaffaa475f78ea5ef3e08,2017-02-01 13:53:16,sao sebastiao do paraiso,MG,delivered,49.90,14.52,64.42,150.0,fashion_bags_accessories,0,0,1.0,credit_card,1.0
2,0032c76b20340da25249092a268ce66c,2016-10-06 11:32:00,charqueada,SP,delivered,128.90,16.04,144.94,5470.0,toys,1,1,1.0,credit_card,1.0
3,0055b522bc89cbfbf376d8b59a628470,2017-03-03 15:48:57,fortaleza,CE,delivered,328.00,36.75,364.75,1500.0,small_appliances,0,0,1.0,boleto,1.0
4,0071f46a072a9ae25bbe4438b15efe9c,2017-02-01 00:04:17,aracatuba,SP,unavailable,0.00,0.00,174.54,0.0,NaN,0,0,1.0,credit_card,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58592,fff7219c86179ca6441b8f37823ba3d3,2017-12-27 18:57:38,cachoeiras de macacu,RJ,delivered,245.80,20.00,531.60,3500.0,bed_bath_table,0,0,1.0,debit_card,1.0
58593,fffa431dd3fcdefea4b1777d114144f2,2017-10-30 20:39:50,bom jardim,RJ,delivered,64.99,16.21,81.20,3585.0,cool_stuff,1,1,1.0,boleto,1.0
58594,fffb09418989a0dbff854a28163e47c6,2017-12-17 19:14:35,veranopolis,RS,delivered,58.00,15.16,73.16,213.0,watches_gifts,0,0,1.0,boleto,1.0
58595,fffbf87b7a1a6fa8b03f081c5f51a201,2017-12-27 22:36:41,fortaleza,CE,delivered,149.00,18.32,167.32,350.0,NaN,0,0,1.0,credit_card,2.0
58596,fffea47cd6d3cc0a88bd621562a9d061,2017-12-10 20:07:56,feira de santana,BA,delivered,64.89,19.69,84.58,1720.0,baby,0,0,1.0,credit_card,1.0

In [21]:
train_90_df.to_csv(r"C:\Users\Hallen\Documents\mis_cosas\silvana\master\tfm-uned-churn\Data\Train_test\train_90.csv", index=False)

## 100 days

In [22]:
train_100_df = pd.concat([churn_dataset_100_days1,churn_dataset_100_days2], axis= 0, ignore_index= True)

train_100_df

,customer_unique_id,order_purchase_timestamp,customer_city,customer_state,order_status,price,freight_value,payment_value,product_weight_g,product_category_name_english,is_customer,churn_100,payment_sequential,payment_type,payment_installments
0,0000f46a3911fa3c0805444483337064,2017-03-10 21:05:03,sao jose,SC,delivered,69.00,17.22,86.22,1500.0,stationery,0,0,1.0,credit_card,8.0
1,0005e1862207bf6ccc02e4228effd9a0,2017-03-04 23:32:12,teresopolis,RJ,delivered,135.00,15.12,150.12,2250.0,fashion_bags_accessories,0,0,1.0,credit_card,3.0
2,00115fc7123b5310cf6d3a3aa932699e,2017-01-21 21:58:35,brasilia,DF,delivered,59.99,16.12,76.11,525.0,sports_leisure,0,0,1.0,credit_card,1.0
3,001f3c4211216384d5fe59b041ce1461,2017-03-19 18:34:36,sao paulo,SP,delivered,24.88,10.96,35.84,250.0,housewares,0,0,1.0,credit_card,3.0
4,002b4cd83fabaffaa475f78ea5ef3e08,2017-02-01 13:53:16,sao sebastiao do paraiso,MG,delivered,49.90,14.52,64.42,150.0,fashion_bags_accessories,0,0,1.0,credit_card,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28765,fff1afc79f6b5db1e235a4a6c30ceda7,2017-08-30 23:38:43,erechim,RS,delivered,34.99,15.10,50.09,200.0,health_beauty,0,0,1.0,credit_card,4.0
28766,fff3a9369e4b7102fab406a334a678c3,2017-08-11 10:26:38,brasilia,DF,delivered,84.90,17.84,102.74,1450.0,luggage_accessories,0,0,1.0,credit_card,2.0
28767,fff699c184bcc967d62fa2c6171765f7,2017-09-01 17:06:54,santos,SP,delivered,39.90,15.10,55.00,200.0,consoles_games,0,0,1.0,boleto,1.0
28768,fffcf5a5ff07b0908bd4e2dbc735a684,2017-06-08 21:00:36,sanharo,PE,delivered,1570.00,497.42,4134.84,60000.0,health_beauty,1,1,1.0,credit_card,10.0
28769,ffffd2657e2aad2907e67c3e9daecbeb,2017-05-02 20:18:45,campo largo,PR,delivered,56.99,14.57,71.56,400.0,perfumery,1,1,1.0,credit_card,4.0

In [23]:
train_100_df.to_csv(r"C:\Users\Hallen\Documents\mis_cosas\silvana\master\tfm-uned-churn\Data\Train_test\train_100.csv", index=False)

## 110 days

In [24]:
train_110_df = pd.concat([churn_dataset_110_days1,churn_dataset_110_days2], axis= 0, ignore_index= True)

train_110_df

,customer_unique_id,order_purchase_timestamp,customer_city,customer_state,order_status,price,freight_value,payment_value,product_weight_g,product_category_name_english,is_customer,churn_110,payment_sequential,payment_type,payment_installments
0,0000f46a3911fa3c0805444483337064,2017-03-10 21:05:03,sao jose,SC,delivered,69.00,17.22,86.22,1500.0,stationery,0,0,1.0,credit_card,8.0
1,0005e1862207bf6ccc02e4228effd9a0,2017-03-04 23:32:12,teresopolis,RJ,delivered,135.00,15.12,150.12,2250.0,fashion_bags_accessories,0,0,1.0,credit_card,3.0
2,00115fc7123b5310cf6d3a3aa932699e,2017-01-21 21:58:35,brasilia,DF,delivered,59.99,16.12,76.11,525.0,sports_leisure,0,0,1.0,credit_card,1.0
3,001f3c4211216384d5fe59b041ce1461,2017-03-19 18:34:36,sao paulo,SP,delivered,24.88,10.96,35.84,250.0,housewares,0,0,1.0,credit_card,3.0
4,002043098f10ba39a4600b6c52fbfe3c,2017-03-26 16:45:59,aracaju,SE,delivered,176.99,60.82,237.81,10725.0,office_furniture,0,0,1.0,credit_card,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35082,fff3a9369e4b7102fab406a334a678c3,2017-08-11 10:26:38,brasilia,DF,delivered,84.90,17.84,102.74,1450.0,luggage_accessories,0,0,1.0,credit_card,2.0
35083,fff699c184bcc967d62fa2c6171765f7,2017-09-01 17:06:54,santos,SP,delivered,39.90,15.10,55.00,200.0,consoles_games,0,0,1.0,boleto,1.0
35084,fffa431dd3fcdefea4b1777d114144f2,2017-10-30 20:39:50,bom jardim,RJ,delivered,64.99,16.21,81.20,3585.0,cool_stuff,0,0,1.0,boleto,1.0
35085,fffcf5a5ff07b0908bd4e2dbc735a684,2017-06-08 21:00:36,sanharo,PE,delivered,1570.00,497.42,4134.84,60000.0,health_beauty,1,1,1.0,credit_card,10.0
35086,ffffd2657e2aad2907e67c3e9daecbeb,2017-05-02 20:18:45,campo largo,PR,delivered,56.99,14.57,71.56,400.0,perfumery,1,1,1.0,credit_card,4.0

In [25]:
train_110_df.to_csv(r"C:\Users\Hallen\Documents\mis_cosas\silvana\master\tfm-uned-churn\Data\Train_test\train_110.csv", index=False)