In [12]:
import pandas as pd

import seaborn as sb
import matplotlib.pyplot as plt

In [13]:
DATA_PATH = "../Data"

In [14]:
NINETY_DAYS_T1_PATH = "churn_dataset_90_1.csv"
NINETY_DAYS_T2_PATH = "churn_dataset_90_days2.csv"
ONE_HUNDRED_TWENTY_T1_PATH = "churn_dataset_120_1.csv"
ONE_HUNDRED_TWENTY_T2_PATH = "churn_dataset_120_2.csv"
ONE_HUNDRED_FIFTY_T1_PATH = "churn_dataset_150_1.csv"
ONE_HUNDRED_FIFTY_T2_PATH = "churn_dataset_150_2.csv"
NINETY_DAYS_TESTT1_PATH = "churn_test_dataset_90.csv"
NINETY_DAYS_TESTT2_PATH ="churn_test_dataset_90_2.csv"
ONE_HUNDRED_TWENTY_TESTT1_PATH = "churn_test_dataset_120.csv"
ONE_HUNDRED_TWENTY_TESTT2_PATH = "churn_test_dataset_120_2.csv"

In [15]:
churn_dataset_90_days1 = pd.read_csv(DATA_PATH + "/" + NINETY_DAYS_T1_PATH) 
churn_dataset_90_days2 = pd.read_csv(DATA_PATH + "/" + NINETY_DAYS_T2_PATH)
churn_dataset_120_days1 = pd.read_csv(DATA_PATH + "/" + ONE_HUNDRED_TWENTY_T1_PATH)
churn_dataset_120_days2 = pd.read_csv(DATA_PATH + "/" + ONE_HUNDRED_TWENTY_T2_PATH)
churn_dataset_150_days1 = pd.read_csv(DATA_PATH + "/" + ONE_HUNDRED_FIFTY_T1_PATH)
churn_dataset_150_days2 = pd.read_csv(DATA_PATH + "/" + ONE_HUNDRED_FIFTY_T2_PATH)
Churn_test_dataset_90_days1 = pd.read_csv(DATA_PATH + "/" + NINETY_DAYS_TESTT1_PATH)
Churn_test_dataset_90_days2 = pd.read_csv(DATA_PATH + "/" + NINETY_DAYS_TESTT2_PATH)
Churn_test_dataset_120_days1 = pd.read_csv(DATA_PATH + "/" + ONE_HUNDRED_TWENTY_TESTT1_PATH)
Churn_test_dataset_120_days2 = pd.read_csv(DATA_PATH + "/" + ONE_HUNDRED_TWENTY_TESTT2_PATH)

-----
-----

# Vertical union of columns

## 90 days

In [16]:
train_90_df = pd.concat([churn_dataset_90_days1,churn_dataset_90_days2], axis= 0, ignore_index= True)

train_90_df

,customer_unique_id,price,freight_to_price_ratio,payment_value,dates_diff,review_score,freight_to_weight_ratio,product_photos_qty,customer_city,customer_state,order_status,payment_sequential,payment_type,payment_installments,product_cat,churn_90
0,0032c76b20340da25249092a268ce66c,128.90,0.124438,144.94,-27.0,4.0,0.002932,1.0,charqueada,SP,delivered,1.0,credit_card,1.0,entertainment,0
1,01f156677184504063bd19739f924af1,739.98,0.060569,784.80,-46.0,5.0,0.002873,2.0,gravatal,SC,delivered,1.0,credit_card,10.0,household,0
2,0313291a6f4f16df04dcf819d88c38ef,95.00,0.187158,112.78,0.0,1.0,0.017780,1.0,sao sebastiao,SP,processing,1.0,boleto,1.0,household,0
3,0636d30c77f0f9cfad81f1c9b58c791f,949.99,0.023127,971.96,-44.0,4.0,0.004674,2.0,itaquaquecetuba,SP,delivered,1.0,credit_card,10.0,entertainment,0
4,0659f2d6cabae94afd4d009c6d0e07dc,390.00,0.177282,918.28,0.0,1.0,0.003582,1.0,cacequi,RS,canceled,1.0,credit_card,4.0,automotive,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8657,ffe3e199b9d0b7fb7d2d29a5b9498447,146.90,0.103472,162.10,0.0,1.0,0.043429,2.0,uberlandia,MG,delivered,1.0,boleto,1.0,construction,0
8658,ffe4c3aa14d4702fb11fe5b3c4dd755c,118.90,0.154752,137.30,-15.0,5.0,0.013143,4.0,sarzedo,MG,delivered,1.0,credit_card,1.0,beauty,0
8659,ffedff0547d809c90c05c2691c51f9b7,17.90,0.811173,32.42,-56.0,5.0,0.064533,1.0,ribeirao preto,SP,delivered,1.0,credit_card,3.0,household,0
8660,ffef0ffa736c7b3d9af741611089729b,109.90,0.265423,139.07,-22.0,5.0,0.025678,1.0,nova venecia,ES,delivered,1.0,credit_card,1.0,sports_leisure,0
8661,ffffd2657e2aad2907e67c3e9daecbeb,56.99,0.255659,71.56,-16.0,5.0,0.036425,2.0,campo largo,PR,delivered,1.0,credit_card,4.0,beauty,0

In [17]:
train_90_df.to_csv(r"C:\Users\Hallen\Documents\mis_cosas\silvana\master\tfm-uned-churn\Data\Train_test\train_90.csv", index=False)

## 120 days

In [18]:
train_120_df = pd.concat([churn_dataset_120_days1,churn_dataset_120_days2], axis= 0, ignore_index= True)

train_120_df

,customer_unique_id,price,freight_to_price_ratio,payment_value,dates_diff,review_score,freight_to_weight_ratio,product_photos_qty,customer_city,customer_state,order_status,payment_sequential,payment_type,payment_installments,product_cat,churn_120
0,0032c76b20340da25249092a268ce66c,128.90,0.124438,144.94,-27.0,4.0,0.002932,1.0,charqueada,SP,delivered,1.0,credit_card,1.0,entertainment,0
1,01f156677184504063bd19739f924af1,739.98,0.060569,784.80,-46.0,5.0,0.002873,2.0,gravatal,SC,delivered,1.0,credit_card,10.0,household,0
2,0313291a6f4f16df04dcf819d88c38ef,95.00,0.187158,112.78,0.0,1.0,0.017780,1.0,sao sebastiao,SP,processing,1.0,boleto,1.0,household,0
3,0636d30c77f0f9cfad81f1c9b58c791f,949.99,0.023127,971.96,-44.0,4.0,0.004674,2.0,itaquaquecetuba,SP,delivered,1.0,credit_card,10.0,entertainment,0
4,0659f2d6cabae94afd4d009c6d0e07dc,390.00,0.177282,918.28,0.0,1.0,0.003582,1.0,cacequi,RS,canceled,1.0,credit_card,4.0,automotive,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7795,ffe2dd1f3b0cbf0b5f35e818ec03c49b,89.99,0.230137,110.70,-9.0,4.0,0.011834,1.0,rio de janeiro,RJ,delivered,1.0,credit_card,2.0,household,0
7796,ffe3e199b9d0b7fb7d2d29a5b9498447,146.90,0.103472,162.10,0.0,1.0,0.043429,2.0,uberlandia,MG,delivered,1.0,boleto,1.0,construction,0
7797,ffebb6424578e7bb153322da9d65634f,629.00,0.058347,665.70,-5.0,1.0,0.005169,2.0,guarulhos,SP,delivered,1.0,credit_card,8.0,entertainment,0
7798,ffedff0547d809c90c05c2691c51f9b7,17.90,0.811173,32.42,-56.0,5.0,0.064533,1.0,ribeirao preto,SP,delivered,1.0,credit_card,3.0,household,0
7799,ffff371b4d645b6ecea244b27531430a,89.90,0.250945,112.46,-30.0,5.0,0.037600,5.0,sinop,MT,delivered,1.0,credit_card,1.0,automotive,0

In [19]:
train_120_df.to_csv(r"C:\Users\Hallen\Documents\mis_cosas\silvana\master\tfm-uned-churn\Data\Train_test\train_120.csv", index=False)

## 110 days

In [20]:
train_150_df = pd.concat([churn_dataset_150_days1,churn_dataset_150_days2], axis= 0, ignore_index= True)

train_150_df

,customer_unique_id,price,freight_to_price_ratio,payment_value,dates_diff,review_score,freight_to_weight_ratio,product_photos_qty,customer_city,customer_state,order_status,payment_sequential,payment_type,payment_installments,product_cat,churn_150
0,00115fc7123b5310cf6d3a3aa932699e,59.99,0.268711,76.11,-33.0,4.0,0.030705,6.0,brasilia,DF,delivered,1.0,credit_card,1.0,sports_leisure,0
1,0032c76b20340da25249092a268ce66c,128.90,0.124438,144.94,-27.0,4.0,0.002932,1.0,charqueada,SP,delivered,1.0,credit_card,1.0,entertainment,0
2,008f3d5f45a11059239a5c452cd00006,309.90,0.086028,336.56,-28.0,5.0,0.059376,1.0,sao pedro da agua branca,MA,delivered,1.0,boleto,1.0,beauty,0
3,012e12f54f6e73b1faba89a119dab849,87.74,0.205152,105.74,-40.0,4.0,0.006207,10.0,maurilandia,GO,delivered,1.0,credit_card,5.0,household,0
4,01838e7d69d87bd8ff2b6ff06789adfb,126.90,0.253822,159.11,-35.0,5.0,0.035789,2.0,belem,PA,delivered,1.0,credit_card,1.0,fashion,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14367,ffedff0547d809c90c05c2691c51f9b7,17.90,0.811173,32.42,-56.0,5.0,0.064533,1.0,ribeirao preto,SP,delivered,1.0,credit_card,3.0,household,0
14368,ffef0ffa736c7b3d9af741611089729b,109.90,0.265423,139.07,-22.0,5.0,0.025678,1.0,nova venecia,ES,delivered,1.0,credit_card,1.0,sports_leisure,0
14369,fffcf5a5ff07b0908bd4e2dbc735a684,1570.00,0.320939,4134.84,-27.0,5.0,0.008290,1.0,sanharo,PE,delivered,1.0,credit_card,10.0,beauty,0
14370,ffff371b4d645b6ecea244b27531430a,89.90,0.250945,112.46,-30.0,5.0,0.037600,5.0,sinop,MT,delivered,1.0,credit_card,1.0,automotive,0
14371,ffffd2657e2aad2907e67c3e9daecbeb,56.99,0.255659,71.56,-16.0,5.0,0.036425,2.0,campo largo,PR,delivered,1.0,credit_card,4.0,beauty,0

In [21]:
train_150_df.to_csv(r"C:\Users\Hallen\Documents\mis_cosas\silvana\master\tfm-uned-churn\Data\Train_test\train_150.csv", index=False)

# Test 90 days

In [22]:
test_90_df = pd.concat([Churn_test_dataset_90_days1,Churn_test_dataset_90_days2], axis= 0, ignore_index= True)

test_90_df

,customer_unique_id,price,freight_to_price_ratio,payment_value,dates_diff,review_score,freight_to_weight_ratio,product_photos_qty,customer_city,customer_state,order_status,payment_sequential,payment_type,payment_installments,product_cat,churn_90
0,00053a61a98854899e70ed204dd4bafe,382.00,0.097330,838.36,-10.0,1.0,0.016423,1.0,curitiba,PR,delivered,1.0,credit_card,3.0,sports_leisure,0
1,000c8bdb58a29e7115cfc257230fb21b,13.90,1.086331,29.00,-9.0,5.0,0.086286,2.0,belo horizonte,MG,delivered,1.0,credit_card,2.0,household,0
2,000d460961d6dbfa3ec6c9f5805769e1,28.90,0.269204,36.68,-13.0,5.0,0.051867,3.0,sao paulo,SP,delivered,1.0,credit_card,1.0,electronics,0
3,0014a5a58da615f7b01a4f5e194bf5ea,88.00,0.134318,99.82,-7.0,5.0,0.021491,2.0,sao paulo,SP,delivered,1.0,credit_card,3.0,beauty,0
4,00196fdb2bf9edfc35e88ebfbcf8d781,12.90,1.093023,27.00,1.0,3.0,0.080571,1.0,canoas,RS,delivered,1.0,credit_card,1.0,electronics,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39545,ffecceca389973ef16660d58696f281e,59.90,0.214691,72.76,-15.0,5.0,0.064300,1.0,ilha solteira,SP,delivered,1.0,boleto,1.0,fashion,0
39546,ffeddf8aa7cdecf403e77b2e9a99e2ea,330.00,0.237576,204.20,6.0,2.0,0.174222,3.0,santarem,PA,delivered,2.0,credit_card,5.0,office,0
39547,fff2ae16b99c6f3c785f0e052f2a9cfb,129.94,0.546098,200.90,-21.0,5.0,0.005117,1.0,rio de janeiro,RJ,delivered,1.0,credit_card,8.0,office,0
39548,fffcc512b7dfecaffd80f13614af1d16,688.00,0.032994,710.70,0.0,1.0,0.026182,2.0,cabo frio,RJ,shipped,1.0,credit_card,3.0,beauty,0
39549,ffff5962728ec6157033ef9805bacc48,115.00,0.162522,133.69,-14.0,5.0,0.042095,3.0,bom jesus do norte,ES,delivered,1.0,credit_card,5.0,beauty,0

In [23]:
test_90_df.to_csv(r"C:\Users\Hallen\Documents\mis_cosas\silvana\master\tfm-uned-churn\Data\Train_test\test_90.csv", index=False)

# Test 120 days

In [24]:
test_120_df = pd.concat([Churn_test_dataset_120_days1,Churn_test_dataset_120_days2], axis= 0, ignore_index= True)

test_120_df

,customer_unique_id,price,freight_to_price_ratio,payment_value,dates_diff,review_score,freight_to_weight_ratio,product_photos_qty,customer_city,customer_state,order_status,payment_sequential,payment_type,payment_installments,product_cat,churn_120
0,00053a61a98854899e70ed204dd4bafe,382.00,0.097330,838.36,-10.0,1.0,0.016423,1.0,curitiba,PR,delivered,1.0,credit_card,3.0,sports_leisure,0
1,0005ef4cd20d2893f0d9fbd94d3c0d97,104.90,0.236988,129.76,31.0,1.0,0.021884,1.0,sao luis,MA,delivered,1.0,credit_card,4.0,sports_leisure,0
2,00090324bbad0e9342388303bb71ba0a,49.95,0.274474,63.66,-8.0,5.0,0.030467,2.0,campinas,SP,delivered,1.0,credit_card,3.0,household,0
3,000c8bdb58a29e7115cfc257230fb21b,13.90,1.086331,29.00,-9.0,5.0,0.086286,2.0,belo horizonte,MG,delivered,1.0,credit_card,2.0,household,0
4,000d460961d6dbfa3ec6c9f5805769e1,28.90,0.269204,36.68,-13.0,5.0,0.051867,3.0,sao paulo,SP,delivered,1.0,credit_card,1.0,electronics,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39952,ffe76cb2f4bb39384c432d65ece67441,49.00,0.348163,66.06,-15.0,5.0,0.068240,3.0,camacari,BA,delivered,1.0,boleto,1.0,beauty,0
39953,ffec10ad4229ba46818560e1c8b40a68,120.00,0.131000,135.72,-10.0,5.0,0.104800,1.0,viana,ES,delivered,1.0,credit_card,3.0,sports_leisure,0
39954,ffecceca389973ef16660d58696f281e,59.90,0.214691,72.76,-15.0,5.0,0.064300,1.0,ilha solteira,SP,delivered,1.0,boleto,1.0,fashion,0
39955,fff2ae16b99c6f3c785f0e052f2a9cfb,129.94,0.546098,200.90,-21.0,5.0,0.005117,1.0,rio de janeiro,RJ,delivered,1.0,credit_card,8.0,office,0
39956,fffcc512b7dfecaffd80f13614af1d16,688.00,0.032994,710.70,0.0,1.0,0.026182,2.0,cabo frio,RJ,shipped,1.0,credit_card,3.0,beauty,0

In [25]:
test_120_df.to_csv(r"C:\Users\Hallen\Documents\mis_cosas\silvana\master\tfm-uned-churn\Data\Train_test\test_120.csv", index=False)