# Data preparation

Here the clean dataset will be processed to get the features dataset for 3 intervals:
- **90 days**:
- **120 days**:
- **150 days**:
    - Train:
        - From 04/09/2016
        - To 28/11/2017
    - Validation and test
        - From 01/12/2017
        - To 08/09/2018

We generate two terms for 90 days, 120 days, 150 days.

90 days: 180 days in total. The first 90 days are used to identify customers, and the other 90 days to see if they have purchased whithin that period. If not, they are categorized as churned customers. The same logic applies for 120 days and 150 days.

120 days: 240 days in total

150 days: 300 days in total

In [ ]:
import pandas as pd

import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
olist_path = "../Data/olist_post_cleaning.csv"

In [ ]:
# Load the data
olist_df = pd.read_csv(olist_path)

olist_df

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_id,order_status,order_purchase_timestamp,order_approved_at,order_estimated_delivery_date,...,review_score,product_photos_qty,seller_zip_code_prefix,seller_city,seller_state,product_category_name_english,freight_to_price_ratio,freight_to_weight_ratio,dates_diff,product_cat
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP,00e7ee1b050b8499577073aeb2a297a1,delivered,2017-05-16,2017-05-16,2017-06-05,...,4.0,1.0,8577.0,itaquaquecetuba,SP,office_furniture,0.175054,0.002520,-11.0,office
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP,29150127e6685892b6eab3eec79f59c7,delivered,2018-01-12,2018-01-12,2018-02-06,...,5.0,3.0,88303.0,itajai,SC,housewares,0.160830,0.004579,-8.0,household
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP,b2059ed67ce144a36e2aa97d2c9e9ad2,delivered,2018-05-19,2018-05-20,2018-06-13,...,5.0,1.0,8577.0,itaquaquecetuba,SP,office_furniture,0.127126,0.002152,1.0,office
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP,951670f92359f4fe4a63112aa7306eba,delivered,2018-03-13,2018-03-13,2018-04-10,...,5.0,1.0,8577.0,itaquaquecetuba,SP,office_furniture,0.155796,0.001921,-13.0,office
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP,6b7d50bd145f6fc7f33cebabd7e49d0f,delivered,2018-07-29,2018-07-29,2018-08-15,...,5.0,1.0,14940.0,ibitinga,SP,home_confort,0.096739,0.004279,-6.0,household
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118287,17ddf5dd5d51696bb3d7c6291687be6f,1a29b476fee25c95fbafc67c5ac95cf8,3937,sao paulo,SP,6760e20addcf0121e9d58f2f1ff14298,delivered,2018-04-07,2018-04-07,2018-04-25,...,4.0,2.0,17400.0,garca,SP,books_general_interest,0.185314,0.022717,-12.0,books_media
118288,e7b71a9017aa05c9a7fd292d714858e8,d52a67c98be1cf6a5c84435bd38d095d,6764,taboao da serra,SP,9ec0c8947d973db4f4e8dcf1fbfa8f1b,delivered,2018-04-04,2018-04-04,2018-04-20,...,5.0,1.0,14802.0,araraquara,SP,sports_leisure,0.123238,0.011693,-9.0,sports_leisure
118289,5e28dfe12db7fb50a4b2f691faecea5e,e9f50caf99f032f0bf3c55141f019d99,60115,fortaleza,CE,fed4434add09a6f332ea398efd656a5c,delivered,2018-04-08,2018-04-08,2018-05-02,...,1.0,1.0,3304.0,sao paulo,SP,health_beauty,0.514595,0.021885,7.0,beauty
118290,56b18e2166679b8a959d72dd06da27f9,73c2643a0a458b49f58cea58833b192e,92120,canoas,RS,e31ec91cea1ecf97797787471f98a8c2,delivered,2017-11-03,2017-11-03,2017-12-05,...,5.0,1.0,14840.0,guariba,SP,watches_gifts,0.032032,0.031085,-19.0,beauty
118291,274fa6071e5e17fe303b9748641082c8,84732c5050c01db9b23e19ba39899398,6703,cotia,SP,28db69209a75e59f20ccbb5c36a20b90,delivered,2017-12-19,2017-12-19,2018-01-08,...,5.0,1.0,3804.0,sao paulo,SP,perfumery,0.556112,0.155600,-13.0,beauty

In [581]:
olist_df["order_purchase_timestamp"] = pd.to_datetime(olist_df["order_purchase_timestamp"])

-------
-------

# Training data set by days

## 90 days

### 90 days term 1

In [582]:
pd.to_datetime("2016-12-01")

Timestamp('2016-12-01 00:00:00')

In [583]:
CHURN_DAYS = 90

In [584]:
start_date_90 = olist_df["order_purchase_timestamp"].min()

start_date_90

Timestamp('2016-09-04 00:00:00')

In [585]:
ninety_days_later = start_date_90 + pd.Timedelta(days= CHURN_DAYS)

ninety_days_later

Timestamp('2016-12-03 00:00:00')

In [ ]:
# 90 days to identify customers and another 90 days to see if they have churned

end_date = ninety_days_later + pd.Timedelta(days= CHURN_DAYS)

end_date

Timestamp('2017-03-03 00:00:00')

In [ ]:
# Identify who bought in the early 90 days 

is_customers = olist_df[
    (olist_df["order_purchase_timestamp"] >= start_date_90) & 
    (olist_df["order_purchase_timestamp"] < ninety_days_later)
]["customer_unique_id"].unique()

In [ ]:
# Customers that purchased again within the later 90 days

future_active_ids = set(
    olist_df[
        (olist_df["order_purchase_timestamp"] >= ninety_days_later) & 
        (olist_df["order_purchase_timestamp"] < end_date)
    ]["customer_unique_id"].unique()
)

In [ ]:
# Create an observation dataframe that include those IDs detected as customers
# We can not observe churn for a customer who never purchased on the platform

obs_df = olist_df[olist_df["customer_unique_id"].isin(is_customers)].copy()
obs_df = obs_df[
    (obs_df["order_purchase_timestamp"] >= start_date_90) & 
    (obs_df["order_purchase_timestamp"] < ninety_days_later)
]

In [ ]:
# Group the observation dataset by customer unique id, and aggregate features to include.
dataset_90_df = obs_df.groupby('customer_unique_id').agg({
    'price': 'sum',            # Total spent on the order (47.40 + 39.90)
    'freight_to_price_ratio': 'mean',    # Total shipping cost
    'payment_value': 'sum',    # Total amount charged to credit card
    'dates_diff': 'mean',
    'review_score': 'mean',
    'freight_to_weight_ratio': 'mean',
    'product_photos_qty':'mean',

    # Categorical and indicator columns to pull forward
    'customer_city': 'first', 
    'customer_state': 'first', 
    'order_status': 'first',
    'payment_sequential': 'max',
    'payment_type': 'first',
    'payment_installments': 'max',
    'product_cat': 'first'

}).reset_index()

dataset_90_df

,customer_unique_id,price,freight_to_price_ratio,payment_value,dates_diff,review_score,freight_to_weight_ratio,product_photos_qty,customer_city,customer_state,order_status,payment_sequential,payment_type,payment_installments,product_cat
0,0032c76b20340da25249092a268ce66c,128.90,0.124438,144.94,-27.0,4.0,0.002932,1.0,charqueada,SP,delivered,1.0,credit_card,1.0,entertainment
1,01f156677184504063bd19739f924af1,739.98,0.060569,784.80,-46.0,5.0,0.002873,2.0,gravatal,SC,delivered,1.0,credit_card,10.0,household
2,0313291a6f4f16df04dcf819d88c38ef,95.00,0.187158,112.78,0.0,1.0,0.017780,1.0,sao sebastiao,SP,processing,1.0,boleto,1.0,household
3,0636d30c77f0f9cfad81f1c9b58c791f,949.99,0.023127,971.96,-44.0,4.0,0.004674,2.0,itaquaquecetuba,SP,delivered,1.0,credit_card,10.0,entertainment
4,0659f2d6cabae94afd4d009c6d0e07dc,390.00,0.177282,918.28,0.0,1.0,0.003582,1.0,cacequi,RS,canceled,1.0,credit_card,4.0,automotive
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
302,ff39ae410be7f9b3a2457c546c6f67de,159.80,0.233417,98.55,0.0,3.0,0.010361,4.0,goiania,GO,shipped,2.0,voucher,1.0,commercial_industrial
303,ff68ad2883e793597f1c343dd6505f5d,499.80,0.070388,1069.96,-23.0,5.0,0.028836,1.0,ribeirao preto,SP,delivered,1.0,credit_card,8.0,beauty
304,ff822e5e1322cef6c211ad8a0591999e,15.90,0.913208,30.42,-35.0,5.0,0.032267,0.0,petropolis,RJ,delivered,1.0,boleto,1.0,unknown
305,ff8557b296729eaa30f078d974c86812,79.99,0.235529,98.83,-36.0,4.0,0.009420,1.0,sao jose,SC,delivered,1.0,credit_card,9.0,beauty
306,ffb973f2bb1c0cb807a99341a9b20dcd,87.30,0.247574,218.04,-47.0,5.0,0.007150,3.0,sao paulo,SP,delivered,1.0,credit_card,6.0,household

In [ ]:
# Generate a churn column. If the customer ID appears in the later 90 days, they are retained customers (1), otherwise they have churned (0)

dataset_90_df["churn_90"] =  (dataset_90_df["customer_unique_id"].isin(future_active_ids)).astype(int)

dataset_90_df["churn_90"]

0      0
1      0
2      0
3      0
4      0
      ..
302    0
303    0
304    0
305    0
306    0
Name: churn_90, Length: 307, dtype: int64

In [592]:
dataset_90_df["churn_90"].value_counts()

churn_90
0    307
Name: count, dtype: int64

In [ ]:
# Save the dataframe
dataset_90_df.to_csv(r"C:\Users\Hallen\Documents\mis_cosas\silvana\master\tfm-uned-churn\Data\churn_dataset_90_1.csv", index=False)

------------------------------------

### **90 days term 2**

In [594]:
start_date_90_t2 = pd.to_datetime(end_date)

start_date_90_t2

Timestamp('2017-03-03 00:00:00')

In [595]:
ninety_days_later_t2 = start_date_90_t2 + pd.Timedelta(days= CHURN_DAYS)

ninety_days_later_t2

Timestamp('2017-06-01 00:00:00')

In [596]:
end_date_t2 = ninety_days_later_t2 + pd.Timedelta(days= CHURN_DAYS)

end_date_t2

Timestamp('2017-08-30 00:00:00')

In [597]:
is_customers_t2 = olist_df[
    (olist_df["order_purchase_timestamp"] >= start_date_90_t2) & 
    (olist_df["order_purchase_timestamp"] < ninety_days_later_t2)
]["customer_unique_id"].unique()

In [598]:
future_active_ids = set(
    olist_df[
        (olist_df["order_purchase_timestamp"] >= ninety_days_later_t2) & 
        (olist_df["order_purchase_timestamp"] < end_date_t2)
    ]["customer_unique_id"].unique()
)

In [599]:
obs_t2_df = olist_df[olist_df["customer_unique_id"].isin(is_customers_t2)].copy()
obs_t2_df = obs_t2_df[
    (obs_t2_df["order_purchase_timestamp"] >= start_date_90_t2) & 
    (obs_t2_df["order_purchase_timestamp"] < ninety_days_later_t2)]

In [600]:
dataset_90_t2_df = obs_t2_df.groupby('customer_unique_id').agg({
    'price': 'sum',            # Total spent on the order (47.40 + 39.90)
    'freight_to_price_ratio': 'mean',    # Total shipping cost
    'payment_value': 'sum',    # Total amount charged to credit card
    'dates_diff': 'mean',
    'review_score': 'mean',
    'freight_to_weight_ratio': 'mean',
    'product_photos_qty':'mean',

    # Categorical and indicator columns to pull forward
    'customer_city': 'first', 
    'customer_state': 'first', 
    'order_status': 'first',
    'payment_sequential': 'max',
    'payment_type': 'first',
    'payment_installments': 'max',
    'product_cat': 'first'

}).reset_index()

dataset_90_t2_df

,customer_unique_id,price,freight_to_price_ratio,payment_value,dates_diff,review_score,freight_to_weight_ratio,product_photos_qty,customer_city,customer_state,order_status,payment_sequential,payment_type,payment_installments,product_cat
0,0000f46a3911fa3c0805444483337064,69.00,0.249565,86.22,-2.0,3.0,0.011480,3.0,sao jose,SC,delivered,1.0,credit_card,8.0,office
1,0005e1862207bf6ccc02e4228effd9a0,135.00,0.112000,150.12,-28.0,4.0,0.006720,6.0,teresopolis,RJ,delivered,1.0,credit_card,3.0,fashion
2,0011805441c0d1b68b48002f1d005526,269.00,0.104610,297.14,-13.0,3.0,0.140700,1.0,goianesia do para,PA,delivered,1.0,credit_card,10.0,electronics
3,00191a9719ef48ebb5860b130347bf33,47.90,0.228810,58.86,-19.0,3.0,0.018267,1.0,jarinu,SP,delivered,1.0,credit_card,2.0,household
4,001f3c4211216384d5fe59b041ce1461,24.88,0.440514,35.84,-11.0,3.0,0.043840,1.0,sao paulo,SP,delivered,1.0,credit_card,3.0,household
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8350,ffe3e199b9d0b7fb7d2d29a5b9498447,146.90,0.103472,162.10,0.0,1.0,0.043429,2.0,uberlandia,MG,delivered,1.0,boleto,1.0,construction
8351,ffe4c3aa14d4702fb11fe5b3c4dd755c,118.90,0.154752,137.30,-15.0,5.0,0.013143,4.0,sarzedo,MG,delivered,1.0,credit_card,1.0,beauty
8352,ffedff0547d809c90c05c2691c51f9b7,17.90,0.811173,32.42,-56.0,5.0,0.064533,1.0,ribeirao preto,SP,delivered,1.0,credit_card,3.0,household
8353,ffef0ffa736c7b3d9af741611089729b,109.90,0.265423,139.07,-22.0,5.0,0.025678,1.0,nova venecia,ES,delivered,1.0,credit_card,1.0,sports_leisure
8354,ffffd2657e2aad2907e67c3e9daecbeb,56.99,0.255659,71.56,-16.0,5.0,0.036425,2.0,campo largo,PR,delivered,1.0,credit_card,4.0,beauty

In [601]:
dataset_90_t2_df["churn_90"] =  (dataset_90_t2_df["customer_unique_id"].isin(future_active_ids)).astype(int)

dataset_90_t2_df["churn_90"]

0       0
1       0
2       0
3       0
4       0
       ..
8350    0
8351    0
8352    0
8353    0
8354    0
Name: churn_90, Length: 8355, dtype: int64

In [602]:
dataset_90_t2_df["churn_90"].value_counts()

churn_90
0    8276
1      79
Name: count, dtype: int64

In [603]:
dataset_90_t2_df.to_csv(r"C:\Users\Hallen\Documents\mis_cosas\silvana\master\tfm-uned-churn\Data\churn_dataset_90_days2.csv", index=False)

-----

----------------------------------------------------------------------
----------------------------------

## 120 days

### **120 days term 1**

In [604]:
CHURN_DAYS = 120

In [605]:
start_date_120 = olist_df["order_purchase_timestamp"].min()

start_date_120

Timestamp('2016-09-04 00:00:00')

In [606]:
one_hundred_twenty_days_later = start_date_120 + pd.Timedelta(days= CHURN_DAYS)

one_hundred_twenty_days_later

Timestamp('2017-01-02 00:00:00')

In [607]:
end_date_one_hundred_twenty = one_hundred_twenty_days_later + pd.Timedelta(days= CHURN_DAYS)

end_date_one_hundred_twenty

Timestamp('2017-05-02 00:00:00')

In [608]:
is_customers_one_hundred_twenty = olist_df[
    (olist_df["order_purchase_timestamp"] >= start_date_120) & 
    (olist_df["order_purchase_timestamp"] < one_hundred_twenty_days_later)
]["customer_unique_id"].unique()

In [609]:
future_active_ids = set(
    olist_df[
        (olist_df["order_purchase_timestamp"] >= one_hundred_twenty_days_later) & 
        (olist_df["order_purchase_timestamp"] < end_date_one_hundred_twenty)
    ]["customer_unique_id"].unique()
)

In [610]:
obs_one_hundred_twenty_df = olist_df[olist_df["customer_unique_id"].isin(is_customers_one_hundred_twenty)].copy()
obs_one_hundred_twenty_df = obs_one_hundred_twenty_df[
    (obs_one_hundred_twenty_df["order_purchase_timestamp"] >= start_date_120) & 
    (obs_one_hundred_twenty_df["order_purchase_timestamp"] < one_hundred_twenty_days_later)]

In [611]:
dataset_120_df = obs_one_hundred_twenty_df.groupby('customer_unique_id').agg({
    'price': 'sum',            # Total spent on the order (47.40 + 39.90)
    'freight_to_price_ratio': 'mean',    # Total shipping cost
    'payment_value': 'sum',    # Total amount charged to credit card
    'dates_diff': 'mean',
    'review_score': 'mean',
    'freight_to_weight_ratio': 'mean',
    'product_photos_qty':'mean',

    # Categorical and indicator columns to pull forward
    'customer_city': 'first', 
    'customer_state': 'first', 
    'order_status': 'first',
    'payment_sequential': 'max',
    'payment_type': 'first',
    'payment_installments': 'max',
    'product_cat': 'first'

}).reset_index()

dataset_120_df

,customer_unique_id,price,freight_to_price_ratio,payment_value,dates_diff,review_score,freight_to_weight_ratio,product_photos_qty,customer_city,customer_state,order_status,payment_sequential,payment_type,payment_installments,product_cat
0,0032c76b20340da25249092a268ce66c,128.90,0.124438,144.94,-27.0,4.0,0.002932,1.0,charqueada,SP,delivered,1.0,credit_card,1.0,entertainment
1,01f156677184504063bd19739f924af1,739.98,0.060569,784.80,-46.0,5.0,0.002873,2.0,gravatal,SC,delivered,1.0,credit_card,10.0,household
2,0313291a6f4f16df04dcf819d88c38ef,95.00,0.187158,112.78,0.0,1.0,0.017780,1.0,sao sebastiao,SP,processing,1.0,boleto,1.0,household
3,0636d30c77f0f9cfad81f1c9b58c791f,949.99,0.023127,971.96,-44.0,4.0,0.004674,2.0,itaquaquecetuba,SP,delivered,1.0,credit_card,10.0,entertainment
4,0659f2d6cabae94afd4d009c6d0e07dc,390.00,0.177282,918.28,0.0,1.0,0.003582,1.0,cacequi,RS,canceled,1.0,credit_card,4.0,automotive
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
303,ff39ae410be7f9b3a2457c546c6f67de,159.80,0.233417,98.55,0.0,3.0,0.010361,4.0,goiania,GO,shipped,2.0,voucher,1.0,commercial_industrial
304,ff68ad2883e793597f1c343dd6505f5d,499.80,0.070388,1069.96,-23.0,5.0,0.028836,1.0,ribeirao preto,SP,delivered,1.0,credit_card,8.0,beauty
305,ff822e5e1322cef6c211ad8a0591999e,15.90,0.913208,30.42,-35.0,5.0,0.032267,0.0,petropolis,RJ,delivered,1.0,boleto,1.0,unknown
306,ff8557b296729eaa30f078d974c86812,79.99,0.235529,98.83,-36.0,4.0,0.009420,1.0,sao jose,SC,delivered,1.0,credit_card,9.0,beauty
307,ffb973f2bb1c0cb807a99341a9b20dcd,87.30,0.247574,218.04,-47.0,5.0,0.007150,3.0,sao paulo,SP,delivered,1.0,credit_card,6.0,household

In [612]:
dataset_120_df["churn_120"] =  (dataset_120_df["customer_unique_id"].isin(future_active_ids)).astype(int)

dataset_120_df["churn_120"]

0      0
1      0
2      0
3      0
4      0
      ..
303    0
304    0
305    0
306    0
307    0
Name: churn_120, Length: 308, dtype: int64

In [613]:
dataset_120_df["churn_120"].value_counts()

churn_120
0    306
1      2
Name: count, dtype: int64

In [614]:
dataset_120_df.to_csv(r"C:\Users\Hallen\Documents\mis_cosas\silvana\master\tfm-uned-churn\Data\churn_dataset_120_1.csv", index=False)

-------

### **120 days term 2**

In [615]:
start_date_120_t2 = one_hundred_twenty_days_later

start_date_120_t2

Timestamp('2017-01-02 00:00:00')

In [616]:
one_hundred_twenty_days_later_t2 = start_date_120_t2 + pd.Timedelta(days= CHURN_DAYS)

one_hundred_twenty_days_later_t2

Timestamp('2017-05-02 00:00:00')

In [617]:
end_date_one_hundred_twenty_t2 = one_hundred_twenty_days_later_t2 + pd.Timedelta(days= CHURN_DAYS)

end_date_one_hundred_twenty_t2

Timestamp('2017-08-30 00:00:00')

In [618]:
is_customers_one_hundred_twenty_t2 = olist_df[
    (olist_df["order_purchase_timestamp"] >= start_date_120_t2) & 
    (olist_df["order_purchase_timestamp"] < one_hundred_twenty_days_later_t2)
]["customer_unique_id"].unique()

In [619]:
future_active_ids = set(
    olist_df[
        (olist_df["order_purchase_timestamp"] >= one_hundred_twenty_days_later_t2) & 
        (olist_df["order_purchase_timestamp"] < end_date_one_hundred_twenty_t2)
    ]["customer_unique_id"].unique()
)

In [620]:
obs_one_hundred_twenty_t2df = olist_df[olist_df["customer_unique_id"].isin(is_customers_one_hundred_twenty_t2)].copy()
obs_one_hundred_twenty_t2df = obs_one_hundred_twenty_t2df[
    (obs_one_hundred_twenty_t2df["order_purchase_timestamp"] >= start_date_120_t2) & 
    (obs_one_hundred_twenty_t2df["order_purchase_timestamp"] < one_hundred_twenty_days_later_t2)]

In [621]:
dataset_120_t2df = obs_one_hundred_twenty_t2df.groupby('customer_unique_id').agg({
    'price': 'sum',            # Total spent on the order (47.40 + 39.90)
    'freight_to_price_ratio': 'mean',    # Total shipping cost
    'payment_value': 'sum',    # Total amount charged to credit card
    'dates_diff': 'mean',
    'review_score': 'mean',
    'freight_to_weight_ratio': 'mean',
    'product_photos_qty':'mean',

    # Categorical and indicator columns to pull forward
    'customer_city': 'first', 
    'customer_state': 'first', 
    'order_status': 'first',
    'payment_sequential': 'max',
    'payment_type': 'first',
    'payment_installments': 'max',
    'product_cat': 'first'

}).reset_index()

dataset_120_t2df

,customer_unique_id,price,freight_to_price_ratio,payment_value,dates_diff,review_score,freight_to_weight_ratio,product_photos_qty,customer_city,customer_state,order_status,payment_sequential,payment_type,payment_installments,product_cat
0,0000f46a3911fa3c0805444483337064,69.00,0.249565,86.22,-2.0,3.0,0.011480,3.0,sao jose,SC,delivered,1.0,credit_card,8.0,office
1,0005e1862207bf6ccc02e4228effd9a0,135.00,0.112000,150.12,-28.0,4.0,0.006720,6.0,teresopolis,RJ,delivered,1.0,credit_card,3.0,fashion
2,00115fc7123b5310cf6d3a3aa932699e,59.99,0.268711,76.11,-33.0,4.0,0.030705,6.0,brasilia,DF,delivered,1.0,credit_card,1.0,sports_leisure
3,0011805441c0d1b68b48002f1d005526,269.00,0.104610,297.14,-13.0,3.0,0.140700,1.0,goianesia do para,PA,delivered,1.0,credit_card,10.0,electronics
4,00191a9719ef48ebb5860b130347bf33,47.90,0.228810,58.86,-19.0,3.0,0.018267,1.0,jarinu,SP,delivered,1.0,credit_card,2.0,household
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7487,ffe2dd1f3b0cbf0b5f35e818ec03c49b,89.99,0.230137,110.70,-9.0,4.0,0.011834,1.0,rio de janeiro,RJ,delivered,1.0,credit_card,2.0,household
7488,ffe3e199b9d0b7fb7d2d29a5b9498447,146.90,0.103472,162.10,0.0,1.0,0.043429,2.0,uberlandia,MG,delivered,1.0,boleto,1.0,construction
7489,ffebb6424578e7bb153322da9d65634f,629.00,0.058347,665.70,-5.0,1.0,0.005169,2.0,guarulhos,SP,delivered,1.0,credit_card,8.0,entertainment
7490,ffedff0547d809c90c05c2691c51f9b7,17.90,0.811173,32.42,-56.0,5.0,0.064533,1.0,ribeirao preto,SP,delivered,1.0,credit_card,3.0,household
7491,ffff371b4d645b6ecea244b27531430a,89.90,0.250945,112.46,-30.0,5.0,0.037600,5.0,sinop,MT,delivered,1.0,credit_card,1.0,automotive

In [622]:
dataset_120_t2df["churn_120"] =  (dataset_120_t2df["customer_unique_id"].isin(future_active_ids)).astype(int)

dataset_120_t2df["churn_120"]

0       0
1       0
2       0
3       0
4       0
       ..
7487    0
7488    0
7489    0
7490    0
7491    0
Name: churn_120, Length: 7492, dtype: int64

In [623]:
dataset_120_t2df["churn_120"].value_counts()

churn_120
0    7411
1      81
Name: count, dtype: int64

In [624]:
dataset_120_t2df.to_csv(r"C:\Users\Hallen\Documents\mis_cosas\silvana\master\tfm-uned-churn\Data\churn_dataset_120_2.csv", index=False)

-------
-------

## 150 days

### **150 days term 1**

In [625]:
CHURN_DAYS = 150

In [626]:
start_date_150 = olist_df["order_purchase_timestamp"].min()

start_date_150

Timestamp('2016-09-04 00:00:00')

In [627]:
one_hundred_fifty_days_later = start_date_150 + pd.Timedelta(days= CHURN_DAYS)

one_hundred_fifty_days_later

Timestamp('2017-02-01 00:00:00')

In [628]:
end_date_hundred_fifty = one_hundred_fifty_days_later + pd.Timedelta(days= CHURN_DAYS)

end_date_hundred_fifty

Timestamp('2017-07-01 00:00:00')

In [629]:
is_customers_one_hundred_fifty = olist_df[
    (olist_df["order_purchase_timestamp"] >= start_date_150) & 
    (olist_df["order_purchase_timestamp"] < one_hundred_fifty_days_later)
]["customer_unique_id"].unique()

In [630]:
future_active_ids = set(
    olist_df[
        (olist_df["order_purchase_timestamp"] >= one_hundred_fifty_days_later) & 
        (olist_df["order_purchase_timestamp"] < end_date_hundred_fifty)
    ]["customer_unique_id"].unique()
)

In [631]:
obs_one_hundred_fifty_df = olist_df[olist_df["customer_unique_id"].isin(is_customers_one_hundred_fifty)].copy()
obs_one_hundred_fifty_df = obs_one_hundred_fifty_df[
    (obs_one_hundred_fifty_df["order_purchase_timestamp"] >= start_date_150) & 
    (obs_one_hundred_fifty_df["order_purchase_timestamp"] < one_hundred_fifty_days_later)]

In [632]:
dataset_150_df = obs_one_hundred_fifty_df.groupby('customer_unique_id').agg({
    'price': 'sum',            # Total spent on the order (47.40 + 39.90)
    'freight_to_price_ratio': 'mean',    # Total shipping cost
    'payment_value': 'sum',    # Total amount charged to credit card
    'dates_diff': 'mean',
    'review_score': 'mean',
    'freight_to_weight_ratio': 'mean',
    'product_photos_qty':'mean',

    # Categorical and indicator columns to pull forward
    'customer_city': 'first', 
    'customer_state': 'first', 
    'order_status': 'first',
    'payment_sequential': 'max',
    'payment_type': 'first',
    'payment_installments': 'max',
    'product_cat': 'first'

}).reset_index()

dataset_150_df

,customer_unique_id,price,freight_to_price_ratio,payment_value,dates_diff,review_score,freight_to_weight_ratio,product_photos_qty,customer_city,customer_state,order_status,payment_sequential,payment_type,payment_installments,product_cat
0,00115fc7123b5310cf6d3a3aa932699e,59.99,0.268711,76.11,-33.0,4.0,0.030705,6.0,brasilia,DF,delivered,1.0,credit_card,1.0,sports_leisure
1,0032c76b20340da25249092a268ce66c,128.90,0.124438,144.94,-27.0,4.0,0.002932,1.0,charqueada,SP,delivered,1.0,credit_card,1.0,entertainment
2,008f3d5f45a11059239a5c452cd00006,309.90,0.086028,336.56,-28.0,5.0,0.059376,1.0,sao pedro da agua branca,MA,delivered,1.0,boleto,1.0,beauty
3,012e12f54f6e73b1faba89a119dab849,87.74,0.205152,105.74,-40.0,4.0,0.006207,10.0,maurilandia,GO,delivered,1.0,credit_card,5.0,household
4,01838e7d69d87bd8ff2b6ff06789adfb,126.90,0.253822,159.11,-35.0,5.0,0.035789,2.0,belem,PA,delivered,1.0,credit_card,1.0,fashion
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1055,ff8557b296729eaa30f078d974c86812,79.99,0.235529,98.83,-36.0,4.0,0.009420,1.0,sao jose,SC,delivered,1.0,credit_card,9.0,beauty
1056,ff8b95898b5d2ce400ce59b28c40bfbc,323.10,0.133581,732.52,-16.0,5.0,0.071933,4.0,goiania,GO,delivered,1.0,credit_card,3.0,electronics
1057,ff9b8e5654b51a827582daf1051b1918,169.90,0.580518,268.53,0.0,3.0,0.003288,2.0,belem,PA,shipped,1.0,credit_card,1.0,sports_leisure
1058,ffb973f2bb1c0cb807a99341a9b20dcd,87.30,0.247574,218.04,-47.0,5.0,0.007150,3.0,sao paulo,SP,delivered,1.0,credit_card,6.0,household
1059,ffebb6424578e7bb153322da9d65634f,629.00,0.058347,665.70,-5.0,1.0,0.005169,2.0,guarulhos,SP,delivered,1.0,credit_card,8.0,entertainment

In [633]:
dataset_150_df["churn_150"] =  (dataset_150_df["customer_unique_id"].isin(future_active_ids)).astype(int)

dataset_150_df["churn_150"]

0       0
1       0
2       0
3       0
4       0
       ..
1055    0
1056    0
1057    0
1058    0
1059    0
Name: churn_150, Length: 1060, dtype: int64

In [634]:
dataset_150_df["churn_150"].value_counts()

churn_150
0    1049
1      11
Name: count, dtype: int64

In [635]:
dataset_150_df.to_csv(r"C:\Users\Hallen\Documents\mis_cosas\silvana\master\tfm-uned-churn\Data\churn_dataset_150_1.csv", index=False)

-----

### **150 days term 2**

In [636]:
start_date_150_t2 = one_hundred_fifty_days_later

start_date_150_t2

Timestamp('2017-02-01 00:00:00')

In [637]:
one_hundred_fifty_days_later_t2 = start_date_150_t2 + pd.Timedelta(days= CHURN_DAYS)

one_hundred_fifty_days_later_t2

Timestamp('2017-07-01 00:00:00')

In [638]:
end_date_hundred_fifty_t2 = one_hundred_fifty_days_later_t2 + pd.Timedelta(days= CHURN_DAYS)

end_date_hundred_fifty_t2

Timestamp('2017-11-28 00:00:00')

In [639]:
is_customers_one_hundred_fifty_t2 = olist_df[
    (olist_df["order_purchase_timestamp"] >= start_date_150_t2) & 
    (olist_df["order_purchase_timestamp"] < one_hundred_fifty_days_later_t2)
]["customer_unique_id"].unique()

In [640]:
future_active_ids = set(
    olist_df[
        (olist_df["order_purchase_timestamp"] >= one_hundred_fifty_days_later_t2) & 
        (olist_df["order_purchase_timestamp"] < end_date_hundred_fifty_t2)
    ]["customer_unique_id"].unique()
)

In [641]:
obs_one_hundred_fifty_t2df = olist_df[olist_df["customer_unique_id"].isin(is_customers_one_hundred_fifty_t2)].copy()
obs_one_hundred_fifty_t2df = obs_one_hundred_fifty_t2df[
    (obs_one_hundred_fifty_t2df["order_purchase_timestamp"] >= start_date_150_t2) & 
    (obs_one_hundred_fifty_t2df["order_purchase_timestamp"] < one_hundred_fifty_days_later_t2)]

In [642]:
dataset_150_t2df = obs_one_hundred_fifty_t2df.groupby('customer_unique_id').agg({
    'price': 'sum',            # Total spent on the order (47.40 + 39.90)
    'freight_to_price_ratio': 'mean',    # Total shipping cost
    'payment_value': 'sum',    # Total amount charged to credit card
    'dates_diff': 'mean',
    'review_score': 'mean',
    'freight_to_weight_ratio': 'mean',
    'product_photos_qty':'mean',

    # Categorical and indicator columns to pull forward
    'customer_city': 'first', 
    'customer_state': 'first', 
    'order_status': 'first',
    'payment_sequential': 'max',
    'payment_type': 'first',
    'payment_installments': 'max',
    'product_cat': 'first'

}).reset_index()

dataset_150_t2df

,customer_unique_id,price,freight_to_price_ratio,payment_value,dates_diff,review_score,freight_to_weight_ratio,product_photos_qty,customer_city,customer_state,order_status,payment_sequential,payment_type,payment_installments,product_cat
0,0000f46a3911fa3c0805444483337064,69.00,0.249565,86.22,-2.0,3.0,0.011480,3.0,sao jose,SC,delivered,1.0,credit_card,8.0,office
1,0005e1862207bf6ccc02e4228effd9a0,135.00,0.112000,150.12,-28.0,4.0,0.006720,6.0,teresopolis,RJ,delivered,1.0,credit_card,3.0,fashion
2,0011805441c0d1b68b48002f1d005526,269.00,0.104610,297.14,-13.0,3.0,0.140700,1.0,goianesia do para,PA,delivered,1.0,credit_card,10.0,electronics
3,0011857aff0e5871ce5eb429f21cdaf5,174.33,0.106121,192.83,-20.0,5.0,0.038302,2.0,santo andre,SP,delivered,1.0,credit_card,3.0,fashion
4,00191a9719ef48ebb5860b130347bf33,47.90,0.228810,58.86,-19.0,3.0,0.018267,1.0,jarinu,SP,delivered,1.0,credit_card,2.0,household
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13307,ffedff0547d809c90c05c2691c51f9b7,17.90,0.811173,32.42,-56.0,5.0,0.064533,1.0,ribeirao preto,SP,delivered,1.0,credit_card,3.0,household
13308,ffef0ffa736c7b3d9af741611089729b,109.90,0.265423,139.07,-22.0,5.0,0.025678,1.0,nova venecia,ES,delivered,1.0,credit_card,1.0,sports_leisure
13309,fffcf5a5ff07b0908bd4e2dbc735a684,1570.00,0.320939,4134.84,-27.0,5.0,0.008290,1.0,sanharo,PE,delivered,1.0,credit_card,10.0,beauty
13310,ffff371b4d645b6ecea244b27531430a,89.90,0.250945,112.46,-30.0,5.0,0.037600,5.0,sinop,MT,delivered,1.0,credit_card,1.0,automotive
13311,ffffd2657e2aad2907e67c3e9daecbeb,56.99,0.255659,71.56,-16.0,5.0,0.036425,2.0,campo largo,PR,delivered,1.0,credit_card,4.0,beauty

In [643]:
dataset_150_t2df["churn_150"] =  (dataset_150_t2df["customer_unique_id"].isin(future_active_ids)).astype(int)

dataset_150_t2df["churn_150"]

0        0
1        0
2        0
3        0
4        0
        ..
13307    0
13308    0
13309    0
13310    0
13311    0
Name: churn_150, Length: 13312, dtype: int64

In [644]:
dataset_150_t2df["churn_150"].value_counts()

churn_150
0    13128
1      184
Name: count, dtype: int64

In [645]:
dataset_150_t2df.to_csv(r"C:\Users\Hallen\Documents\mis_cosas\silvana\master\tfm-uned-churn\Data\churn_dataset_150_2.csv", index=False)

--------
--------

Calculating Max the test dates range

In [646]:
max_date = olist_df["order_purchase_timestamp"].max()

max_date

Timestamp('2018-09-03 00:00:00')

In [647]:
limit_test = max_date - (pd.Timedelta(days= 110)*2)

test_period = limit_test - pd.Timedelta(days= 10)

test_period

Timestamp('2018-01-16 00:00:00')

------
------

# Test data set by days

## 90 days

In [648]:
CHURN_DAYS = 90

In [649]:
start_date_90T = pd.to_datetime("2017-12-01")

start_date_90T

Timestamp('2017-12-01 00:00:00')

In [650]:
ninety_days_laterT = start_date_90T + pd.Timedelta(days= CHURN_DAYS)

ninety_days_laterT

Timestamp('2018-03-01 00:00:00')

In [651]:
end_dateT = ninety_days_laterT + pd.Timedelta(days= CHURN_DAYS)

end_dateT

Timestamp('2018-05-30 00:00:00')

In [652]:
is_customers_90 = olist_df[
    (olist_df["order_purchase_timestamp"] >= start_date_90T) & 
    (olist_df["order_purchase_timestamp"] < ninety_days_laterT)
]["customer_unique_id"].unique()

In [653]:
future_active_ids = set(
    olist_df[
        (olist_df["order_purchase_timestamp"] >= ninety_days_laterT) & 
        (olist_df["order_purchase_timestamp"] < end_dateT)
    ]["customer_unique_id"].unique()
)

In [654]:
obs_df = olist_df[olist_df["customer_unique_id"].isin(is_customers_90)].copy()
obs_df = obs_df[
    (obs_df["order_purchase_timestamp"] >= start_date_90T) & 
    (obs_df["order_purchase_timestamp"] < ninety_days_laterT)]

In [655]:
dataset_90_test_df = obs_df.groupby('customer_unique_id').agg({
    'price': 'sum',            # Total spent on the order (47.40 + 39.90)
    'freight_to_price_ratio': 'mean',    # Total shipping cost
    'payment_value': 'sum',    # Total amount charged to credit card
    'dates_diff': 'mean',
    'review_score': 'mean',
    'freight_to_weight_ratio': 'mean',
    'product_photos_qty':'mean',

    # Categorical and indicator columns to pull forward
    'customer_city': 'first', 
    'customer_state': 'first', 
    'order_status': 'first',
    'payment_sequential': 'max',
    'payment_type': 'first',
    'payment_installments': 'max',
    'product_cat': 'first'

}).reset_index()

dataset_90_test_df

,customer_unique_id,price,freight_to_price_ratio,payment_value,dates_diff,review_score,freight_to_weight_ratio,product_photos_qty,customer_city,customer_state,order_status,payment_sequential,payment_type,payment_installments,product_cat
0,00053a61a98854899e70ed204dd4bafe,382.00,0.097330,838.36,-10.0,1.0,0.016423,1.0,curitiba,PR,delivered,1.0,credit_card,3.0,sports_leisure
1,000c8bdb58a29e7115cfc257230fb21b,13.90,1.086331,29.00,-9.0,5.0,0.086286,2.0,belo horizonte,MG,delivered,1.0,credit_card,2.0,household
2,000d460961d6dbfa3ec6c9f5805769e1,28.90,0.269204,36.68,-13.0,5.0,0.051867,3.0,sao paulo,SP,delivered,1.0,credit_card,1.0,electronics
3,0014a5a58da615f7b01a4f5e194bf5ea,88.00,0.134318,99.82,-7.0,5.0,0.021491,2.0,sao paulo,SP,delivered,1.0,credit_card,3.0,beauty
4,00196fdb2bf9edfc35e88ebfbcf8d781,12.90,1.093023,27.00,1.0,3.0,0.080571,1.0,canoas,RS,delivered,1.0,credit_card,1.0,electronics
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19148,fff1bdd5c5e37ca79dd74deeb91aa5b6,134.90,0.282283,172.98,32.0,1.0,0.006060,4.0,araguaina,TO,delivered,2.0,debit_card,1.0,entertainment
19149,fff7219c86179ca6441b8f37823ba3d3,245.80,0.081367,531.60,-12.0,4.0,0.005714,1.0,cachoeiras de macacu,RJ,delivered,1.0,debit_card,1.0,household
19150,fffb09418989a0dbff854a28163e47c6,58.00,0.261379,73.16,-23.0,5.0,0.071174,1.0,veranopolis,RS,delivered,1.0,boleto,1.0,beauty
19151,fffbf87b7a1a6fa8b03f081c5f51a201,149.00,0.122953,167.32,-14.0,5.0,0.052343,0.0,fortaleza,CE,delivered,1.0,credit_card,2.0,unknown
19152,fffea47cd6d3cc0a88bd621562a9d061,64.89,0.303437,84.58,-3.0,4.0,0.011448,2.0,feira de santana,BA,delivered,1.0,credit_card,1.0,babies

In [656]:
dataset_90_test_df["churn_90"] =  (dataset_90_test_df["customer_unique_id"].isin(future_active_ids)).astype(int)

dataset_90_test_df["churn_90"]

0        0
1        0
2        0
3        0
4        0
        ..
19148    0
19149    0
19150    0
19151    0
19152    0
Name: churn_90, Length: 19153, dtype: int64

In [657]:
dataset_90_test_df["churn_90"].value_counts()

churn_90
0    18967
1      186
Name: count, dtype: int64

In [658]:
dataset_90_test_df.to_csv(r"C:\Users\Hallen\Documents\mis_cosas\silvana\master\tfm-uned-churn\Data\churn_test_dataset_90.csv", index=False)

___

# 90 days test term 2

In [659]:
start_date_90T2 = pd.to_datetime("2018-03-01")

start_date_90T2

Timestamp('2018-03-01 00:00:00')

In [660]:
ninety_days_laterT2 = start_date_90T2 + pd.Timedelta(days= CHURN_DAYS)

ninety_days_laterT2

Timestamp('2018-05-30 00:00:00')

In [661]:
end_dateT2 = ninety_days_laterT2 + pd.Timedelta(days= CHURN_DAYS)

end_dateT2

Timestamp('2018-08-28 00:00:00')

In [662]:
is_customers_90 = olist_df[
    (olist_df["order_purchase_timestamp"] >= start_date_90T2) & 
    (olist_df["order_purchase_timestamp"] < ninety_days_laterT2)
]["customer_unique_id"].unique()

In [663]:
future_active_ids = set(
    olist_df[
        (olist_df["order_purchase_timestamp"] >= ninety_days_laterT2) & 
        (olist_df["order_purchase_timestamp"] < end_dateT2)
    ]["customer_unique_id"].unique()
)

In [664]:
obs_df = olist_df[olist_df["customer_unique_id"].isin(is_customers_90)].copy()
obs_df = obs_df[
    (obs_df["order_purchase_timestamp"] >= start_date_90T2) & 
    (obs_df["order_purchase_timestamp"] < ninety_days_laterT2)]

In [665]:
dataset_90_test2_df = obs_df.groupby('customer_unique_id').agg({
    'price': 'sum',            # Total spent on the order (47.40 + 39.90)
    'freight_to_price_ratio': 'mean',    # Total shipping cost
    'payment_value': 'sum',    # Total amount charged to credit card
    'dates_diff': 'mean',
    'review_score': 'mean',
    'freight_to_weight_ratio': 'mean',
    'product_photos_qty':'mean',

    # Categorical and indicator columns to pull forward
    'customer_city': 'first', 
    'customer_state': 'first', 
    'order_status': 'first',
    'payment_sequential': 'max',
    'payment_type': 'first',
    'payment_installments': 'max',
    'product_cat': 'first'

}).reset_index()

dataset_90_test2_df

,customer_unique_id,price,freight_to_price_ratio,payment_value,dates_diff,review_score,freight_to_weight_ratio,product_photos_qty,customer_city,customer_state,order_status,payment_sequential,payment_type,payment_installments,product_cat
0,0000366f3b9a7992bf8c76cfdf3221e2,129.90,0.092379,141.90,-5.0,5.0,0.008000,1.0,cajamar,SP,delivered,1.0,credit_card,8.0,household
1,0000b849f77a49e4a4ce2b2a4ca5be3f,18.90,0.438624,27.19,-5.0,4.0,0.022107,1.0,osasco,SP,delivered,1.0,credit_card,1.0,beauty
2,0004bd2a26a76fe21f786e4fbd80607f,154.00,0.084286,166.98,-12.0,4.0,0.004327,3.0,sao paulo,SP,delivered,1.0,credit_card,8.0,miscellaneous
3,00050ab1314c0e55a6ca13cf7181fecf,27.99,0.264023,35.38,-12.0,4.0,0.024633,6.0,campinas,SP,delivered,1.0,boleto,1.0,electronics
4,0005ef4cd20d2893f0d9fbd94d3c0d97,104.90,0.236988,129.76,31.0,1.0,0.021884,1.0,sao luis,MA,delivered,1.0,credit_card,4.0,sports_leisure
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20392,ffecceca389973ef16660d58696f281e,59.90,0.214691,72.76,-15.0,5.0,0.064300,1.0,ilha solteira,SP,delivered,1.0,boleto,1.0,fashion
20393,ffeddf8aa7cdecf403e77b2e9a99e2ea,330.00,0.237576,204.20,6.0,2.0,0.174222,3.0,santarem,PA,delivered,2.0,credit_card,5.0,office
20394,fff2ae16b99c6f3c785f0e052f2a9cfb,129.94,0.546098,200.90,-21.0,5.0,0.005117,1.0,rio de janeiro,RJ,delivered,1.0,credit_card,8.0,office
20395,fffcc512b7dfecaffd80f13614af1d16,688.00,0.032994,710.70,0.0,1.0,0.026182,2.0,cabo frio,RJ,shipped,1.0,credit_card,3.0,beauty
20396,ffff5962728ec6157033ef9805bacc48,115.00,0.162522,133.69,-14.0,5.0,0.042095,3.0,bom jesus do norte,ES,delivered,1.0,credit_card,5.0,beauty

In [666]:
dataset_90_test2_df["churn_90"] =  (dataset_90_test2_df["customer_unique_id"].isin(future_active_ids)).astype(int)

dataset_90_test2_df["churn_90"]

0        0
1        0
2        0
3        0
4        0
        ..
20392    0
20393    0
20394    0
20395    0
20396    0
Name: churn_90, Length: 20397, dtype: int64

In [667]:
dataset_90_test_df["churn_90"].value_counts()

churn_90
0    18967
1      186
Name: count, dtype: int64

In [668]:
dataset_90_test2_df.to_csv(r"C:\Users\Hallen\Documents\mis_cosas\silvana\master\tfm-uned-churn\Data\churn_test_dataset_90_2.csv", index=False)

------
------

## 120 days

In [669]:
CHURN_DAYS = 120

In [670]:
one_hundred_twenty_days_laterT120 = start_date_90T + pd.Timedelta(days= CHURN_DAYS)

one_hundred_twenty_days_laterT120

Timestamp('2018-03-31 00:00:00')

In [671]:
end_dateT120 = one_hundred_twenty_days_laterT120 + pd.Timedelta(days= CHURN_DAYS)

end_dateT120

Timestamp('2018-07-29 00:00:00')

In [672]:
is_customers_120 = olist_df[
    (olist_df["order_purchase_timestamp"] >= start_date_90T) & 
    (olist_df["order_purchase_timestamp"] < one_hundred_twenty_days_laterT120)
]["customer_unique_id"].unique()

In [673]:
future_active_ids = set(
    olist_df[
        (olist_df["order_purchase_timestamp"] >= one_hundred_twenty_days_laterT120) & 
        (olist_df["order_purchase_timestamp"] < end_dateT120)
    ]["customer_unique_id"].unique())

In [674]:
obs_120_df = olist_df[olist_df["customer_unique_id"].isin(is_customers_120)].copy()
obs_120_df = obs_120_df[
    (obs_120_df["order_purchase_timestamp"] >= start_date_90T) & 
    (obs_120_df["order_purchase_timestamp"] < one_hundred_twenty_days_laterT120)]

In [675]:
dataset_120_test_df = obs_120_df.groupby('customer_unique_id').agg({
    'price': 'sum',            # Total spent on the order (47.40 + 39.90)
    'freight_to_price_ratio': 'mean',    # Total shipping cost
    'payment_value': 'sum',    # Total amount charged to credit card
    'dates_diff': 'mean',
    'review_score': 'mean',
    'freight_to_weight_ratio': 'mean',
    'product_photos_qty':'mean',

    # Categorical and indicator columns to pull forward
    'customer_city': 'first', 
    'customer_state': 'first', 
    'order_status': 'first',
    'payment_sequential': 'max',
    'payment_type': 'first',
    'payment_installments': 'max',
    'product_cat': 'first'

}).reset_index()

dataset_120_test_df

,customer_unique_id,price,freight_to_price_ratio,payment_value,dates_diff,review_score,freight_to_weight_ratio,product_photos_qty,customer_city,customer_state,order_status,payment_sequential,payment_type,payment_installments,product_cat
0,00053a61a98854899e70ed204dd4bafe,382.00,0.097330,838.36,-10.0,1.0,0.016423,1.0,curitiba,PR,delivered,1.0,credit_card,3.0,sports_leisure
1,0005ef4cd20d2893f0d9fbd94d3c0d97,104.90,0.236988,129.76,31.0,1.0,0.021884,1.0,sao luis,MA,delivered,1.0,credit_card,4.0,sports_leisure
2,00090324bbad0e9342388303bb71ba0a,49.95,0.274474,63.66,-8.0,5.0,0.030467,2.0,campinas,SP,delivered,1.0,credit_card,3.0,household
3,000c8bdb58a29e7115cfc257230fb21b,13.90,1.086331,29.00,-9.0,5.0,0.086286,2.0,belo horizonte,MG,delivered,1.0,credit_card,2.0,household
4,000d460961d6dbfa3ec6c9f5805769e1,28.90,0.269204,36.68,-13.0,5.0,0.051867,3.0,sao paulo,SP,delivered,1.0,credit_card,1.0,electronics
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26013,fff1bdd5c5e37ca79dd74deeb91aa5b6,134.90,0.282283,172.98,32.0,1.0,0.006060,4.0,araguaina,TO,delivered,2.0,debit_card,1.0,entertainment
26014,fff7219c86179ca6441b8f37823ba3d3,245.80,0.081367,531.60,-12.0,4.0,0.005714,1.0,cachoeiras de macacu,RJ,delivered,1.0,debit_card,1.0,household
26015,fffb09418989a0dbff854a28163e47c6,58.00,0.261379,73.16,-23.0,5.0,0.071174,1.0,veranopolis,RS,delivered,1.0,boleto,1.0,beauty
26016,fffbf87b7a1a6fa8b03f081c5f51a201,149.00,0.122953,167.32,-14.0,5.0,0.052343,0.0,fortaleza,CE,delivered,1.0,credit_card,2.0,unknown
26017,fffea47cd6d3cc0a88bd621562a9d061,64.89,0.303437,84.58,-3.0,4.0,0.011448,2.0,feira de santana,BA,delivered,1.0,credit_card,1.0,babies

In [676]:
dataset_120_test_df["churn_120"] =  (dataset_120_test_df["customer_unique_id"].isin(future_active_ids)).astype(int)

dataset_120_test_df["churn_120"]

0        0
1        0
2        0
3        0
4        0
        ..
26013    0
26014    0
26015    0
26016    0
26017    0
Name: churn_120, Length: 26018, dtype: int64

In [677]:
dataset_120_test_df["churn_120"].value_counts()

churn_120
0    25747
1      271
Name: count, dtype: int64

In [678]:
dataset_120_test_df.to_csv(r"C:\Users\Hallen\Documents\mis_cosas\silvana\master\tfm-uned-churn\Data\churn_test_dataset_120.csv", index=False)

-----

# 120 days test term 2

In [679]:
start_date_120T2 = pd.to_datetime("2018-01-01")

start_date_120T2

Timestamp('2018-01-01 00:00:00')

In [680]:
one_hundred_twenty_days_laterT120_2 = start_date_120T2 + pd.Timedelta(days= CHURN_DAYS)

one_hundred_twenty_days_laterT120_2

Timestamp('2018-05-01 00:00:00')

In [681]:
end_dateT120_2 = one_hundred_twenty_days_laterT120_2 + pd.Timedelta(days= CHURN_DAYS)

end_dateT120_2

Timestamp('2018-08-29 00:00:00')

In [682]:
is_customers_120 = olist_df[
    (olist_df["order_purchase_timestamp"] >= start_date_90T2) & 
    (olist_df["order_purchase_timestamp"] < one_hundred_twenty_days_laterT120_2)
]["customer_unique_id"].unique()

In [683]:
future_active_ids = set(
    olist_df[
        (olist_df["order_purchase_timestamp"] >= one_hundred_twenty_days_laterT120_2) & 
        (olist_df["order_purchase_timestamp"] < end_dateT120_2)
    ]["customer_unique_id"].unique())

In [684]:
obs_120_df = olist_df[olist_df["customer_unique_id"].isin(is_customers_120)].copy()
obs_120_df = obs_120_df[
    (obs_120_df["order_purchase_timestamp"] >= start_date_90T2) & 
    (obs_120_df["order_purchase_timestamp"] < one_hundred_twenty_days_laterT120_2)]

In [685]:
dataset_120_test2_df = obs_120_df.groupby('customer_unique_id').agg({
    'price': 'sum',            # Total spent on the order (47.40 + 39.90)
    'freight_to_price_ratio': 'mean',    # Total shipping cost
    'payment_value': 'sum',    # Total amount charged to credit card
    'dates_diff': 'mean',
    'review_score': 'mean',
    'freight_to_weight_ratio': 'mean',
    'product_photos_qty':'mean',

    # Categorical and indicator columns to pull forward
    'customer_city': 'first', 
    'customer_state': 'first', 
    'order_status': 'first',
    'payment_sequential': 'max',
    'payment_type': 'first',
    'payment_installments': 'max',
    'product_cat': 'first'

}).reset_index()

dataset_120_test2_df

,customer_unique_id,price,freight_to_price_ratio,payment_value,dates_diff,review_score,freight_to_weight_ratio,product_photos_qty,customer_city,customer_state,order_status,payment_sequential,payment_type,payment_installments,product_cat
0,0004bd2a26a76fe21f786e4fbd80607f,154.00,0.084286,166.98,-12.0,4.0,0.004327,3.0,sao paulo,SP,delivered,1.0,credit_card,8.0,miscellaneous
1,00050ab1314c0e55a6ca13cf7181fecf,27.99,0.264023,35.38,-12.0,4.0,0.024633,6.0,campinas,SP,delivered,1.0,boleto,1.0,electronics
2,0005ef4cd20d2893f0d9fbd94d3c0d97,104.90,0.236988,129.76,31.0,1.0,0.021884,1.0,sao luis,MA,delivered,1.0,credit_card,4.0,sports_leisure
3,00090324bbad0e9342388303bb71ba0a,49.95,0.274474,63.66,-8.0,5.0,0.030467,2.0,campinas,SP,delivered,1.0,credit_card,3.0,household
4,000949456b182f53c18b68d6babc79c1,64.89,0.264448,82.05,-15.0,4.0,0.049029,2.0,sao bernardo do campo,SP,delivered,1.0,boleto,1.0,electronics
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13934,ffe76cb2f4bb39384c432d65ece67441,49.00,0.348163,66.06,-15.0,5.0,0.068240,3.0,camacari,BA,delivered,1.0,boleto,1.0,beauty
13935,ffec10ad4229ba46818560e1c8b40a68,120.00,0.131000,135.72,-10.0,5.0,0.104800,1.0,viana,ES,delivered,1.0,credit_card,3.0,sports_leisure
13936,ffecceca389973ef16660d58696f281e,59.90,0.214691,72.76,-15.0,5.0,0.064300,1.0,ilha solteira,SP,delivered,1.0,boleto,1.0,fashion
13937,fff2ae16b99c6f3c785f0e052f2a9cfb,129.94,0.546098,200.90,-21.0,5.0,0.005117,1.0,rio de janeiro,RJ,delivered,1.0,credit_card,8.0,office
13938,fffcc512b7dfecaffd80f13614af1d16,688.00,0.032994,710.70,0.0,1.0,0.026182,2.0,cabo frio,RJ,shipped,1.0,credit_card,3.0,beauty

In [686]:
dataset_120_test2_df["churn_120"] =  (dataset_120_test2_df["customer_unique_id"].isin(future_active_ids)).astype(int)

dataset_120_test2_df["churn_120"]

0        0
1        0
2        0
3        0
4        0
        ..
13934    0
13935    0
13936    0
13937    0
13938    0
Name: churn_120, Length: 13939, dtype: int64

In [687]:
dataset_120_test2_df.to_csv(r"C:\Users\Hallen\Documents\mis_cosas\silvana\master\tfm-uned-churn\Data\churn_test_dataset_120_2.csv", index=False)

-------

## 150 days

In [688]:
CHURN_DAYS = 150

In [689]:
one_hundred_fifty_days_laterT = start_date_90T + pd.Timedelta(days= CHURN_DAYS)

one_hundred_fifty_days_laterT

Timestamp('2018-04-30 00:00:00')

In [690]:
end_dateT150 = one_hundred_fifty_days_laterT + pd.Timedelta(days= CHURN_DAYS)

end_dateT150

Timestamp('2018-09-27 00:00:00')

In [691]:
is_customers_150 = olist_df[
    (olist_df["order_purchase_timestamp"] >= start_date_90T) & 
    (olist_df["order_purchase_timestamp"] < one_hundred_fifty_days_laterT)
]["customer_unique_id"].unique()

In [692]:
future_active_ids = set(
    olist_df[
        (olist_df["order_purchase_timestamp"] >= one_hundred_fifty_days_laterT) & 
        (olist_df["order_purchase_timestamp"] < end_dateT150)
    ]["customer_unique_id"].unique())

In [693]:
obs_150_df = olist_df[olist_df["customer_unique_id"].isin(is_customers_150)].copy()
obs_150_df = obs_150_df[
    (obs_150_df["order_purchase_timestamp"] >= start_date_90T) & 
    (obs_150_df["order_purchase_timestamp"] < one_hundred_fifty_days_laterT)]

In [694]:
dataset_150_test_df = obs_150_df.groupby('customer_unique_id').agg({
    'price': 'sum',            # Total spent on the order (47.40 + 39.90)
    'freight_to_price_ratio': 'mean',    # Total shipping cost
    'payment_value': 'sum',    # Total amount charged to credit card
    'dates_diff': 'mean',
    'review_score': 'mean',
    'freight_to_weight_ratio': 'mean',
    'product_photos_qty':'mean',

    # Categorical and indicator columns to pull forward
    'customer_city': 'first', 
    'customer_state': 'first', 
    'order_status': 'first',
    'payment_sequential': 'max',
    'payment_type': 'first',
    'payment_installments': 'max',
    'product_cat': 'first'

}).reset_index()

dataset_150_test_df

,customer_unique_id,price,freight_to_price_ratio,payment_value,dates_diff,review_score,freight_to_weight_ratio,product_photos_qty,customer_city,customer_state,order_status,payment_sequential,payment_type,payment_installments,product_cat
0,0004bd2a26a76fe21f786e4fbd80607f,154.00,0.084286,166.98,-12.0,4.0,0.004327,3.0,sao paulo,SP,delivered,1.0,credit_card,8.0,miscellaneous
1,00050ab1314c0e55a6ca13cf7181fecf,27.99,0.264023,35.38,-12.0,4.0,0.024633,6.0,campinas,SP,delivered,1.0,boleto,1.0,electronics
2,00053a61a98854899e70ed204dd4bafe,382.00,0.097330,838.36,-10.0,1.0,0.016423,1.0,curitiba,PR,delivered,1.0,credit_card,3.0,sports_leisure
3,0005ef4cd20d2893f0d9fbd94d3c0d97,104.90,0.236988,129.76,31.0,1.0,0.021884,1.0,sao luis,MA,delivered,1.0,credit_card,4.0,sports_leisure
4,00090324bbad0e9342388303bb71ba0a,49.95,0.274474,63.66,-8.0,5.0,0.030467,2.0,campinas,SP,delivered,1.0,credit_card,3.0,household
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32714,fff7219c86179ca6441b8f37823ba3d3,245.80,0.081367,531.60,-12.0,4.0,0.005714,1.0,cachoeiras de macacu,RJ,delivered,1.0,debit_card,1.0,household
32715,fffb09418989a0dbff854a28163e47c6,58.00,0.261379,73.16,-23.0,5.0,0.071174,1.0,veranopolis,RS,delivered,1.0,boleto,1.0,beauty
32716,fffbf87b7a1a6fa8b03f081c5f51a201,149.00,0.122953,167.32,-14.0,5.0,0.052343,0.0,fortaleza,CE,delivered,1.0,credit_card,2.0,unknown
32717,fffcc512b7dfecaffd80f13614af1d16,688.00,0.032994,710.70,0.0,1.0,0.026182,2.0,cabo frio,RJ,shipped,1.0,credit_card,3.0,beauty
32718,fffea47cd6d3cc0a88bd621562a9d061,64.89,0.303437,84.58,-3.0,4.0,0.011448,2.0,feira de santana,BA,delivered,1.0,credit_card,1.0,babies

In [695]:
dataset_150_test_df["churn_150"] =  (dataset_150_test_df["customer_unique_id"].isin(future_active_ids)).astype(int)

dataset_150_test_df["churn_150"]

0        0
1        0
2        0
3        0
4        0
        ..
32714    0
32715    0
32716    0
32717    0
32718    0
Name: churn_150, Length: 32719, dtype: int64

In [696]:
dataset_150_test_df["churn_150"].value_counts()

churn_150
0    32405
1      314
Name: count, dtype: int64

In [697]:
dataset_150_test_df.to_csv(r"C:\Users\Hallen\Documents\mis_cosas\silvana\master\tfm-uned-churn\Data\churn_test_dataset_150.csv", index=False)