In [4]:
import pandas as pd

import numpy as np

import matplotlib.pyplot as plt

import seaborn as sb

In [48]:
Data_90_path = "../Data/churn_dataset_90.csv"

Data_90_test_path = "../Data/churn_test_90_dataset.csv"

In [49]:
Data_90_df = pd.read_csv(Data_90_path) 

Data_90_df

                     customer_unique_id  ... payment_installments
0      0000f46a3911fa3c0805444483337064  ...                  8.0
1      0005e1862207bf6ccc02e4228effd9a0  ...                  3.0
2      00115fc7123b5310cf6d3a3aa932699e  ...                  1.0
3      0011805441c0d1b68b48002f1d005526  ...                 10.0
4      0011857aff0e5871ce5eb429f21cdaf5  ...                  3.0
...                                 ...  ...                  ...
14466  ffedff0547d809c90c05c2691c51f9b7  ...                  3.0
14467  ffef0ffa736c7b3d9af741611089729b  ...                  1.0
14468  fffcf5a5ff07b0908bd4e2dbc735a684  ...                 10.0
14469  ffff371b4d645b6ecea244b27531430a  ...                  1.0
14470  ffffd2657e2aad2907e67c3e9daecbeb  ...                  4.0

[14471 rows x 15 columns]

In [50]:
state_count = Data_90_df["customer_state"].value_counts()

state_count

customer_state
SP    5570
RJ    1970
MG    1767
RS     871
PR     805
SC     570
BA     495
ES     313
GO     302
DF     259
PE     226
CE     199
PA     182
MT     130
MA     120
MS      98
PB      90
AL      83
PI      83
SE      73
RN      66
RO      58
TO      57
AM      37
AC      24
AP      12
RR      11
Name: count, dtype: int64

In [51]:
# Income
HIGH_INCOME = ["SP", "RJ", "AM", "SE"]
MID_INCOME = ["PI", "PB", "MS", "ES", "BA", "AL", "PE", "RN", "CE"]
LOW_INCOME = ["RR", "RO", "MT", "GO", "TO", "RS", "SC", "PR", "MA", "MG", "AC", "PA", "AP", "DF"]

prov_income_map = {
    **{i:"high" for i in HIGH_INCOME},
    **{i:"mid" for i in MID_INCOME},
    **{i:"low" for i in LOW_INCOME}
}
prov_income_map

{'SP': 'high',
 'RJ': 'high',
 'AM': 'high',
 'SE': 'high',
 'PI': 'mid',
 'PB': 'mid',
 'MS': 'mid',
 'ES': 'mid',
 'BA': 'mid',
 'AL': 'mid',
 'PE': 'mid',
 'RN': 'mid',
 'CE': 'mid',
 'RR': 'low',
 'RO': 'low',
 'MT': 'low',
 'GO': 'low',
 'TO': 'low',
 'RS': 'low',
 'SC': 'low',
 'PR': 'low',
 'MA': 'low',
 'MG': 'low',
 'AC': 'low',
 'PA': 'low',
 'AP': 'low',
 'DF': 'low'}

In [52]:
Data_90_df["state_income_level"] = Data_90_df.customer_state.map(prov_income_map)

Data_90_df["state_income_level_high"] = (Data_90_df["state_income_level"] == "high").astype(int)
Data_90_df["state_income_level_mid"] = (Data_90_df["state_income_level"] == "mid").astype(int)
Data_90_df["state_income_level_low"] = (Data_90_df["state_income_level"] == "low").astype(int)

Data_90_df

                     customer_unique_id  ... state_income_level_low
0      0000f46a3911fa3c0805444483337064  ...                      1
1      0005e1862207bf6ccc02e4228effd9a0  ...                      0
2      00115fc7123b5310cf6d3a3aa932699e  ...                      1
3      0011805441c0d1b68b48002f1d005526  ...                      1
4      0011857aff0e5871ce5eb429f21cdaf5  ...                      0
...                                 ...  ...                    ...
14466  ffedff0547d809c90c05c2691c51f9b7  ...                      0
14467  ffef0ffa736c7b3d9af741611089729b  ...                      0
14468  fffcf5a5ff07b0908bd4e2dbc735a684  ...                      0
14469  ffff371b4d645b6ecea244b27531430a  ...                      1
14470  ffffd2657e2aad2907e67c3e9daecbeb  ...                      1

[14471 rows x 19 columns]

In [53]:
# Types of payment installments

Data_90_df["product_category_name_english"].value_counts()

product_category_name_english
bed_bath_table               1308
furniture_decor              1180
health_beauty                1101
sports_leisure               1069
housewares                    949
                             ...
costruction_tools_tools         3
computers                       2
fashion_childrens_clothes       2
la_cuisine                      1
security_and_services           1
Name: count, Length: 64, dtype: int64

In [ ]:
# One hot encoding for freight_price

In [ ]:
# One hot encoding for price

Data_90_df["is_high_price"] = (Data_90_df["price"]>120.64).astype(int)

Data_90_df["is_high_price"]

0        0
1        1
2        0
3        1
4        1
        ..
14466    0
14467    0
14468    1
14469    0
14470    0
Name: is_high_price, Length: 14471, dtype: int64

In [54]:
Data_90_df["beyond_one year"] = (Data_90_df["payment_installments"] > 12.0).astype(int)

Data_90_df["beyond_one year"]

0        0
1        0
2        0
3        0
4        0
        ..
14466    0
14467    0
14468    0
14469    0
14470    0
Name: beyond_one year, Length: 14471, dtype: int64

In [55]:
Data_90_df["multiple_payment_methods"] = (Data_90_df["payment_sequential"] > 2.0).astype(int)

Data_90_df["multiple_payment_methods"]

0        0
1        0
2        0
3        0
4        0
        ..
14466    0
14467    0
14468    0
14469    0
14470    0
Name: multiple_payment_methods, Length: 14471, dtype: int64

In [56]:
product_categories_map = {
    # --- ELECTRONICS ---
    "computers_accessories": "electronics",
    "telephony": "electronics",
    "tablets_printing_image": "electronics",
    "fixed_telephony": "electronics",
    "audio": "electronics",
    "air_conditioning": "electronics",
    "electronics": "electronics",
    "computers": "electronics",
    "cine_photo": "electronics",
    
    # --- HOUSEHOLD ---
    "bed_bath_table": "household",
    "furniture_decor": "household",
    "housewares": "household",
    "small_appliances": "household",
    "kitchen_dining_laundry_garden_furniture": "household",
    "home_appliances": "household",
    "home_confort": "household",
    "furniture_mattress_and_upholstery": "household",
    "furniture_living_room": "household",
    "furniture_bedroom": "household",
    "home_appliances_2": "household",
    "la_cuisine": "household",
    "home_comfort_2": "household",
    "small_appliances_home_oven_and_coffee": "household",
    
    # --- CONSTRUCTION ---
    "construction_tools_construction": "construction",
    "costruction_tools_garden": "construction",
    "home_construction": "construction",
    "construction_tools_lights": "construction",
    "construction_tools_safety": "construction",
    
    # --- BABIES ---
    "baby": "babies",
    "diapers_and_hygiene": "babies",
    "fashion_childrens_clothes": "babies",
    
    # --- OFFICE ---
    "stationery": "office",
    "office_furniture": "office",
    
    # --- ENTERTAINMENT ---
    "toys": "entertainment",
    "consoles_games": "entertainment",
    "cool_stuff": "entertainment", # Often miscellaneous trend/novelty items
    "party_supplies": "entertainment",
    "musical_instruments": "entertainment",
    "art": "entertainment",
    "christmas_supplies": "entertainment",
    
    # --- BEAUTY ---
    "health_beauty": "beauty",
    "perfumery": "beauty",
    "watches_gifts": "beauty", # Frequently grouped with personal styling/accessories
    
    # --- FASHION & ACCESSORIES ---
    # Comment: Added to group wearable items and luggage distinct from general beauty or household goods.
    "fashion_bags_accessories": "fashion",
    "fashion_shoes": "fashion",
    "luggage_accessories": "fashion",
    "fashion_male_clothing": "fashion",
    "fashion_underwear_beach": "fashion",
    "fashion_sport": "fashion",
    "fashio_female_clothing": "fashion",
    
    # --- AUTOMOTIVE ---
    # Comment: Added because automotive parts and tools do not fit standard household or electronics definitions.
    "auto": "automotive",
    
    # --- SPORTS & LEISURE ---
    # Comment: Added for outdoor activities, fitness gear, and hobbies that aren't strictly digital entertainment.
    "sports_leisure": "sports_leisure",
    
    # --- FOOD & BEVERAGE ---
    # Comment: Added because consumables (food, drinks) require different handling and classification than hard goods.
    "food_drink": "food_drink",
    "food": "food_drink",
    "drinks": "food_drink",
    
    # --- PETS ---
    # Comment: Added because pet supplies are a distinct retail vertical separate from human household or baby items.
    "pet_shop": "pet_shop",
    
    # --- BOOKS & MEDIA ---
    # Comment: Added to separate physical/digital reading materials and recorded media from toys and active entertainment.
    "books_technical": "books_media",
    "books_general_interest": "books_media",
    "books_imported": "books_media",
    "music": "books_media",
    "cds_dvds_musicals": "books_media",
    "dvds_blu_ray": "books_media",
    
    # --- COMMERCIAL & INDUSTRIAL ---
    # Comment: Added for B2B, agricultural, wholesale, or heavy professional categories.
    "market_place": "commercial_industrial",
    "costruction_tools_tools": "commercial_industrial", # Heavy professional tools
    "agro_industry_and_commerce": "commercial_industrial",
    "industry_commerce_and_business": "commercial_industrial",
    "signaling_and_security": "commercial_industrial",
    "security_and_services": "commercial_industrial",
    
    # --- MISCELLANEOUS ---
    # Comment: Added for specific items that span multiple categories (e.g., household decor vs. agriculture).
    "garden_tools": "miscellaneous",
    "flowers": "miscellaneous",
    "arts_and_craftmanship": "miscellaneous"
}

In [57]:
Data_90_df["product_cat"] = Data_90_df.product_category_name_english.map(product_categories_map)

Data_90_df["product_cat"].value_counts()

product_cat
household                3905
beauty                   2106
electronics              2077
entertainment            1653
sports_leisure           1069
fashion                   724
miscellaneous             544
office                    469
automotive                468
babies                    323
pet_shop                  261
commercial_industrial     134
books_media               117
food_drink                 73
construction               54
Name: count, dtype: int64

In [58]:
from sklearn.compose import ColumnTransformer

from sklearn.preprocessing import OneHotEncoder

In [59]:
# Create one hot encoding for all non-int features  Logprices?

target_features = ["order_status", "payment_type", "product_cat"]

col_trans = ColumnTransformer(transformers=[("cat", OneHotEncoder(sparse_output= False), target_features)], remainder="passthrough"

)

In [60]:
# fit and transform the dataset

encoded_array = col_trans.fit_transform(Data_90_df)

In [61]:
encoded_90_df = pd.DataFrame(encoded_array, columns= col_trans.get_feature_names_out(Data_90_df.columns))

encoded_90_df

      cat__order_status_approved  ... remainder__multiple_payment_methods
0                            0.0  ...                                   0
1                            0.0  ...                                   0
2                            0.0  ...                                   0
3                            0.0  ...                                   0
4                            0.0  ...                                   0
...                          ...  ...                                 ...
14466                        0.0  ...                                   0
14467                        0.0  ...                                   0
14468                        0.0  ...                                   0
14469                        0.0  ...                                   0
14470                        0.0  ...                                   0

[14471 rows x 46 columns]

In [62]:
encoded_90_df.columns = encoded_90_df.columns.str.replace('remainder__', '')

encoded_90_df

      cat__order_status_approved  ... multiple_payment_methods
0                            0.0  ...                        0
1                            0.0  ...                        0
2                            0.0  ...                        0
3                            0.0  ...                        0
4                            0.0  ...                        0
...                          ...  ...                      ...
14466                        0.0  ...                        0
14467                        0.0  ...                        0
14468                        0.0  ...                        0
14469                        0.0  ...                        0
14470                        0.0  ...                        0

[14471 rows x 46 columns]

beyond one tear= the payment takes more than one year

# Test dataset

In [63]:
Data_90_test_df = pd.read_csv(Data_90_test_path)

Data_90_test_df

                     customer_unique_id  ... payment_installments
0      0000366f3b9a7992bf8c76cfdf3221e2  ...                  8.0
1      0000b849f77a49e4a4ce2b2a4ca5be3f  ...                  1.0
2      0004bd2a26a76fe21f786e4fbd80607f  ...                  8.0
3      00050ab1314c0e55a6ca13cf7181fecf  ...                  1.0
4      0005ef4cd20d2893f0d9fbd94d3c0d97  ...                  4.0
...                                 ...  ...                  ...
39692  fff3e1d7bc75f11dc7670619b2e61840  ...                  1.0
39693  fff5eb4918b2bf4b2da476788d42051c  ...                  1.0
39694  fff96bc586f78b1f070da28c4977e810  ...                  2.0
39695  fffcc512b7dfecaffd80f13614af1d16  ...                  3.0
39696  ffff5962728ec6157033ef9805bacc48  ...                  5.0

[39697 rows x 15 columns]

In [64]:
Data_90_test_df["state_income_level"] = Data_90_test_df.customer_state.map(prov_income_map)

Data_90_test_df["state_income_level_high"] = (Data_90_test_df["state_income_level"] == "high").astype(int)
Data_90_test_df["state_income_level_mid"] = (Data_90_test_df["state_income_level"] == "mid").astype(int)
Data_90_test_df["state_income_level_low"] = (Data_90_test_df["state_income_level"] == "low").astype(int)

Data_90_test_df

                     customer_unique_id  ... state_income_level_low
0      0000366f3b9a7992bf8c76cfdf3221e2  ...                      0
1      0000b849f77a49e4a4ce2b2a4ca5be3f  ...                      0
2      0004bd2a26a76fe21f786e4fbd80607f  ...                      0
3      00050ab1314c0e55a6ca13cf7181fecf  ...                      0
4      0005ef4cd20d2893f0d9fbd94d3c0d97  ...                      1
...                                 ...  ...                    ...
39692  fff3e1d7bc75f11dc7670619b2e61840  ...                      0
39693  fff5eb4918b2bf4b2da476788d42051c  ...                      0
39694  fff96bc586f78b1f070da28c4977e810  ...                      0
39695  fffcc512b7dfecaffd80f13614af1d16  ...                      0
39696  ffff5962728ec6157033ef9805bacc48  ...                      0

[39697 rows x 19 columns]

In [65]:
Data_90_test_df["beyond_one year"] = (Data_90_test_df["payment_installments"] > 12.0).astype(int)

Data_90_test_df["beyond_one year"]

0        0
1        0
2        0
3        0
4        0
        ..
39692    0
39693    0
39694    0
39695    0
39696    0
Name: beyond_one year, Length: 39697, dtype: int64

In [66]:
Data_90_test_df["multiple_payment_methods"] = (Data_90_test_df["payment_sequential"] > 2.0).astype(int)

Data_90_test_df["multiple_payment_methods"]

0        0
1        0
2        0
3        0
4        0
        ..
39692    0
39693    0
39694    0
39695    0
39696    0
Name: multiple_payment_methods, Length: 39697, dtype: int64

In [67]:
Data_90_test_df["product_cat"] = Data_90_test_df.product_category_name_english.map(product_categories_map)

Data_90_test_df["product_cat"].value_counts()

product_cat
household                9861
beauty                   8054
electronics              5584
sports_leisure           2840
entertainment            2792
automotive               1890
office                   1319
babies                   1281
construction             1243
miscellaneous            1108
fashion                   990
pet_shop                  843
food_drink                526
books_media               467
commercial_industrial     451
Name: count, dtype: int64

In [68]:
target_features = ["order_status", "payment_type", "product_cat"]

col_trans = ColumnTransformer(transformers=[("cat", OneHotEncoder(sparse_output= False), target_features)], remainder="passthrough"

)

In [69]:
encoded_array_test = col_trans.fit_transform(Data_90_test_df)

In [70]:
encoded_90_test_df = pd.DataFrame(encoded_array, columns= col_trans.get_feature_names_out(Data_90_test_df.columns))

encoded_90_test_df

      cat__order_status_canceled  ... remainder__multiple_payment_methods
0                            0.0  ...                                   0
1                            0.0  ...                                   0
2                            0.0  ...                                   0
3                            0.0  ...                                   0
4                            0.0  ...                                   0
...                          ...  ...                                 ...
14466                        0.0  ...                                   0
14467                        0.0  ...                                   0
14468                        0.0  ...                                   0
14469                        0.0  ...                                   0
14470                        0.0  ...                                   0

[14471 rows x 46 columns]

In [71]:
encoded_90_test_df.columns = encoded_90_test_df.columns.str.replace('remainder__', '')

encoded_90_test_df

      cat__order_status_canceled  ... multiple_payment_methods
0                            0.0  ...                        0
1                            0.0  ...                        0
2                            0.0  ...                        0
3                            0.0  ...                        0
4                            0.0  ...                        0
...                          ...  ...                      ...
14466                        0.0  ...                        0
14467                        0.0  ...                        0
14468                        0.0  ...                        0
14469                        0.0  ...                        0
14470                        0.0  ...                        0

[14471 rows x 46 columns]

In [34]:
Data_90_df["churn_90"].value_counts()

churn_90
0    9276
1    5195
Name: count, dtype: int64

# Train

In [ ]:
X_train = encoded_90_df.drop(columns = ['churn_90', "customer_unique_id", "order_purchase_timestamp", "customer_city", "customer_state", "product_category_name_english",	"is_customer",	"payment_sequential", "payment_installments",	"state_income_level", "price"])

y_train = encoded_90_df['churn_90']

In [74]:
X_test = Data_90_test_df.drop(columns = ['churn_90', "customer_unique_id", "order_purchase_timestamp", "customer_city", "customer_state", "product_category_name_english",	"is_customer",	"payment_sequential", "payment_installments",	"state_income_level"])

y_test = Data_90_test_df['churn_90']

In [75]:
Data_90_test_df["churn_90"].value_counts()

churn_90
1    20447
0    19250
Name: count, dtype: int64

In [76]:
from sklearn.model_selection import train_test_split

X_val, X_test, y_val, y_test  =  train_test_split(X_train, y_train, test_size= 0.5, random_state = 42)

In [77]:
from sklearn.tree import DecisionTreeClassifier

In [78]:
clf = DecisionTreeClassifier(criterion = "gini", max_depth = 5, random_state= 42)


clf.fit(X_train, y_train)

ValueError: Unknown label type: unknown. Maybe you are trying to fit a classifier, which expects discrete classes on a regression target with continuous values.

In [18]:
mis_modelos = [
    ("Tree_gini", DecisionTreeClassifier, {"criterion": "gini", "max_depth": 5, "random_state": 42}),
    ("Tree_entr", DecisionTreeClassifier, {"criterion": "entropy", "max_depth": 5, "random_state": 42})
]

In [20]:
for clf_name, clf_class, hyper_dict in mis_modelos:
    clf = clf_class(**hyper_dict)
    print(clf_name)
    print(clf)

Tree_gini
DecisionTreeClassifier(max_depth=5, random_state=42)
Tree_entr
DecisionTreeClassifier(criterion='entropy', max_depth=5, random_state=42)