In [822]:
import pandas as pd

import numpy as np

import matplotlib.pyplot as plt

import seaborn as sb

In [823]:
Train_90_path = "../Data/Train_test/train_90.csv"

Train_120_path = "../Data/Train_test/train_120.csv"

Train_150_path = "../Data/Train_test/train_150.csv"


# test


Test_90_path = "../Data/churn_test_dataset_90.csv"

Test_120_path = "../Data/churn_test_dataset_120.csv"

Test_150_path = "../Data/churn_test_dataset_150.csv"

In [824]:
Data_train_90_df = pd.read_csv(Train_90_path)

Data_train_120_df = pd.read_csv(Train_120_path) 

Data_train_150_df = pd.read_csv(Train_150_path) 

Data_test_90_df = pd.read_csv(Test_90_path) 

Data_test_120_df = pd.read_csv(Test_120_path) 

Data_test_150_df = pd.read_csv(Test_150_path)

-------
-------

## 90 days train_test dataset

In [825]:
state_count = Data_train_90_df["customer_state"].value_counts()

state_count

customer_state
SP    13327
RJ     4335
MG     3954
RS     1903
PR     1714
SC     1255
BA     1098
GO      702
ES      699
DF      693
PE      544
CE      435
PA      340
MT      319
MA      255
MS      238
PB      186
PI      179
RN      171
AL      127
SE      104
TO       83
RO       83
AM       43
AC       32
AP       26
RR       10
Name: count, dtype: int64

In [826]:
# Income
HIGH_INCOME = ["SP", "RJ", "AM", "SE"]
MID_INCOME = ["PI", "PB", "MS", "ES", "BA", "AL", "PE", "RN", "CE"]
LOW_INCOME = ["RR", "RO", "MT", "GO", "TO", "RS", "SC", "PR", "MA", "MG", "AC", "PA", "AP", "DF"]

prov_income_map = {
    **{i:"high" for i in HIGH_INCOME},
    **{i:"mid" for i in MID_INCOME},
    **{i:"low" for i in LOW_INCOME}
}
prov_income_map

{'SP': 'high',
 'RJ': 'high',
 'AM': 'high',
 'SE': 'high',
 'PI': 'mid',
 'PB': 'mid',
 'MS': 'mid',
 'ES': 'mid',
 'BA': 'mid',
 'AL': 'mid',
 'PE': 'mid',
 'RN': 'mid',
 'CE': 'mid',
 'RR': 'low',
 'RO': 'low',
 'MT': 'low',
 'GO': 'low',
 'TO': 'low',
 'RS': 'low',
 'SC': 'low',
 'PR': 'low',
 'MA': 'low',
 'MG': 'low',
 'AC': 'low',
 'PA': 'low',
 'AP': 'low',
 'DF': 'low'}

In [827]:
Data_train_90_df["state_income_level"] = Data_train_90_df.customer_state.map(prov_income_map)

Data_train_90_df["state_income_level_high"] = (Data_train_90_df["state_income_level"] == "high").astype(int)
Data_train_90_df["state_income_level_mid"] = (Data_train_90_df["state_income_level"] == "mid").astype(int)
Data_train_90_df["state_income_level_low"] = (Data_train_90_df["state_income_level"] == "low").astype(int)

Data_train_90_df

,customer_unique_id,price,freight_ratio,payment_value,dates_diff,review_score,customer_city,customer_state,order_status,payment_sequential,payment_type,payment_installments,product_cat,churn_90,state_income_level,state_income_level_high,state_income_level_mid,state_income_level_low
0,00115fc7123b5310cf6d3a3aa932699e,59.99,0.268711,76.11,-33.0,4.0,brasilia,DF,delivered,1.0,credit_card,1.0,sports_leisure,1,low,0,0,1
1,002b4cd83fabaffaa475f78ea5ef3e08,49.90,0.290982,64.42,-28.0,2.0,sao sebastiao do paraiso,MG,delivered,1.0,credit_card,1.0,fashion,1,low,0,0,1
2,0087eede471173af78d789df249c3a45,126.99,0.189936,151.11,-19.0,5.0,porto alegre,RS,delivered,1.0,boleto,1.0,miscellaneous,1,low,0,0,1
3,008f3d5f45a11059239a5c452cd00006,309.90,0.086028,336.56,-28.0,5.0,sao pedro da agua branca,MA,delivered,1.0,boleto,1.0,beauty,1,low,0,0,1
4,012b8001e47392df808a454083a74b74,65.60,0.497793,197.68,-28.0,5.0,capitao eneas,MG,delivered,1.0,credit_card,1.0,sports_leisure,1,low,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32850,ffe9e41fbd14db4a7361347c56af5447,199.00,0.109950,220.88,-9.0,5.0,vila velha,ES,delivered,1.0,credit_card,2.0,beauty,1,mid,0,1,0
32851,fff7219c86179ca6441b8f37823ba3d3,245.80,0.081367,531.60,-12.0,4.0,cachoeiras de macacu,RJ,delivered,1.0,debit_card,1.0,household,1,high,1,0,0
32852,fffb09418989a0dbff854a28163e47c6,58.00,0.261379,73.16,-23.0,5.0,veranopolis,RS,delivered,1.0,boleto,1.0,beauty,1,low,0,0,1
32853,fffbf87b7a1a6fa8b03f081c5f51a201,149.00,0.122953,167.32,-14.0,5.0,fortaleza,CE,delivered,1.0,credit_card,2.0,unknown,1,mid,0,1,0
32854,fffea47cd6d3cc0a88bd621562a9d061,64.89,0.303437,84.58,-3.0,4.0,feira de santana,BA,delivered,1.0,credit_card,1.0,babies,1,mid,0,1,0

In [828]:


Data_train_90_df["high_review_score"] = (Data_train_90_df["review_score"]>= 4).astype(int)
Data_train_90_df["medium_review_score"] = ((Data_train_90_df["review_score"]< 4) & (Data_train_90_df["review_score"]>= 2)).astype(int)
Data_train_90_df["low_review_score"] = (Data_train_90_df["review_score"]< 2).astype(int)

Data_train_90_df

,customer_unique_id,price,freight_ratio,payment_value,dates_diff,review_score,customer_city,customer_state,order_status,payment_sequential,...,payment_installments,product_cat,churn_90,state_income_level,state_income_level_high,state_income_level_mid,state_income_level_low,high_review_score,medium_review_score,low_review_score
0,00115fc7123b5310cf6d3a3aa932699e,59.99,0.268711,76.11,-33.0,4.0,brasilia,DF,delivered,1.0,...,1.0,sports_leisure,1,low,0,0,1,1,0,0
1,002b4cd83fabaffaa475f78ea5ef3e08,49.90,0.290982,64.42,-28.0,2.0,sao sebastiao do paraiso,MG,delivered,1.0,...,1.0,fashion,1,low,0,0,1,0,1,0
2,0087eede471173af78d789df249c3a45,126.99,0.189936,151.11,-19.0,5.0,porto alegre,RS,delivered,1.0,...,1.0,miscellaneous,1,low,0,0,1,1,0,0
3,008f3d5f45a11059239a5c452cd00006,309.90,0.086028,336.56,-28.0,5.0,sao pedro da agua branca,MA,delivered,1.0,...,1.0,beauty,1,low,0,0,1,1,0,0
4,012b8001e47392df808a454083a74b74,65.60,0.497793,197.68,-28.0,5.0,capitao eneas,MG,delivered,1.0,...,1.0,sports_leisure,1,low,0,0,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32850,ffe9e41fbd14db4a7361347c56af5447,199.00,0.109950,220.88,-9.0,5.0,vila velha,ES,delivered,1.0,...,2.0,beauty,1,mid,0,1,0,1,0,0
32851,fff7219c86179ca6441b8f37823ba3d3,245.80,0.081367,531.60,-12.0,4.0,cachoeiras de macacu,RJ,delivered,1.0,...,1.0,household,1,high,1,0,0,1,0,0
32852,fffb09418989a0dbff854a28163e47c6,58.00,0.261379,73.16,-23.0,5.0,veranopolis,RS,delivered,1.0,...,1.0,beauty,1,low,0,0,1,1,0,0
32853,fffbf87b7a1a6fa8b03f081c5f51a201,149.00,0.122953,167.32,-14.0,5.0,fortaleza,CE,delivered,1.0,...,2.0,unknown,1,mid,0,1,0,1,0,0
32854,fffea47cd6d3cc0a88bd621562a9d061,64.89,0.303437,84.58,-3.0,4.0,feira de santana,BA,delivered,1.0,...,1.0,babies,1,mid,0,1,0,1,0,0

In [829]:
Data_train_90_df["delay"] = (Data_train_90_df["dates_diff"]>0).astype(int)

Data_train_90_df["delay"]

0        0
1        0
2        0
3        0
4        0
        ..
32850    0
32851    0
32852    0
32853    0
32854    0
Name: delay, Length: 32855, dtype: int64

In [830]:
Data_train_90_df["high_payment_value"] = (Data_train_90_df["payment_value"]>172.73).astype(int)

Data_train_90_df["high_payment_value"]

0        0
1        0
2        0
3        1
4        1
        ..
32850    1
32851    1
32852    0
32853    0
32854    0
Name: high_payment_value, Length: 32855, dtype: int64

In [831]:
# One hot encoding for freight_price
Data_train_90_df["expensive_freight"] = (Data_train_90_df["freight_ratio"]>0.15).astype(int)

Data_train_90_df["expensive_freight"]

0        1
1        1
2        1
3        0
4        1
        ..
32850    0
32851    0
32852    1
32853    0
32854    1
Name: expensive_freight, Length: 32855, dtype: int64

In [832]:
# One hot encoding for price

Data_train_90_df["is_high_price"] = (Data_train_90_df["price"]>120.64).astype(int)

Data_train_90_df["is_high_price"]

0        0
1        0
2        1
3        1
4        0
        ..
32850    1
32851    1
32852    0
32853    1
32854    0
Name: is_high_price, Length: 32855, dtype: int64

In [833]:
Data_train_90_df["beyond_one year"] = (Data_train_90_df["payment_installments"] > 12.0).astype(int)

Data_train_90_df["beyond_one year"]

0        0
1        0
2        0
3        0
4        0
        ..
32850    0
32851    0
32852    0
32853    0
32854    0
Name: beyond_one year, Length: 32855, dtype: int64

In [834]:
Data_train_90_df["multiple_payment_methods"] = (Data_train_90_df["payment_sequential"] > 2.0).astype(int)

Data_train_90_df["multiple_payment_methods"]

0        0
1        0
2        0
3        0
4        0
        ..
32850    0
32851    0
32852    0
32853    0
32854    0
Name: multiple_payment_methods, Length: 32855, dtype: int64

In [835]:
from sklearn.compose import ColumnTransformer

from sklearn.preprocessing import OneHotEncoder

In [836]:
# Create one hot encoding for all non-int features  Logprices?

target_features = ["order_status", "payment_type", "product_cat"]

col_trans = ColumnTransformer(
    transformers=[("cat", OneHotEncoder(sparse_output= False, handle_unknown="ignore"), target_features)], remainder="passthrough"
)
col_trans.fit(Data_train_90_df)

ColumnTransformer(remainder='passthrough',
                  transformers=[('cat',
                                 OneHotEncoder(handle_unknown='ignore',
                                               sparse_output=False),
                                 ['order_status', 'payment_type',
                                  'product_cat'])])

In [837]:
# fit and transform the dataset

encoded_array = col_trans.transform(Data_train_90_df)

In [838]:
encoded_90_df = pd.DataFrame(encoded_array, columns= col_trans.get_feature_names_out(Data_train_90_df.columns))

encoded_90_df

,cat__order_status_approved,cat__order_status_canceled,cat__order_status_delivered,cat__order_status_invoiced,cat__order_status_processing,cat__order_status_shipped,cat__payment_type_boleto,cat__payment_type_credit_card,cat__payment_type_debit_card,cat__payment_type_voucher,...,remainder__state_income_level_low,remainder__high_review_score,remainder__medium_review_score,remainder__low_review_score,remainder__delay,remainder__high_payment_value,remainder__expensive_freight,remainder__is_high_price,remainder__beyond_one year,remainder__multiple_payment_methods
0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1,1,0,0,0,0,1,0,0,0
1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1,0,1,0,0,0,1,0,0,0
2,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1,1,0,0,0,0,1,1,0,0
3,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1,1,0,0,0,1,0,1,0,0
4,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1,1,0,0,0,1,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32850,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0,1,0,0,0,1,0,1,0,0
32851,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0,1,0,0,0,1,0,1,0,0
32852,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1,1,0,0,0,0,1,0,0,0
32853,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0,1,0,0,0,0,0,1,0,0
32854,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0,1,0,0,0,0,1,0,0,0

In [839]:
encoded_90_df.columns = encoded_90_df.columns.str.replace('remainder__', '')

encoded_90_df

,cat__order_status_approved,cat__order_status_canceled,cat__order_status_delivered,cat__order_status_invoiced,cat__order_status_processing,cat__order_status_shipped,cat__payment_type_boleto,cat__payment_type_credit_card,cat__payment_type_debit_card,cat__payment_type_voucher,...,state_income_level_low,high_review_score,medium_review_score,low_review_score,delay,high_payment_value,expensive_freight,is_high_price,beyond_one year,multiple_payment_methods
0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1,1,0,0,0,0,1,0,0,0
1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1,0,1,0,0,0,1,0,0,0
2,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1,1,0,0,0,0,1,1,0,0
3,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1,1,0,0,0,1,0,1,0,0
4,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1,1,0,0,0,1,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32850,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0,1,0,0,0,1,0,1,0,0
32851,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0,1,0,0,0,1,0,1,0,0
32852,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1,1,0,0,0,0,1,0,0,0
32853,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0,1,0,0,0,0,0,1,0,0
32854,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0,1,0,0,0,0,1,0,0,0

beyond one tear= the payment takes more than one year

-----

# Test dataset

In [840]:
Data_test_90_df

,customer_unique_id,price,freight_ratio,payment_value,dates_diff,review_score,customer_city,customer_state,order_status,payment_sequential,payment_type,payment_installments,product_cat,churn_90
0,0004bd2a26a76fe21f786e4fbd80607f,154.00,0.084286,166.98,-12.0,4.0,sao paulo,SP,delivered,1.0,credit_card,8.0,miscellaneous,1
1,00053a61a98854899e70ed204dd4bafe,382.00,0.097330,838.36,-10.0,1.0,curitiba,PR,delivered,1.0,credit_card,3.0,sports_leisure,1
2,0005ef4cd20d2893f0d9fbd94d3c0d97,104.90,0.236988,129.76,31.0,1.0,sao luis,MA,delivered,1.0,credit_card,4.0,sports_leisure,1
3,00090324bbad0e9342388303bb71ba0a,49.95,0.274474,63.66,-8.0,5.0,campinas,SP,delivered,1.0,credit_card,3.0,household,1
4,0010fb34b966d44409382af9e8fd5b77,49.95,0.237237,61.80,2.0,4.0,sao paulo,SP,delivered,1.0,credit_card,6.0,household,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20563,ffe6efca3c7e6a06bad0a6a883280a93,213.90,0.060776,226.90,-9.0,4.0,praia grande,SP,delivered,1.0,credit_card,2.0,beauty,1
20564,ffe9e41fbd14db4a7361347c56af5447,199.00,0.109950,220.88,-9.0,5.0,vila velha,ES,delivered,1.0,credit_card,2.0,beauty,1
20565,ffec10ad4229ba46818560e1c8b40a68,120.00,0.131000,135.72,-10.0,5.0,viana,ES,delivered,1.0,credit_card,3.0,sports_leisure,1
20566,fff1bdd5c5e37ca79dd74deeb91aa5b6,134.90,0.282283,172.98,32.0,1.0,araguaina,TO,delivered,2.0,debit_card,1.0,entertainment,1
20567,fffcc512b7dfecaffd80f13614af1d16,688.00,0.032994,710.70,0.0,1.0,cabo frio,RJ,shipped,1.0,credit_card,3.0,beauty,1

In [841]:
Data_test_90_df["state_income_level"] = Data_test_90_df.customer_state.map(prov_income_map)

Data_test_90_df["state_income_level_high"] = (Data_test_90_df["state_income_level"] == "high").astype(int)
Data_test_90_df["state_income_level_mid"] = (Data_test_90_df["state_income_level"] == "mid").astype(int)
Data_test_90_df["state_income_level_low"] = (Data_test_90_df["state_income_level"] == "low").astype(int)

Data_test_90_df

,customer_unique_id,price,freight_ratio,payment_value,dates_diff,review_score,customer_city,customer_state,order_status,payment_sequential,payment_type,payment_installments,product_cat,churn_90,state_income_level,state_income_level_high,state_income_level_mid,state_income_level_low
0,0004bd2a26a76fe21f786e4fbd80607f,154.00,0.084286,166.98,-12.0,4.0,sao paulo,SP,delivered,1.0,credit_card,8.0,miscellaneous,1,high,1,0,0
1,00053a61a98854899e70ed204dd4bafe,382.00,0.097330,838.36,-10.0,1.0,curitiba,PR,delivered,1.0,credit_card,3.0,sports_leisure,1,low,0,0,1
2,0005ef4cd20d2893f0d9fbd94d3c0d97,104.90,0.236988,129.76,31.0,1.0,sao luis,MA,delivered,1.0,credit_card,4.0,sports_leisure,1,low,0,0,1
3,00090324bbad0e9342388303bb71ba0a,49.95,0.274474,63.66,-8.0,5.0,campinas,SP,delivered,1.0,credit_card,3.0,household,1,high,1,0,0
4,0010fb34b966d44409382af9e8fd5b77,49.95,0.237237,61.80,2.0,4.0,sao paulo,SP,delivered,1.0,credit_card,6.0,household,1,high,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20563,ffe6efca3c7e6a06bad0a6a883280a93,213.90,0.060776,226.90,-9.0,4.0,praia grande,SP,delivered,1.0,credit_card,2.0,beauty,1,high,1,0,0
20564,ffe9e41fbd14db4a7361347c56af5447,199.00,0.109950,220.88,-9.0,5.0,vila velha,ES,delivered,1.0,credit_card,2.0,beauty,1,mid,0,1,0
20565,ffec10ad4229ba46818560e1c8b40a68,120.00,0.131000,135.72,-10.0,5.0,viana,ES,delivered,1.0,credit_card,3.0,sports_leisure,1,mid,0,1,0
20566,fff1bdd5c5e37ca79dd74deeb91aa5b6,134.90,0.282283,172.98,32.0,1.0,araguaina,TO,delivered,2.0,debit_card,1.0,entertainment,1,low,0,0,1
20567,fffcc512b7dfecaffd80f13614af1d16,688.00,0.032994,710.70,0.0,1.0,cabo frio,RJ,shipped,1.0,credit_card,3.0,beauty,1,high,1,0,0

In [842]:
Data_test_90_df["high_review_score"] = (Data_test_90_df["review_score"]>= 4).astype(int)
Data_test_90_df["medium_review_score"] = ((Data_test_90_df["review_score"]< 4) & (Data_test_90_df["review_score"]>= 2)).astype(int)
Data_test_90_df["low_review_score"] = (Data_test_90_df["review_score"]< 2).astype(int)

Data_test_90_df

,customer_unique_id,price,freight_ratio,payment_value,dates_diff,review_score,customer_city,customer_state,order_status,payment_sequential,...,payment_installments,product_cat,churn_90,state_income_level,state_income_level_high,state_income_level_mid,state_income_level_low,high_review_score,medium_review_score,low_review_score
0,0004bd2a26a76fe21f786e4fbd80607f,154.00,0.084286,166.98,-12.0,4.0,sao paulo,SP,delivered,1.0,...,8.0,miscellaneous,1,high,1,0,0,1,0,0
1,00053a61a98854899e70ed204dd4bafe,382.00,0.097330,838.36,-10.0,1.0,curitiba,PR,delivered,1.0,...,3.0,sports_leisure,1,low,0,0,1,0,0,1
2,0005ef4cd20d2893f0d9fbd94d3c0d97,104.90,0.236988,129.76,31.0,1.0,sao luis,MA,delivered,1.0,...,4.0,sports_leisure,1,low,0,0,1,0,0,1
3,00090324bbad0e9342388303bb71ba0a,49.95,0.274474,63.66,-8.0,5.0,campinas,SP,delivered,1.0,...,3.0,household,1,high,1,0,0,1,0,0
4,0010fb34b966d44409382af9e8fd5b77,49.95,0.237237,61.80,2.0,4.0,sao paulo,SP,delivered,1.0,...,6.0,household,1,high,1,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20563,ffe6efca3c7e6a06bad0a6a883280a93,213.90,0.060776,226.90,-9.0,4.0,praia grande,SP,delivered,1.0,...,2.0,beauty,1,high,1,0,0,1,0,0
20564,ffe9e41fbd14db4a7361347c56af5447,199.00,0.109950,220.88,-9.0,5.0,vila velha,ES,delivered,1.0,...,2.0,beauty,1,mid,0,1,0,1,0,0
20565,ffec10ad4229ba46818560e1c8b40a68,120.00,0.131000,135.72,-10.0,5.0,viana,ES,delivered,1.0,...,3.0,sports_leisure,1,mid,0,1,0,1,0,0
20566,fff1bdd5c5e37ca79dd74deeb91aa5b6,134.90,0.282283,172.98,32.0,1.0,araguaina,TO,delivered,2.0,...,1.0,entertainment,1,low,0,0,1,0,0,1
20567,fffcc512b7dfecaffd80f13614af1d16,688.00,0.032994,710.70,0.0,1.0,cabo frio,RJ,shipped,1.0,...,3.0,beauty,1,high,1,0,0,0,0,1

In [843]:
Data_test_90_df["delay"] = (Data_test_90_df["dates_diff"]>0).astype(int)

Data_test_90_df["delay"]

0        0
1        0
2        1
3        0
4        1
        ..
20563    0
20564    0
20565    0
20566    1
20567    0
Name: delay, Length: 20568, dtype: int64

In [844]:
Data_test_90_df["high_payment_value"] = (Data_test_90_df["payment_value"]>172.73).astype(int)

Data_test_90_df["high_payment_value"]

0        0
1        1
2        0
3        0
4        0
        ..
20563    1
20564    1
20565    0
20566    1
20567    1
Name: high_payment_value, Length: 20568, dtype: int64

In [845]:
Data_test_90_df["expensive_freight"] = (Data_test_90_df["freight_ratio"]>0.15).astype(int)

Data_test_90_df["expensive_freight"]

0        0
1        0
2        1
3        1
4        1
        ..
20563    0
20564    0
20565    0
20566    1
20567    0
Name: expensive_freight, Length: 20568, dtype: int64

In [846]:
Data_test_90_df["is_high_price"] = (Data_test_90_df["price"]>120.64).astype(int)

Data_test_90_df["is_high_price"]

0        1
1        1
2        0
3        0
4        0
        ..
20563    1
20564    1
20565    0
20566    1
20567    1
Name: is_high_price, Length: 20568, dtype: int64

In [847]:
Data_test_90_df["beyond_one year"] = (Data_test_90_df["payment_installments"] > 12.0).astype(int)

Data_test_90_df["beyond_one year"]

0        0
1        0
2        0
3        0
4        0
        ..
20563    0
20564    0
20565    0
20566    0
20567    0
Name: beyond_one year, Length: 20568, dtype: int64

In [848]:
Data_test_90_df["multiple_payment_methods"] = (Data_test_90_df["payment_sequential"] > 2.0).astype(int)

Data_test_90_df["multiple_payment_methods"]

0        0
1        0
2        0
3        0
4        0
        ..
20563    0
20564    0
20565    0
20566    0
20567    0
Name: multiple_payment_methods, Length: 20568, dtype: int64

In [849]:
Data_train_90_df["order_status"].value_counts()

order_status
delivered     32081
shipped         358
canceled        176
processing      153
invoiced         86
approved          1
Name: count, dtype: int64

In [850]:
Data_test_90_df["order_status"].value_counts()

order_status
delivered     20098
shipped         278
canceled        123
invoiced         43
processing       26
Name: count, dtype: int64

In [851]:
target_features = ["order_status", "payment_type", "product_cat"]

In [852]:
encoded_array_test = col_trans.transform(Data_test_90_df)

In [853]:
Data_test_90_df.columns

Index(['customer_unique_id', 'price', 'freight_ratio', 'payment_value',
       'dates_diff', 'review_score', 'customer_city', 'customer_state',
       'order_status', 'payment_sequential', 'payment_type',
       'payment_installments', 'product_cat', 'churn_90', 'state_income_level',
       'state_income_level_high', 'state_income_level_mid',
       'state_income_level_low', 'high_review_score', 'medium_review_score',
       'low_review_score', 'delay', 'high_payment_value', 'expensive_freight',
       'is_high_price', 'beyond_one year', 'multiple_payment_methods'],
      dtype='str')

In [854]:
Data_test_90_df.columns

Index(['customer_unique_id', 'price', 'freight_ratio', 'payment_value',
       'dates_diff', 'review_score', 'customer_city', 'customer_state',
       'order_status', 'payment_sequential', 'payment_type',
       'payment_installments', 'product_cat', 'churn_90', 'state_income_level',
       'state_income_level_high', 'state_income_level_mid',
       'state_income_level_low', 'high_review_score', 'medium_review_score',
       'low_review_score', 'delay', 'high_payment_value', 'expensive_freight',
       'is_high_price', 'beyond_one year', 'multiple_payment_methods'],
      dtype='str')

In [855]:
encoded_90_test_df = pd.DataFrame(encoded_array, columns= col_trans.get_feature_names_out(Data_test_90_df.columns))

encoded_90_test_df

,cat__order_status_approved,cat__order_status_canceled,cat__order_status_delivered,cat__order_status_invoiced,cat__order_status_processing,cat__order_status_shipped,cat__payment_type_boleto,cat__payment_type_credit_card,cat__payment_type_debit_card,cat__payment_type_voucher,...,remainder__state_income_level_low,remainder__high_review_score,remainder__medium_review_score,remainder__low_review_score,remainder__delay,remainder__high_payment_value,remainder__expensive_freight,remainder__is_high_price,remainder__beyond_one year,remainder__multiple_payment_methods
0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1,1,0,0,0,0,1,0,0,0
1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1,0,1,0,0,0,1,0,0,0
2,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1,1,0,0,0,0,1,1,0,0
3,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1,1,0,0,0,1,0,1,0,0
4,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1,1,0,0,0,1,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32850,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0,1,0,0,0,1,0,1,0,0
32851,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0,1,0,0,0,1,0,1,0,0
32852,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1,1,0,0,0,0,1,0,0,0
32853,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0,1,0,0,0,0,0,1,0,0
32854,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0,1,0,0,0,0,1,0,0,0

In [856]:
encoded_90_test_df.columns = encoded_90_test_df.columns.str.replace('remainder__', '')

encoded_90_test_df

,cat__order_status_approved,cat__order_status_canceled,cat__order_status_delivered,cat__order_status_invoiced,cat__order_status_processing,cat__order_status_shipped,cat__payment_type_boleto,cat__payment_type_credit_card,cat__payment_type_debit_card,cat__payment_type_voucher,...,state_income_level_low,high_review_score,medium_review_score,low_review_score,delay,high_payment_value,expensive_freight,is_high_price,beyond_one year,multiple_payment_methods
0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1,1,0,0,0,0,1,0,0,0
1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1,0,1,0,0,0,1,0,0,0
2,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1,1,0,0,0,0,1,1,0,0
3,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1,1,0,0,0,1,0,1,0,0
4,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1,1,0,0,0,1,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32850,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0,1,0,0,0,1,0,1,0,0
32851,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0,1,0,0,0,1,0,1,0,0
32852,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1,1,0,0,0,0,1,0,0,0
32853,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0,1,0,0,0,0,0,1,0,0
32854,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0,1,0,0,0,0,1,0,0,0

In [857]:
Data_test_90_df["churn_90"].value_counts()

churn_90
1    20385
0      183
Name: count, dtype: int64

--------

In [858]:
encoded_90_df["customer_unique_id"]

0        00115fc7123b5310cf6d3a3aa932699e
1        002b4cd83fabaffaa475f78ea5ef3e08
2        0087eede471173af78d789df249c3a45
3        008f3d5f45a11059239a5c452cd00006
4        012b8001e47392df808a454083a74b74
                       ...
32850    ffe9e41fbd14db4a7361347c56af5447
32851    fff7219c86179ca6441b8f37823ba3d3
32852    fffb09418989a0dbff854a28163e47c6
32853    fffbf87b7a1a6fa8b03f081c5f51a201
32854    fffea47cd6d3cc0a88bd621562a9d061
Name: customer_unique_id, Length: 32855, dtype: str

# Train test split

In [859]:
X_train = encoded_90_df.drop(columns = ['churn_90', "customer_unique_id", "customer_city", "customer_state",	"payment_sequential", "payment_installments",	"state_income_level", "price", "freight_ratio", "payment_value", "dates_diff",	"review_score"])

y_train = encoded_90_df['churn_90'].fillna(0).astype(int)

In [860]:
X_valtest = encoded_90_test_df.drop(columns = ['churn_90', "customer_unique_id", "customer_city", "customer_state",	"payment_sequential", "payment_installments",	"state_income_level", "price", "freight_ratio", "payment_value", "dates_diff",	"review_score"])

y_valtest = encoded_90_test_df['churn_90'].fillna(0).astype(int)

In [861]:
X_valtest

,cat__order_status_approved,cat__order_status_canceled,cat__order_status_delivered,cat__order_status_invoiced,cat__order_status_processing,cat__order_status_shipped,cat__payment_type_boleto,cat__payment_type_credit_card,cat__payment_type_debit_card,cat__payment_type_voucher,...,state_income_level_low,high_review_score,medium_review_score,low_review_score,delay,high_payment_value,expensive_freight,is_high_price,beyond_one year,multiple_payment_methods
0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1,1,0,0,0,0,1,0,0,0
1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1,0,1,0,0,0,1,0,0,0
2,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1,1,0,0,0,0,1,1,0,0
3,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1,1,0,0,0,1,0,1,0,0
4,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1,1,0,0,0,1,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32850,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0,1,0,0,0,1,0,1,0,0
32851,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0,1,0,0,0,1,0,1,0,0
32852,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1,1,0,0,0,0,1,0,0,0
32853,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0,1,0,0,0,0,0,1,0,0
32854,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0,1,0,0,0,0,1,0,0,0

In [862]:
y_train

0        1
1        1
2        1
3        1
4        1
        ..
32850    1
32851    1
32852    1
32853    1
32854    1
Name: churn_90, Length: 32855, dtype: int64

In [863]:
from sklearn.model_selection import train_test_split

X_val, X_test, y_val, y_test  =  train_test_split(X_valtest, y_valtest, test_size= 0.5, random_state = 42)

In [864]:
print(X_train.shape)
print(X_valtest.shape)

(32855, 38)
(32855, 38)

-----

# Gini criterion

## Decision tree

In [865]:
from sklearn.tree import DecisionTreeClassifier

In [866]:
clf = DecisionTreeClassifier(criterion = "gini", max_depth = 5000, random_state= 42)


clf.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=5000, random_state=42)

In [867]:
X_train.columns

Index(['cat__order_status_approved', 'cat__order_status_canceled',
       'cat__order_status_delivered', 'cat__order_status_invoiced',
       'cat__order_status_processing', 'cat__order_status_shipped',
       'cat__payment_type_boleto', 'cat__payment_type_credit_card',
       'cat__payment_type_debit_card', 'cat__payment_type_voucher',
       'cat__product_cat_automotive', 'cat__product_cat_babies',
       'cat__product_cat_beauty', 'cat__product_cat_books_media',
       'cat__product_cat_commercial_industrial',
       'cat__product_cat_construction', 'cat__product_cat_electronics',
       'cat__product_cat_entertainment', 'cat__product_cat_fashion',
       'cat__product_cat_food_drink', 'cat__product_cat_household',
       'cat__product_cat_miscellaneous', 'cat__product_cat_office',
       'cat__product_cat_pet_shop', 'cat__product_cat_sports_leisure',
       'cat__product_cat_unknown', 'state_income_level_high',
       'state_income_level_mid', 'state_income_level_low', 'high_review_score',
       'medium_review_score', 'low_review_score', 'delay',
       'high_payment_value', 'expensive_freight', 'is_high_price',
       'beyond_one year', 'multiple_payment_methods'],
      dtype='str')

In [868]:
X_test.columns

Index(['cat__order_status_approved', 'cat__order_status_canceled',
       'cat__order_status_delivered', 'cat__order_status_invoiced',
       'cat__order_status_processing', 'cat__order_status_shipped',
       'cat__payment_type_boleto', 'cat__payment_type_credit_card',
       'cat__payment_type_debit_card', 'cat__payment_type_voucher',
       'cat__product_cat_automotive', 'cat__product_cat_babies',
       'cat__product_cat_beauty', 'cat__product_cat_books_media',
       'cat__product_cat_commercial_industrial',
       'cat__product_cat_construction', 'cat__product_cat_electronics',
       'cat__product_cat_entertainment', 'cat__product_cat_fashion',
       'cat__product_cat_food_drink', 'cat__product_cat_household',
       'cat__product_cat_miscellaneous', 'cat__product_cat_office',
       'cat__product_cat_pet_shop', 'cat__product_cat_sports_leisure',
       'cat__product_cat_unknown', 'state_income_level_high',
       'state_income_level_mid', 'state_income_level_low', 'high_review_score',
       'medium_review_score', 'low_review_score', 'delay',
       'high_payment_value', 'expensive_freight', 'is_high_price',
       'beyond_one year', 'multiple_payment_methods'],
      dtype='str')

In [869]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix

In [870]:
#{0:0.4f} = f means float and you will have until 4 decimals

ds_list = [
    ("Train", X_train, y_train),
    ("Val", X_val, y_val),
    ("Test", X_test, y_test)
]

for ds_name, ds_x, ds_y in ds_list:
    ds_y_pred = clf.predict(ds_x)

    print(ds_name)
    print('Model F1 score with gini index: {0:0.4f}'. format(f1_score(ds_y, ds_y_pred)))
    print('Model accuracy score with gini index: {0:0.4f}'. format(accuracy_score(ds_y, ds_y_pred)))

    cm = confusion_matrix(ds_y, ds_y_pred)
    print(cm)
    print()

Train
Model F1 score with gini index: 0.9953
Model accuracy score with gini index: 0.9907
[[   31   292]
 [   12 32520]]

Val
Model F1 score with gini index: 0.9956
Model accuracy score with gini index: 0.9912
[[   14   141]
 [    4 16268]]

Test
Model F1 score with gini index: 0.9951
Model accuracy score with gini index: 0.9903
[[   17   151]
 [    8 16252]]

-----

# Random Forest

In [871]:
from sklearn.ensemble import RandomForestClassifier


rfcl = RandomForestClassifier(criterion= "gini", n_estimators=300, 
                               random_state=42, 
                               max_features = 'sqrt',
                               n_jobs=-1, verbose = 1)

# Fit on training data
rfcl.fit(X_train, y_train)

[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  34 tasks      | elapsed:    0.4s
[Parallel(n_jobs=-1)]: Done 184 tasks      | elapsed:    2.2s
[Parallel(n_jobs=-1)]: Done 300 out of 300 | elapsed:    3.6s finished

RandomForestClassifier(n_estimators=300, n_jobs=-1, random_state=42, verbose=1)

In [872]:
train_rf_predictions = rfcl.predict(X_train)
train_rf_probs = rfcl.predict_proba(X_train)

rf_predictions = rfcl.predict(X_test)
rf_probs = rfcl.predict_proba(X_test)

[Parallel(n_jobs=8)]: Using backend ThreadingBackend with 8 concurrent workers.
[Parallel(n_jobs=8)]: Done  34 tasks      | elapsed:    0.0s
[Parallel(n_jobs=8)]: Done 184 tasks      | elapsed:    0.2s
[Parallel(n_jobs=8)]: Done 300 out of 300 | elapsed:    0.3s finished
[Parallel(n_jobs=8)]: Using backend ThreadingBackend with 8 concurrent workers.
[Parallel(n_jobs=8)]: Done  34 tasks      | elapsed:    0.0s
[Parallel(n_jobs=8)]: Done 184 tasks      | elapsed:    0.2s
[Parallel(n_jobs=8)]: Done 300 out of 300 | elapsed:    0.3s finished
[Parallel(n_jobs=8)]: Using backend ThreadingBackend with 8 concurrent workers.
[Parallel(n_jobs=8)]: Done  34 tasks      | elapsed:    0.0s
[Parallel(n_jobs=8)]: Done 184 tasks      | elapsed:    0.1s
[Parallel(n_jobs=8)]: Done 300 out of 300 | elapsed:    0.2s finished
[Parallel(n_jobs=8)]: Using backend ThreadingBackend with 8 concurrent workers.
[Parallel(n_jobs=8)]: Done  34 tasks      | elapsed:    0.0s
[Parallel(n_jobs=8)]: Done 184 tasks      | elapsed:    0.1s
[Parallel(n_jobs=8)]: Done 300 out of 300 | elapsed:    0.1s finished

In [873]:
train_rf_probs

array([[0.01043913, 0.98956087],
       [0.        , 1.        ],
       [0.00175757, 0.99824243],
       ...,
       [0.00546157, 0.99453843],
       [0.        , 1.        ],
       [0.        , 1.        ]], shape=(32855, 2))

In [874]:
y_pred = rfcl.predict(X_test)

[Parallel(n_jobs=8)]: Using backend ThreadingBackend with 8 concurrent workers.
[Parallel(n_jobs=8)]: Done  34 tasks      | elapsed:    0.0s
[Parallel(n_jobs=8)]: Done 184 tasks      | elapsed:    0.1s
[Parallel(n_jobs=8)]: Done 300 out of 300 | elapsed:    0.2s finished

In [875]:
from sklearn.metrics import accuracy_score

print('Model accuracy score with 10 decision-trees : {0:0.4f}'. format(accuracy_score(y_test, y_pred)))

Model accuracy score with 10 decision-trees : 0.9905

In [876]:
cm = confusion_matrix(y_test, y_pred)

---

# Entropy criterion

---

# Log loss criteriom

--------
--------

## 120 days train_test dataset

In [877]:
Data_train_120_df["state_income_level"] = Data_train_120_df.customer_state.map(prov_income_map)

Data_train_120_df["state_income_level_high"] = (Data_train_120_df["state_income_level"] == "high").astype(int)
Data_train_120_df["state_income_level_mid"] = (Data_train_120_df["state_income_level"] == "mid").astype(int)
Data_train_120_df["state_income_level_low"] = (Data_train_120_df["state_income_level"] == "low").astype(int)

Data_train_120_df

,customer_unique_id,price,freight_ratio,payment_value,dates_diff,review_score,customer_city,customer_state,order_status,payment_sequential,payment_type,payment_installments,product_cat,churn_120,state_income_level,state_income_level_high,state_income_level_mid,state_income_level_low
0,0000f46a3911fa3c0805444483337064,69.00,0.249565,86.22,-2.0,3.0,sao jose,SC,delivered,1.0,credit_card,8.0,office,1,low,0,0,1
1,0005e1862207bf6ccc02e4228effd9a0,135.00,0.112000,150.12,-28.0,4.0,teresopolis,RJ,delivered,1.0,credit_card,3.0,fashion,1,high,1,0,0
2,00115fc7123b5310cf6d3a3aa932699e,59.99,0.268711,76.11,-33.0,4.0,brasilia,DF,delivered,1.0,credit_card,1.0,sports_leisure,1,low,0,0,1
3,001f3c4211216384d5fe59b041ce1461,24.88,0.440514,35.84,-11.0,3.0,sao paulo,SP,delivered,1.0,credit_card,3.0,household,1,high,1,0,0
4,002043098f10ba39a4600b6c52fbfe3c,176.99,0.343635,237.81,-16.0,4.0,aracaju,SE,delivered,1.0,credit_card,4.0,office,1,high,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23693,ffeefd086fc667aaf6595c8fe3d22d54,55.00,0.144364,62.94,-8.0,4.0,japeri,RJ,delivered,1.0,credit_card,3.0,beauty,1,high,1,0,0
23694,fff1afc79f6b5db1e235a4a6c30ceda7,34.99,0.431552,50.09,-16.0,5.0,erechim,RS,delivered,1.0,credit_card,4.0,beauty,1,low,0,0,1
23695,fff3a9369e4b7102fab406a334a678c3,84.90,0.210130,102.74,-7.0,5.0,brasilia,DF,delivered,1.0,credit_card,2.0,fashion,1,low,0,0,1
23696,fff699c184bcc967d62fa2c6171765f7,39.90,0.378446,55.00,-7.0,4.0,santos,SP,delivered,1.0,boleto,1.0,entertainment,1,high,1,0,0
23697,fffa431dd3fcdefea4b1777d114144f2,64.99,0.249423,81.20,-7.0,5.0,bom jardim,RJ,delivered,1.0,boleto,1.0,entertainment,1,high,1,0,0

In [878]:

Data_train_120_df["high_review_score"] = (Data_train_120_df["review_score"]>= 4).astype(int)
Data_train_120_df["medium_review_score"] = ((Data_train_120_df["review_score"]< 4) & (Data_train_120_df["review_score"]>= 2)).astype(int)
Data_train_120_df["low_review_score"] = (Data_train_120_df["review_score"]< 2).astype(int)

Data_train_120_df

,customer_unique_id,price,freight_ratio,payment_value,dates_diff,review_score,customer_city,customer_state,order_status,payment_sequential,...,payment_installments,product_cat,churn_120,state_income_level,state_income_level_high,state_income_level_mid,state_income_level_low,high_review_score,medium_review_score,low_review_score
0,0000f46a3911fa3c0805444483337064,69.00,0.249565,86.22,-2.0,3.0,sao jose,SC,delivered,1.0,...,8.0,office,1,low,0,0,1,0,1,0
1,0005e1862207bf6ccc02e4228effd9a0,135.00,0.112000,150.12,-28.0,4.0,teresopolis,RJ,delivered,1.0,...,3.0,fashion,1,high,1,0,0,1,0,0
2,00115fc7123b5310cf6d3a3aa932699e,59.99,0.268711,76.11,-33.0,4.0,brasilia,DF,delivered,1.0,...,1.0,sports_leisure,1,low,0,0,1,1,0,0
3,001f3c4211216384d5fe59b041ce1461,24.88,0.440514,35.84,-11.0,3.0,sao paulo,SP,delivered,1.0,...,3.0,household,1,high,1,0,0,0,1,0
4,002043098f10ba39a4600b6c52fbfe3c,176.99,0.343635,237.81,-16.0,4.0,aracaju,SE,delivered,1.0,...,4.0,office,1,high,1,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23693,ffeefd086fc667aaf6595c8fe3d22d54,55.00,0.144364,62.94,-8.0,4.0,japeri,RJ,delivered,1.0,...,3.0,beauty,1,high,1,0,0,1,0,0
23694,fff1afc79f6b5db1e235a4a6c30ceda7,34.99,0.431552,50.09,-16.0,5.0,erechim,RS,delivered,1.0,...,4.0,beauty,1,low,0,0,1,1,0,0
23695,fff3a9369e4b7102fab406a334a678c3,84.90,0.210130,102.74,-7.0,5.0,brasilia,DF,delivered,1.0,...,2.0,fashion,1,low,0,0,1,1,0,0
23696,fff699c184bcc967d62fa2c6171765f7,39.90,0.378446,55.00,-7.0,4.0,santos,SP,delivered,1.0,...,1.0,entertainment,1,high,1,0,0,1,0,0
23697,fffa431dd3fcdefea4b1777d114144f2,64.99,0.249423,81.20,-7.0,5.0,bom jardim,RJ,delivered,1.0,...,1.0,entertainment,1,high,1,0,0,1,0,0

In [879]:
Data_train_120_df["delay"] = (Data_train_120_df["dates_diff"]>0).astype(int)

Data_train_120_df["delay"]

0        0
1        0
2        0
3        0
4        0
        ..
23693    0
23694    0
23695    0
23696    0
23697    0
Name: delay, Length: 23698, dtype: int64

In [880]:
Data_train_120_df["high_payment_value"] = (Data_train_120_df["payment_value"]>172.73).astype(int)

Data_train_120_df["high_payment_value"]

0        0
1        0
2        0
3        0
4        1
        ..
23693    0
23694    0
23695    0
23696    0
23697    0
Name: high_payment_value, Length: 23698, dtype: int64

In [881]:
Data_train_120_df["expensive_freight"] = (Data_train_120_df["freight_ratio"]>0.15).astype(int)

Data_train_120_df["expensive_freight"]

0        1
1        0
2        1
3        1
4        1
        ..
23693    0
23694    1
23695    1
23696    1
23697    1
Name: expensive_freight, Length: 23698, dtype: int64

In [882]:
Data_train_120_df["is_high_price"] = (Data_train_120_df["price"]>120.64).astype(int)

Data_train_120_df["is_high_price"]

0        0
1        1
2        0
3        0
4        1
        ..
23693    0
23694    0
23695    0
23696    0
23697    0
Name: is_high_price, Length: 23698, dtype: int64

In [883]:
Data_train_120_df["beyond_one year"] = (Data_train_120_df["payment_installments"] > 12.0).astype(int)

Data_train_120_df["beyond_one year"]

0        0
1        0
2        0
3        0
4        0
        ..
23693    0
23694    0
23695    0
23696    0
23697    0
Name: beyond_one year, Length: 23698, dtype: int64

In [884]:
Data_train_120_df["multiple_payment_methods"] = (Data_train_120_df["payment_sequential"] > 2.0).astype(int)

Data_train_120_df["multiple_payment_methods"]

0        0
1        0
2        0
3        0
4        0
        ..
23693    0
23694    0
23695    0
23696    0
23697    0
Name: multiple_payment_methods, Length: 23698, dtype: int64

In [885]:
target_features = ["order_status", "payment_type", "product_cat"]

col_trans = ColumnTransformer(
    transformers=[("cat", OneHotEncoder(sparse_output= False, handle_unknown="ignore"), target_features)], remainder="passthrough"
)
col_trans.fit(Data_train_120_df)

ColumnTransformer(remainder='passthrough',
                  transformers=[('cat',
                                 OneHotEncoder(handle_unknown='ignore',
                                               sparse_output=False),
                                 ['order_status', 'payment_type',
                                  'product_cat'])])

In [886]:
encoded_array = col_trans.transform(Data_train_120_df)

In [887]:
encoded_120_df = pd.DataFrame(encoded_array, columns= col_trans.get_feature_names_out(Data_train_120_df.columns))

encoded_120_df

,cat__order_status_approved,cat__order_status_canceled,cat__order_status_delivered,cat__order_status_invoiced,cat__order_status_processing,cat__order_status_shipped,cat__payment_type_boleto,cat__payment_type_credit_card,cat__payment_type_debit_card,cat__payment_type_voucher,...,remainder__state_income_level_low,remainder__high_review_score,remainder__medium_review_score,remainder__low_review_score,remainder__delay,remainder__high_payment_value,remainder__expensive_freight,remainder__is_high_price,remainder__beyond_one year,remainder__multiple_payment_methods
0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1,0,1,0,0,0,1,0,0,0
1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0,1,0,0,0,0,0,1,0,0
2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1,1,0,0,0,0,1,0,0,0
3,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0,0,1,0,0,0,1,0,0,0
4,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0,1,0,0,0,1,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23693,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0,1,0,0,0,0,0,0,0,0
23694,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1,1,0,0,0,0,1,0,0,0
23695,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1,1,0,0,0,0,1,0,0,0
23696,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0,1,0,0,0,0,1,0,0,0
23697,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0,1,0,0,0,0,1,0,0,0

In [888]:
encoded_120_df.columns = encoded_120_df.columns.str.replace('remainder__', '')

encoded_120_df

,cat__order_status_approved,cat__order_status_canceled,cat__order_status_delivered,cat__order_status_invoiced,cat__order_status_processing,cat__order_status_shipped,cat__payment_type_boleto,cat__payment_type_credit_card,cat__payment_type_debit_card,cat__payment_type_voucher,...,state_income_level_low,high_review_score,medium_review_score,low_review_score,delay,high_payment_value,expensive_freight,is_high_price,beyond_one year,multiple_payment_methods
0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1,0,1,0,0,0,1,0,0,0
1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0,1,0,0,0,0,0,1,0,0
2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1,1,0,0,0,0,1,0,0,0
3,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0,0,1,0,0,0,1,0,0,0
4,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0,1,0,0,0,1,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23693,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0,1,0,0,0,0,0,0,0,0
23694,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1,1,0,0,0,0,1,0,0,0
23695,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1,1,0,0,0,0,1,0,0,0
23696,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0,1,0,0,0,0,1,0,0,0
23697,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0,1,0,0,0,0,1,0,0,0

-----

## Test dataset

In [889]:
Data_test_120_df

,customer_unique_id,price,freight_ratio,payment_value,dates_diff,review_score,customer_city,customer_state,order_status,payment_sequential,payment_type,payment_installments,product_cat,churn_120
0,0000366f3b9a7992bf8c76cfdf3221e2,129.90,0.092379,141.90,-5.0,5.0,cajamar,SP,delivered,1.0,credit_card,8.0,household,1
1,0000b849f77a49e4a4ce2b2a4ca5be3f,18.90,0.438624,27.19,-5.0,4.0,osasco,SP,delivered,1.0,credit_card,1.0,beauty,1
2,0004bd2a26a76fe21f786e4fbd80607f,154.00,0.084286,166.98,-12.0,4.0,sao paulo,SP,delivered,1.0,credit_card,8.0,miscellaneous,1
3,00050ab1314c0e55a6ca13cf7181fecf,27.99,0.264023,35.38,-12.0,4.0,campinas,SP,delivered,1.0,boleto,1.0,electronics,1
4,00053a61a98854899e70ed204dd4bafe,382.00,0.097330,838.36,-10.0,1.0,curitiba,PR,delivered,1.0,credit_card,3.0,sports_leisure,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28212,ffeddf8aa7cdecf403e77b2e9a99e2ea,330.00,0.237576,204.20,6.0,2.0,santarem,PA,delivered,2.0,credit_card,5.0,office,1
28213,fff1bdd5c5e37ca79dd74deeb91aa5b6,134.90,0.282283,172.98,32.0,1.0,araguaina,TO,delivered,2.0,debit_card,1.0,entertainment,1
28214,fff2ae16b99c6f3c785f0e052f2a9cfb,129.94,0.546098,200.90,-21.0,5.0,rio de janeiro,RJ,delivered,1.0,credit_card,8.0,office,1
28215,fffcc512b7dfecaffd80f13614af1d16,688.00,0.032994,710.70,0.0,1.0,cabo frio,RJ,shipped,1.0,credit_card,3.0,beauty,1
28216,ffff5962728ec6157033ef9805bacc48,115.00,0.162522,133.69,-14.0,5.0,bom jesus do norte,ES,delivered,1.0,credit_card,5.0,beauty,1

In [890]:
Data_test_120_df["state_income_level"] = Data_test_120_df.customer_state.map(prov_income_map)

Data_test_120_df["state_income_level_high"] = (Data_test_120_df["state_income_level"] == "high").astype(int)
Data_test_120_df["state_income_level_mid"] = (Data_test_120_df["state_income_level"] == "mid").astype(int)
Data_test_120_df["state_income_level_low"] = (Data_test_120_df["state_income_level"] == "low").astype(int)

Data_test_120_df

,customer_unique_id,price,freight_ratio,payment_value,dates_diff,review_score,customer_city,customer_state,order_status,payment_sequential,payment_type,payment_installments,product_cat,churn_120,state_income_level,state_income_level_high,state_income_level_mid,state_income_level_low
0,0000366f3b9a7992bf8c76cfdf3221e2,129.90,0.092379,141.90,-5.0,5.0,cajamar,SP,delivered,1.0,credit_card,8.0,household,1,high,1,0,0
1,0000b849f77a49e4a4ce2b2a4ca5be3f,18.90,0.438624,27.19,-5.0,4.0,osasco,SP,delivered,1.0,credit_card,1.0,beauty,1,high,1,0,0
2,0004bd2a26a76fe21f786e4fbd80607f,154.00,0.084286,166.98,-12.0,4.0,sao paulo,SP,delivered,1.0,credit_card,8.0,miscellaneous,1,high,1,0,0
3,00050ab1314c0e55a6ca13cf7181fecf,27.99,0.264023,35.38,-12.0,4.0,campinas,SP,delivered,1.0,boleto,1.0,electronics,1,high,1,0,0
4,00053a61a98854899e70ed204dd4bafe,382.00,0.097330,838.36,-10.0,1.0,curitiba,PR,delivered,1.0,credit_card,3.0,sports_leisure,1,low,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28212,ffeddf8aa7cdecf403e77b2e9a99e2ea,330.00,0.237576,204.20,6.0,2.0,santarem,PA,delivered,2.0,credit_card,5.0,office,1,low,0,0,1
28213,fff1bdd5c5e37ca79dd74deeb91aa5b6,134.90,0.282283,172.98,32.0,1.0,araguaina,TO,delivered,2.0,debit_card,1.0,entertainment,1,low,0,0,1
28214,fff2ae16b99c6f3c785f0e052f2a9cfb,129.94,0.546098,200.90,-21.0,5.0,rio de janeiro,RJ,delivered,1.0,credit_card,8.0,office,1,high,1,0,0
28215,fffcc512b7dfecaffd80f13614af1d16,688.00,0.032994,710.70,0.0,1.0,cabo frio,RJ,shipped,1.0,credit_card,3.0,beauty,1,high,1,0,0
28216,ffff5962728ec6157033ef9805bacc48,115.00,0.162522,133.69,-14.0,5.0,bom jesus do norte,ES,delivered,1.0,credit_card,5.0,beauty,1,mid,0,1,0

In [891]:
Data_test_120_df["high_review_score"] = (Data_test_120_df["review_score"]>= 4).astype(int)
Data_test_120_df["medium_review_score"] = ((Data_test_120_df["review_score"]< 4) & (Data_test_120_df["review_score"]>= 2)).astype(int)
Data_test_120_df["low_review_score"] = (Data_test_120_df["review_score"]< 2).astype(int)

Data_test_120_df

,customer_unique_id,price,freight_ratio,payment_value,dates_diff,review_score,customer_city,customer_state,order_status,payment_sequential,...,payment_installments,product_cat,churn_120,state_income_level,state_income_level_high,state_income_level_mid,state_income_level_low,high_review_score,medium_review_score,low_review_score
0,0000366f3b9a7992bf8c76cfdf3221e2,129.90,0.092379,141.90,-5.0,5.0,cajamar,SP,delivered,1.0,...,8.0,household,1,high,1,0,0,1,0,0
1,0000b849f77a49e4a4ce2b2a4ca5be3f,18.90,0.438624,27.19,-5.0,4.0,osasco,SP,delivered,1.0,...,1.0,beauty,1,high,1,0,0,1,0,0
2,0004bd2a26a76fe21f786e4fbd80607f,154.00,0.084286,166.98,-12.0,4.0,sao paulo,SP,delivered,1.0,...,8.0,miscellaneous,1,high,1,0,0,1,0,0
3,00050ab1314c0e55a6ca13cf7181fecf,27.99,0.264023,35.38,-12.0,4.0,campinas,SP,delivered,1.0,...,1.0,electronics,1,high,1,0,0,1,0,0
4,00053a61a98854899e70ed204dd4bafe,382.00,0.097330,838.36,-10.0,1.0,curitiba,PR,delivered,1.0,...,3.0,sports_leisure,1,low,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28212,ffeddf8aa7cdecf403e77b2e9a99e2ea,330.00,0.237576,204.20,6.0,2.0,santarem,PA,delivered,2.0,...,5.0,office,1,low,0,0,1,0,1,0
28213,fff1bdd5c5e37ca79dd74deeb91aa5b6,134.90,0.282283,172.98,32.0,1.0,araguaina,TO,delivered,2.0,...,1.0,entertainment,1,low,0,0,1,0,0,1
28214,fff2ae16b99c6f3c785f0e052f2a9cfb,129.94,0.546098,200.90,-21.0,5.0,rio de janeiro,RJ,delivered,1.0,...,8.0,office,1,high,1,0,0,1,0,0
28215,fffcc512b7dfecaffd80f13614af1d16,688.00,0.032994,710.70,0.0,1.0,cabo frio,RJ,shipped,1.0,...,3.0,beauty,1,high,1,0,0,0,0,1
28216,ffff5962728ec6157033ef9805bacc48,115.00,0.162522,133.69,-14.0,5.0,bom jesus do norte,ES,delivered,1.0,...,5.0,beauty,1,mid,0,1,0,1,0,0

In [892]:
Data_test_120_df["delay"] = (Data_test_120_df["dates_diff"]>0).astype(int)

Data_test_120_df["delay"]

0        0
1        0
2        0
3        0
4        0
        ..
28212    1
28213    1
28214    0
28215    0
28216    0
Name: delay, Length: 28217, dtype: int64

In [893]:
Data_test_120_df["high_payment_value"] = (Data_test_120_df["payment_value"]>172.73).astype(int)

Data_test_120_df["high_payment_value"]

0        0
1        0
2        0
3        0
4        1
        ..
28212    1
28213    1
28214    1
28215    1
28216    0
Name: high_payment_value, Length: 28217, dtype: int64

In [894]:
Data_test_120_df["expensive_freight"] = (Data_test_120_df["freight_ratio"]>0.15).astype(int)

Data_test_120_df["expensive_freight"]

0        0
1        1
2        0
3        1
4        0
        ..
28212    1
28213    1
28214    1
28215    0
28216    1
Name: expensive_freight, Length: 28217, dtype: int64

In [895]:
Data_test_120_df["is_high_price"] = (Data_test_120_df["price"]>120.64).astype(int)

Data_test_120_df["is_high_price"]

0        1
1        0
2        1
3        0
4        1
        ..
28212    1
28213    1
28214    1
28215    1
28216    0
Name: is_high_price, Length: 28217, dtype: int64

In [896]:
Data_test_120_df["beyond_one year"] = (Data_test_120_df["payment_installments"] > 12.0).astype(int)

Data_test_120_df["beyond_one year"]

0        0
1        0
2        0
3        0
4        0
        ..
28212    0
28213    0
28214    0
28215    0
28216    0
Name: beyond_one year, Length: 28217, dtype: int64

In [897]:
Data_test_120_df["multiple_payment_methods"] = (Data_test_120_df["payment_sequential"] > 2.0).astype(int)

Data_test_120_df["multiple_payment_methods"]

0        0
1        0
2        0
3        0
4        0
        ..
28212    0
28213    0
28214    0
28215    0
28216    0
Name: multiple_payment_methods, Length: 28217, dtype: int64

In [898]:
encoded_array_test = col_trans.transform(Data_test_120_df)

In [899]:
encoded_120_test_df = pd.DataFrame(encoded_array_test, columns= col_trans.get_feature_names_out(Data_test_120_df.columns))

encoded_120_test_df

,cat__order_status_approved,cat__order_status_canceled,cat__order_status_delivered,cat__order_status_invoiced,cat__order_status_processing,cat__order_status_shipped,cat__payment_type_boleto,cat__payment_type_credit_card,cat__payment_type_debit_card,cat__payment_type_voucher,...,remainder__state_income_level_low,remainder__high_review_score,remainder__medium_review_score,remainder__low_review_score,remainder__delay,remainder__high_payment_value,remainder__expensive_freight,remainder__is_high_price,remainder__beyond_one year,remainder__multiple_payment_methods
0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0,1,0,0,0,0,0,1,0,0
1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0,1,0,0,0,0,1,0,0,0
2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0,1,0,0,0,0,0,1,0,0
3,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0,1,0,0,0,0,1,0,0,0
4,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1,0,0,1,0,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28212,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1,0,1,0,1,1,1,1,0,0
28213,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,1,0,0,1,1,1,1,1,0,0
28214,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0,1,0,0,0,1,1,1,0,0
28215,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0,0,0,1,0,1,0,1,0,0
28216,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0,1,0,0,0,0,1,0,0,0

In [900]:
encoded_120_test_df.columns = encoded_120_test_df.columns.str.replace('remainder__', '')

encoded_120_test_df

,cat__order_status_approved,cat__order_status_canceled,cat__order_status_delivered,cat__order_status_invoiced,cat__order_status_processing,cat__order_status_shipped,cat__payment_type_boleto,cat__payment_type_credit_card,cat__payment_type_debit_card,cat__payment_type_voucher,...,state_income_level_low,high_review_score,medium_review_score,low_review_score,delay,high_payment_value,expensive_freight,is_high_price,beyond_one year,multiple_payment_methods
0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0,1,0,0,0,0,0,1,0,0
1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0,1,0,0,0,0,1,0,0,0
2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0,1,0,0,0,0,0,1,0,0
3,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0,1,0,0,0,0,1,0,0,0
4,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1,0,0,1,0,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28212,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1,0,1,0,1,1,1,1,0,0
28213,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,1,0,0,1,1,1,1,1,0,0
28214,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0,1,0,0,0,1,1,1,0,0
28215,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0,0,0,1,0,1,0,1,0,0
28216,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0,1,0,0,0,0,1,0,0,0

-----

## Train test split

In [901]:
X_train = encoded_120_test_df.drop(columns = ['churn_120', "customer_unique_id",  "customer_city", "customer_state", "payment_sequential", "payment_installments",	"state_income_level", "price", "freight_ratio", "payment_value", "dates_diff",	"review_score"])

y_train = encoded_120_test_df['churn_120'].fillna(0).astype(int)

In [902]:
X_valtest = encoded_120_test_df.drop(columns = ['churn_120', "customer_unique_id", "customer_city", "customer_state", "payment_sequential", "payment_installments",	"state_income_level", "price", "freight_ratio", "payment_value", "dates_diff",	"review_score"])

y_valtest = encoded_120_test_df['churn_120'].fillna(0).astype(int)

In [903]:
from sklearn.model_selection import train_test_split

X_val, X_test, y_val, y_test  =  train_test_split(X_valtest, y_valtest, test_size= 0.5, random_state = 42)

In [904]:
print(X_train.shape)
print(X_valtest.shape)

(28217, 38)
(28217, 38)

In [905]:
X_train.columns

Index(['cat__order_status_approved', 'cat__order_status_canceled',
       'cat__order_status_delivered', 'cat__order_status_invoiced',
       'cat__order_status_processing', 'cat__order_status_shipped',
       'cat__payment_type_boleto', 'cat__payment_type_credit_card',
       'cat__payment_type_debit_card', 'cat__payment_type_voucher',
       'cat__product_cat_automotive', 'cat__product_cat_babies',
       'cat__product_cat_beauty', 'cat__product_cat_books_media',
       'cat__product_cat_commercial_industrial',
       'cat__product_cat_construction', 'cat__product_cat_electronics',
       'cat__product_cat_entertainment', 'cat__product_cat_fashion',
       'cat__product_cat_food_drink', 'cat__product_cat_household',
       'cat__product_cat_miscellaneous', 'cat__product_cat_office',
       'cat__product_cat_pet_shop', 'cat__product_cat_sports_leisure',
       'cat__product_cat_unknown', 'state_income_level_high',
       'state_income_level_mid', 'state_income_level_low', 'high_review_score',
       'medium_review_score', 'low_review_score', 'delay',
       'high_payment_value', 'expensive_freight', 'is_high_price',
       'beyond_one year', 'multiple_payment_methods'],
      dtype='str')

In [906]:
X_valtest.columns

Index(['cat__order_status_approved', 'cat__order_status_canceled',
       'cat__order_status_delivered', 'cat__order_status_invoiced',
       'cat__order_status_processing', 'cat__order_status_shipped',
       'cat__payment_type_boleto', 'cat__payment_type_credit_card',
       'cat__payment_type_debit_card', 'cat__payment_type_voucher',
       'cat__product_cat_automotive', 'cat__product_cat_babies',
       'cat__product_cat_beauty', 'cat__product_cat_books_media',
       'cat__product_cat_commercial_industrial',
       'cat__product_cat_construction', 'cat__product_cat_electronics',
       'cat__product_cat_entertainment', 'cat__product_cat_fashion',
       'cat__product_cat_food_drink', 'cat__product_cat_household',
       'cat__product_cat_miscellaneous', 'cat__product_cat_office',
       'cat__product_cat_pet_shop', 'cat__product_cat_sports_leisure',
       'cat__product_cat_unknown', 'state_income_level_high',
       'state_income_level_mid', 'state_income_level_low', 'high_review_score',
       'medium_review_score', 'low_review_score', 'delay',
       'high_payment_value', 'expensive_freight', 'is_high_price',
       'beyond_one year', 'multiple_payment_methods'],
      dtype='str')

----

# Gini criterion

## Decision Tree

In [907]:
clf = DecisionTreeClassifier(criterion = "gini", max_depth = 5000, random_state= 42)


clf.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=5000, random_state=42)

In [908]:
ds_list = [
    ("Train", X_train, y_train),
    ("Val", X_val, y_val),
    ("Test", X_test, y_test)
]

for ds_name, ds_x, ds_y in ds_list:
    ds_y_pred = clf.predict(ds_x)

    print(ds_name)
    print('Model F1 score with gini index: {0:0.4f}'. format(f1_score(ds_y, ds_y_pred)))
    print('Model accuracy score with gini index: {0:0.4f}'. format(accuracy_score(ds_y, ds_y_pred)))

    cm = confusion_matrix(ds_y, ds_y_pred)
    print(cm)
    print()

Train
Model F1 score with gini index: 0.9959
Model accuracy score with gini index: 0.9918
[[   22   223]
 [    8 27964]]

Val
Model F1 score with gini index: 0.9956
Model accuracy score with gini index: 0.9913
[[   10   119]
 [    4 13975]]

Test
Model F1 score with gini index: 0.9962
Model accuracy score with gini index: 0.9923
[[   12   104]
 [    4 13989]]

-----

# Random Forest

In [909]:
from sklearn.ensemble import RandomForestClassifier


rfcl = RandomForestClassifier(criterion= "gini", n_estimators=300, 
                               random_state=42, 
                               max_features = 'sqrt',
                               n_jobs=-1, verbose = 1)

# Fit on training data
rfcl.fit(X_train, y_train)

[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  34 tasks      | elapsed:    0.3s
[Parallel(n_jobs=-1)]: Done 184 tasks      | elapsed:    1.7s
[Parallel(n_jobs=-1)]: Done 300 out of 300 | elapsed:    2.7s finished

RandomForestClassifier(n_estimators=300, n_jobs=-1, random_state=42, verbose=1)

In [910]:
train_rf_predictions = rfcl.predict(X_train)
train_rf_probs = rfcl.predict_proba(X_train)

rf_predictions = rfcl.predict(X_test)
rf_probs = rfcl.predict_proba(X_test)

[Parallel(n_jobs=8)]: Using backend ThreadingBackend with 8 concurrent workers.
[Parallel(n_jobs=8)]: Done  34 tasks      | elapsed:    0.0s
[Parallel(n_jobs=8)]: Done 184 tasks      | elapsed:    0.1s
[Parallel(n_jobs=8)]: Done 300 out of 300 | elapsed:    0.3s finished
[Parallel(n_jobs=8)]: Using backend ThreadingBackend with 8 concurrent workers.
[Parallel(n_jobs=8)]: Done  34 tasks      | elapsed:    0.0s
[Parallel(n_jobs=8)]: Done 184 tasks      | elapsed:    0.1s
[Parallel(n_jobs=8)]: Done 300 out of 300 | elapsed:    0.3s finished
[Parallel(n_jobs=8)]: Using backend ThreadingBackend with 8 concurrent workers.
[Parallel(n_jobs=8)]: Done  34 tasks      | elapsed:    0.0s
[Parallel(n_jobs=8)]: Done 184 tasks      | elapsed:    0.1s
[Parallel(n_jobs=8)]: Done 300 out of 300 | elapsed:    0.2s finished
[Parallel(n_jobs=8)]: Using backend ThreadingBackend with 8 concurrent workers.
[Parallel(n_jobs=8)]: Done  34 tasks      | elapsed:    0.0s
[Parallel(n_jobs=8)]: Done 184 tasks      | elapsed:    0.1s
[Parallel(n_jobs=8)]: Done 300 out of 300 | elapsed:    0.2s finished

In [911]:
y_pred = rfcl.predict(X_test)

[Parallel(n_jobs=8)]: Using backend ThreadingBackend with 8 concurrent workers.
[Parallel(n_jobs=8)]: Done  34 tasks      | elapsed:    0.0s
[Parallel(n_jobs=8)]: Done 184 tasks      | elapsed:    0.1s
[Parallel(n_jobs=8)]: Done 300 out of 300 | elapsed:    0.2s finished

In [912]:
print('Model accuracy score with 10 decision-trees : {0:0.4f}'. format(accuracy_score(y_test, y_pred)))

Model accuracy score with 10 decision-trees : 0.9923

In [913]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[    7,   109],
       [    0, 13993]])

---

# Entropy Criterion

---

# Log loss Criterion

-----
-----

## 150 days

## 150 days train_test dataset

In [914]:
Data_train_150_df["state_income_level"] = Data_train_150_df.customer_state.map(prov_income_map)

Data_train_150_df["state_income_level_high"] = (Data_train_150_df["state_income_level"] == "high").astype(int)
Data_train_150_df["state_income_level_mid"] = (Data_train_150_df["state_income_level"] == "mid").astype(int)
Data_train_150_df["state_income_level_low"] = (Data_train_150_df["state_income_level"] == "low").astype(int)

Data_train_150_df

,customer_unique_id,price,freight_ratio,payment_value,dates_diff,review_score,customer_city,customer_state,order_status,payment_sequential,payment_type,payment_installments,product_cat,churn_150,state_income_level,state_income_level_high,state_income_level_mid,state_income_level_low
0,0000f46a3911fa3c0805444483337064,69.00,0.249565,86.22,-2.0,3.0,sao jose,SC,delivered,1.0,credit_card,8.0,office,1,low,0,0,1
1,0005e1862207bf6ccc02e4228effd9a0,135.00,0.112000,150.12,-28.0,4.0,teresopolis,RJ,delivered,1.0,credit_card,3.0,fashion,1,high,1,0,0
2,00115fc7123b5310cf6d3a3aa932699e,59.99,0.268711,76.11,-33.0,4.0,brasilia,DF,delivered,1.0,credit_card,1.0,sports_leisure,1,low,0,0,1
3,0011805441c0d1b68b48002f1d005526,269.00,0.104610,297.14,-13.0,3.0,goianesia do para,PA,delivered,1.0,credit_card,10.0,electronics,1,low,0,0,1
4,00191a9719ef48ebb5860b130347bf33,47.90,0.228810,58.86,-19.0,3.0,jarinu,SP,delivered,1.0,credit_card,2.0,household,1,high,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25735,fff1afc79f6b5db1e235a4a6c30ceda7,34.99,0.431552,50.09,-16.0,5.0,erechim,RS,delivered,1.0,credit_card,4.0,beauty,1,low,0,0,1
25736,fff3a9369e4b7102fab406a334a678c3,84.90,0.210130,102.74,-7.0,5.0,brasilia,DF,delivered,1.0,credit_card,2.0,fashion,1,low,0,0,1
25737,fff699c184bcc967d62fa2c6171765f7,39.90,0.378446,55.00,-7.0,4.0,santos,SP,delivered,1.0,boleto,1.0,entertainment,1,high,1,0,0
25738,fffcf5a5ff07b0908bd4e2dbc735a684,1570.00,0.320939,4134.84,-27.0,5.0,sanharo,PE,delivered,1.0,credit_card,10.0,beauty,1,mid,0,1,0
25739,ffffd2657e2aad2907e67c3e9daecbeb,56.99,0.255659,71.56,-16.0,5.0,campo largo,PR,delivered,1.0,credit_card,4.0,beauty,1,low,0,0,1

In [915]:
Data_train_150_df["high_review_score"] = (Data_train_150_df["review_score"]>= 4).astype(int)
Data_train_150_df["medium_review_score"] = ((Data_train_150_df["review_score"]< 4) & (Data_train_150_df["review_score"]>= 2)).astype(int)
Data_train_150_df["low_review_score"] = (Data_train_150_df["review_score"]< 2).astype(int)

Data_train_150_df

,customer_unique_id,price,freight_ratio,payment_value,dates_diff,review_score,customer_city,customer_state,order_status,payment_sequential,...,payment_installments,product_cat,churn_150,state_income_level,state_income_level_high,state_income_level_mid,state_income_level_low,high_review_score,medium_review_score,low_review_score
0,0000f46a3911fa3c0805444483337064,69.00,0.249565,86.22,-2.0,3.0,sao jose,SC,delivered,1.0,...,8.0,office,1,low,0,0,1,0,1,0
1,0005e1862207bf6ccc02e4228effd9a0,135.00,0.112000,150.12,-28.0,4.0,teresopolis,RJ,delivered,1.0,...,3.0,fashion,1,high,1,0,0,1,0,0
2,00115fc7123b5310cf6d3a3aa932699e,59.99,0.268711,76.11,-33.0,4.0,brasilia,DF,delivered,1.0,...,1.0,sports_leisure,1,low,0,0,1,1,0,0
3,0011805441c0d1b68b48002f1d005526,269.00,0.104610,297.14,-13.0,3.0,goianesia do para,PA,delivered,1.0,...,10.0,electronics,1,low,0,0,1,0,1,0
4,00191a9719ef48ebb5860b130347bf33,47.90,0.228810,58.86,-19.0,3.0,jarinu,SP,delivered,1.0,...,2.0,household,1,high,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25735,fff1afc79f6b5db1e235a4a6c30ceda7,34.99,0.431552,50.09,-16.0,5.0,erechim,RS,delivered,1.0,...,4.0,beauty,1,low,0,0,1,1,0,0
25736,fff3a9369e4b7102fab406a334a678c3,84.90,0.210130,102.74,-7.0,5.0,brasilia,DF,delivered,1.0,...,2.0,fashion,1,low,0,0,1,1,0,0
25737,fff699c184bcc967d62fa2c6171765f7,39.90,0.378446,55.00,-7.0,4.0,santos,SP,delivered,1.0,...,1.0,entertainment,1,high,1,0,0,1,0,0
25738,fffcf5a5ff07b0908bd4e2dbc735a684,1570.00,0.320939,4134.84,-27.0,5.0,sanharo,PE,delivered,1.0,...,10.0,beauty,1,mid,0,1,0,1,0,0
25739,ffffd2657e2aad2907e67c3e9daecbeb,56.99,0.255659,71.56,-16.0,5.0,campo largo,PR,delivered,1.0,...,4.0,beauty,1,low,0,0,1,1,0,0

In [916]:
Data_train_150_df["delay"] = (Data_train_150_df["dates_diff"]>0).astype(int)

Data_train_150_df["delay"]

0        0
1        0
2        0
3        0
4        0
        ..
25735    0
25736    0
25737    0
25738    0
25739    0
Name: delay, Length: 25740, dtype: int64

In [917]:
Data_train_150_df["high_payment_value"] = (Data_train_150_df["payment_value"]>172.73).astype(int)

Data_train_150_df["high_payment_value"]

0        0
1        0
2        0
3        1
4        0
        ..
25735    0
25736    0
25737    0
25738    1
25739    0
Name: high_payment_value, Length: 25740, dtype: int64

In [918]:
Data_train_150_df["expensive_freight"] = (Data_train_150_df["freight_ratio"]>0.15).astype(int)

Data_train_150_df["expensive_freight"]

0        1
1        0
2        1
3        0
4        1
        ..
25735    1
25736    1
25737    1
25738    1
25739    1
Name: expensive_freight, Length: 25740, dtype: int64

In [919]:
Data_train_150_df["is_high_price"] = (Data_train_150_df["price"]>120.64).astype(int)

Data_train_150_df["is_high_price"]

0        0
1        1
2        0
3        1
4        0
        ..
25735    0
25736    0
25737    0
25738    1
25739    0
Name: is_high_price, Length: 25740, dtype: int64

In [920]:
Data_train_150_df["beyond_one year"] = (Data_train_150_df["payment_installments"] > 12.0).astype(int)

Data_train_150_df["beyond_one year"]

0        0
1        0
2        0
3        0
4        0
        ..
25735    0
25736    0
25737    0
25738    0
25739    0
Name: beyond_one year, Length: 25740, dtype: int64

In [921]:
Data_train_150_df["multiple_payment_methods"] = (Data_train_150_df["payment_sequential"] > 2.0).astype(int)

Data_train_150_df["multiple_payment_methods"]

0        0
1        0
2        0
3        0
4        0
        ..
25735    0
25736    0
25737    0
25738    0
25739    0
Name: multiple_payment_methods, Length: 25740, dtype: int64

In [922]:
target_features = ["order_status", "payment_type", "product_cat"]

col_trans = ColumnTransformer(
    transformers=[("cat", OneHotEncoder(sparse_output= False, handle_unknown="ignore"), target_features)], remainder="passthrough"
)
col_trans.fit(Data_train_150_df)

ColumnTransformer(remainder='passthrough',
                  transformers=[('cat',
                                 OneHotEncoder(handle_unknown='ignore',
                                               sparse_output=False),
                                 ['order_status', 'payment_type',
                                  'product_cat'])])

In [923]:
encoded_array = col_trans.transform(Data_train_150_df)

In [924]:
encoded_150_df = pd.DataFrame(encoded_array, columns= col_trans.get_feature_names_out(Data_train_150_df.columns))

encoded_150_df

,cat__order_status_approved,cat__order_status_canceled,cat__order_status_delivered,cat__order_status_invoiced,cat__order_status_processing,cat__order_status_shipped,cat__payment_type_boleto,cat__payment_type_credit_card,cat__payment_type_debit_card,cat__payment_type_voucher,...,remainder__state_income_level_low,remainder__high_review_score,remainder__medium_review_score,remainder__low_review_score,remainder__delay,remainder__high_payment_value,remainder__expensive_freight,remainder__is_high_price,remainder__beyond_one year,remainder__multiple_payment_methods
0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1,0,1,0,0,0,1,0,0,0
1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0,1,0,0,0,0,0,1,0,0
2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1,1,0,0,0,0,1,0,0,0
3,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1,0,1,0,0,1,0,1,0,0
4,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0,0,1,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25735,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1,1,0,0,0,0,1,0,0,0
25736,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1,1,0,0,0,0,1,0,0,0
25737,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0,1,0,0,0,0,1,0,0,0
25738,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0,1,0,0,0,1,1,1,0,0
25739,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1,1,0,0,0,0,1,0,0,0

In [925]:
encoded_150_df.columns = encoded_150_df.columns.str.replace('remainder__', '')

encoded_150_df

,cat__order_status_approved,cat__order_status_canceled,cat__order_status_delivered,cat__order_status_invoiced,cat__order_status_processing,cat__order_status_shipped,cat__payment_type_boleto,cat__payment_type_credit_card,cat__payment_type_debit_card,cat__payment_type_voucher,...,state_income_level_low,high_review_score,medium_review_score,low_review_score,delay,high_payment_value,expensive_freight,is_high_price,beyond_one year,multiple_payment_methods
0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1,0,1,0,0,0,1,0,0,0
1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0,1,0,0,0,0,0,1,0,0
2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1,1,0,0,0,0,1,0,0,0
3,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1,0,1,0,0,1,0,1,0,0
4,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0,0,1,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25735,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1,1,0,0,0,0,1,0,0,0
25736,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1,1,0,0,0,0,1,0,0,0
25737,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0,1,0,0,0,0,1,0,0,0
25738,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0,1,0,0,0,1,1,1,0,0
25739,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1,1,0,0,0,0,1,0,0,0

----

## Test dataset

In [926]:
Data_test_150_df

,customer_unique_id,price,freight_ratio,payment_value,dates_diff,review_score,customer_city,customer_state,order_status,payment_sequential,payment_type,payment_installments,product_cat,churn_150
0,0000366f3b9a7992bf8c76cfdf3221e2,129.90,0.092379,141.90,-5.0,5.0,cajamar,SP,delivered,1.0,credit_card,8.0,household,1
1,0000b849f77a49e4a4ce2b2a4ca5be3f,18.90,0.438624,27.19,-5.0,4.0,osasco,SP,delivered,1.0,credit_card,1.0,beauty,1
2,0004bd2a26a76fe21f786e4fbd80607f,154.00,0.084286,166.98,-12.0,4.0,sao paulo,SP,delivered,1.0,credit_card,8.0,miscellaneous,1
3,00050ab1314c0e55a6ca13cf7181fecf,27.99,0.264023,35.38,-12.0,4.0,campinas,SP,delivered,1.0,boleto,1.0,electronics,1
4,00053a61a98854899e70ed204dd4bafe,382.00,0.097330,838.36,-10.0,1.0,curitiba,PR,delivered,1.0,credit_card,3.0,sports_leisure,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33672,ffeddf8aa7cdecf403e77b2e9a99e2ea,330.00,0.237576,204.20,6.0,2.0,santarem,PA,delivered,2.0,credit_card,5.0,office,1
33673,fff1bdd5c5e37ca79dd74deeb91aa5b6,134.90,0.282283,172.98,32.0,1.0,araguaina,TO,delivered,2.0,debit_card,1.0,entertainment,1
33674,fff2ae16b99c6f3c785f0e052f2a9cfb,129.94,0.546098,200.90,-21.0,5.0,rio de janeiro,RJ,delivered,1.0,credit_card,8.0,office,1
33675,fffcc512b7dfecaffd80f13614af1d16,688.00,0.032994,710.70,0.0,1.0,cabo frio,RJ,shipped,1.0,credit_card,3.0,beauty,1
33676,ffff5962728ec6157033ef9805bacc48,115.00,0.162522,133.69,-14.0,5.0,bom jesus do norte,ES,delivered,1.0,credit_card,5.0,beauty,1

In [927]:
Data_test_150_df["state_income_level"] = Data_test_150_df.customer_state.map(prov_income_map)

Data_test_150_df["state_income_level_high"] = (Data_test_150_df["state_income_level"] == "high").astype(int)
Data_test_150_df["state_income_level_mid"] = (Data_test_150_df["state_income_level"] == "mid").astype(int)
Data_test_150_df["state_income_level_low"] = (Data_test_150_df["state_income_level"] == "low").astype(int)

Data_test_150_df

,customer_unique_id,price,freight_ratio,payment_value,dates_diff,review_score,customer_city,customer_state,order_status,payment_sequential,payment_type,payment_installments,product_cat,churn_150,state_income_level,state_income_level_high,state_income_level_mid,state_income_level_low
0,0000366f3b9a7992bf8c76cfdf3221e2,129.90,0.092379,141.90,-5.0,5.0,cajamar,SP,delivered,1.0,credit_card,8.0,household,1,high,1,0,0
1,0000b849f77a49e4a4ce2b2a4ca5be3f,18.90,0.438624,27.19,-5.0,4.0,osasco,SP,delivered,1.0,credit_card,1.0,beauty,1,high,1,0,0
2,0004bd2a26a76fe21f786e4fbd80607f,154.00,0.084286,166.98,-12.0,4.0,sao paulo,SP,delivered,1.0,credit_card,8.0,miscellaneous,1,high,1,0,0
3,00050ab1314c0e55a6ca13cf7181fecf,27.99,0.264023,35.38,-12.0,4.0,campinas,SP,delivered,1.0,boleto,1.0,electronics,1,high,1,0,0
4,00053a61a98854899e70ed204dd4bafe,382.00,0.097330,838.36,-10.0,1.0,curitiba,PR,delivered,1.0,credit_card,3.0,sports_leisure,1,low,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33672,ffeddf8aa7cdecf403e77b2e9a99e2ea,330.00,0.237576,204.20,6.0,2.0,santarem,PA,delivered,2.0,credit_card,5.0,office,1,low,0,0,1
33673,fff1bdd5c5e37ca79dd74deeb91aa5b6,134.90,0.282283,172.98,32.0,1.0,araguaina,TO,delivered,2.0,debit_card,1.0,entertainment,1,low,0,0,1
33674,fff2ae16b99c6f3c785f0e052f2a9cfb,129.94,0.546098,200.90,-21.0,5.0,rio de janeiro,RJ,delivered,1.0,credit_card,8.0,office,1,high,1,0,0
33675,fffcc512b7dfecaffd80f13614af1d16,688.00,0.032994,710.70,0.0,1.0,cabo frio,RJ,shipped,1.0,credit_card,3.0,beauty,1,high,1,0,0
33676,ffff5962728ec6157033ef9805bacc48,115.00,0.162522,133.69,-14.0,5.0,bom jesus do norte,ES,delivered,1.0,credit_card,5.0,beauty,1,mid,0,1,0

In [928]:
Data_test_150_df["high_review_score"] = (Data_test_150_df["review_score"]>= 4).astype(int)
Data_test_150_df["medium_review_score"] = ((Data_test_150_df["review_score"]< 4) & (Data_test_150_df["review_score"]>= 2)).astype(int)
Data_test_150_df["low_review_score"] = (Data_test_150_df["review_score"]< 2).astype(int)

Data_test_150_df

,customer_unique_id,price,freight_ratio,payment_value,dates_diff,review_score,customer_city,customer_state,order_status,payment_sequential,...,payment_installments,product_cat,churn_150,state_income_level,state_income_level_high,state_income_level_mid,state_income_level_low,high_review_score,medium_review_score,low_review_score
0,0000366f3b9a7992bf8c76cfdf3221e2,129.90,0.092379,141.90,-5.0,5.0,cajamar,SP,delivered,1.0,...,8.0,household,1,high,1,0,0,1,0,0
1,0000b849f77a49e4a4ce2b2a4ca5be3f,18.90,0.438624,27.19,-5.0,4.0,osasco,SP,delivered,1.0,...,1.0,beauty,1,high,1,0,0,1,0,0
2,0004bd2a26a76fe21f786e4fbd80607f,154.00,0.084286,166.98,-12.0,4.0,sao paulo,SP,delivered,1.0,...,8.0,miscellaneous,1,high,1,0,0,1,0,0
3,00050ab1314c0e55a6ca13cf7181fecf,27.99,0.264023,35.38,-12.0,4.0,campinas,SP,delivered,1.0,...,1.0,electronics,1,high,1,0,0,1,0,0
4,00053a61a98854899e70ed204dd4bafe,382.00,0.097330,838.36,-10.0,1.0,curitiba,PR,delivered,1.0,...,3.0,sports_leisure,1,low,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33672,ffeddf8aa7cdecf403e77b2e9a99e2ea,330.00,0.237576,204.20,6.0,2.0,santarem,PA,delivered,2.0,...,5.0,office,1,low,0,0,1,0,1,0
33673,fff1bdd5c5e37ca79dd74deeb91aa5b6,134.90,0.282283,172.98,32.0,1.0,araguaina,TO,delivered,2.0,...,1.0,entertainment,1,low,0,0,1,0,0,1
33674,fff2ae16b99c6f3c785f0e052f2a9cfb,129.94,0.546098,200.90,-21.0,5.0,rio de janeiro,RJ,delivered,1.0,...,8.0,office,1,high,1,0,0,1,0,0
33675,fffcc512b7dfecaffd80f13614af1d16,688.00,0.032994,710.70,0.0,1.0,cabo frio,RJ,shipped,1.0,...,3.0,beauty,1,high,1,0,0,0,0,1
33676,ffff5962728ec6157033ef9805bacc48,115.00,0.162522,133.69,-14.0,5.0,bom jesus do norte,ES,delivered,1.0,...,5.0,beauty,1,mid,0,1,0,1,0,0

In [929]:
Data_test_150_df["delay"] = (Data_test_150_df["dates_diff"]>0).astype(int)

Data_test_150_df["delay"]

0        0
1        0
2        0
3        0
4        0
        ..
33672    1
33673    1
33674    0
33675    0
33676    0
Name: delay, Length: 33677, dtype: int64

In [930]:
Data_test_150_df["high_payment_value"] = (Data_test_150_df["payment_value"]>172.73).astype(int)

Data_test_150_df["high_payment_value"]

0        0
1        0
2        0
3        0
4        1
        ..
33672    1
33673    1
33674    1
33675    1
33676    0
Name: high_payment_value, Length: 33677, dtype: int64

In [931]:
Data_test_150_df["expensive_freight"] = (Data_test_150_df["freight_ratio"]>20.03).astype(int)

Data_test_150_df["expensive_freight"]

0        0
1        0
2        0
3        0
4        0
        ..
33672    0
33673    0
33674    0
33675    0
33676    0
Name: expensive_freight, Length: 33677, dtype: int64

In [932]:
Data_test_150_df["is_high_price"] = (Data_test_150_df["price"]>120.64).astype(int)

Data_test_150_df["is_high_price"]

0        1
1        0
2        1
3        0
4        1
        ..
33672    1
33673    1
33674    1
33675    1
33676    0
Name: is_high_price, Length: 33677, dtype: int64

In [933]:
Data_test_150_df["beyond_one year"] = (Data_test_150_df["payment_installments"] > 12.0).astype(int)

Data_test_150_df["beyond_one year"]

0        0
1        0
2        0
3        0
4        0
        ..
33672    0
33673    0
33674    0
33675    0
33676    0
Name: beyond_one year, Length: 33677, dtype: int64

In [934]:
Data_test_150_df["multiple_payment_methods"] = (Data_test_150_df["payment_sequential"] > 2.0).astype(int)

Data_test_150_df["multiple_payment_methods"]

0        0
1        0
2        0
3        0
4        0
        ..
33672    0
33673    0
33674    0
33675    0
33676    0
Name: multiple_payment_methods, Length: 33677, dtype: int64

In [935]:
encoded_array_test = col_trans.transform(Data_test_150_df)

In [936]:
encoded_150_test_df = pd.DataFrame(encoded_array_test, columns= col_trans.get_feature_names_out(Data_test_150_df.columns))

encoded_150_test_df

,cat__order_status_approved,cat__order_status_canceled,cat__order_status_delivered,cat__order_status_invoiced,cat__order_status_processing,cat__order_status_shipped,cat__payment_type_boleto,cat__payment_type_credit_card,cat__payment_type_debit_card,cat__payment_type_voucher,...,remainder__state_income_level_low,remainder__high_review_score,remainder__medium_review_score,remainder__low_review_score,remainder__delay,remainder__high_payment_value,remainder__expensive_freight,remainder__is_high_price,remainder__beyond_one year,remainder__multiple_payment_methods
0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0,1,0,0,0,0,0,1,0,0
1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0,1,0,0,0,0,0,0,0,0
2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0,1,0,0,0,0,0,1,0,0
3,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0,1,0,0,0,0,0,0,0,0
4,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1,0,0,1,0,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33672,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1,0,1,0,1,1,0,1,0,0
33673,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,1,0,0,1,1,1,0,1,0,0
33674,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0,1,0,0,0,1,0,1,0,0
33675,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0,0,0,1,0,1,0,1,0,0
33676,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0,1,0,0,0,0,0,0,0,0

In [937]:
encoded_150_test_df.columns = encoded_150_test_df.columns.str.replace('remainder__', '')

encoded_150_test_df

,cat__order_status_approved,cat__order_status_canceled,cat__order_status_delivered,cat__order_status_invoiced,cat__order_status_processing,cat__order_status_shipped,cat__payment_type_boleto,cat__payment_type_credit_card,cat__payment_type_debit_card,cat__payment_type_voucher,...,state_income_level_low,high_review_score,medium_review_score,low_review_score,delay,high_payment_value,expensive_freight,is_high_price,beyond_one year,multiple_payment_methods
0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0,1,0,0,0,0,0,1,0,0
1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0,1,0,0,0,0,0,0,0,0
2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0,1,0,0,0,0,0,1,0,0
3,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0,1,0,0,0,0,0,0,0,0
4,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1,0,0,1,0,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33672,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1,0,1,0,1,1,0,1,0,0
33673,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,1,0,0,1,1,1,0,1,0,0
33674,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0,1,0,0,0,1,0,1,0,0
33675,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0,0,0,1,0,1,0,1,0,0
33676,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0,1,0,0,0,0,0,0,0,0

-----

## Train test split

In [938]:
X_train = encoded_150_df.drop(columns = ['churn_150', "customer_unique_id", "customer_city", "customer_state",	"payment_sequential", "payment_installments",	"state_income_level", "price", "freight_ratio", "payment_value", "dates_diff",	"review_score"])

y_train = encoded_150_df['churn_150'].fillna(0).astype(int)

In [939]:
X_valtest = encoded_150_test_df.drop(columns = ['churn_150', "customer_unique_id", "customer_city", "customer_state",	"payment_sequential", "payment_installments",	"state_income_level", "price", "freight_ratio", "payment_value", "dates_diff",	"review_score"])

y_valtest = encoded_150_test_df['churn_150'].fillna(0).astype(int)

In [940]:
X_val, X_test, y_val, y_test  =  train_test_split(X_valtest, y_valtest, test_size= 0.5, random_state = 42)

In [941]:
print(X_train.shape)
print(X_valtest.shape)

(25740, 38)
(33677, 38)

In [942]:
X_train.columns

Index(['cat__order_status_approved', 'cat__order_status_canceled',
       'cat__order_status_delivered', 'cat__order_status_invoiced',
       'cat__order_status_processing', 'cat__order_status_shipped',
       'cat__payment_type_boleto', 'cat__payment_type_credit_card',
       'cat__payment_type_debit_card', 'cat__payment_type_voucher',
       'cat__product_cat_automotive', 'cat__product_cat_babies',
       'cat__product_cat_beauty', 'cat__product_cat_books_media',
       'cat__product_cat_commercial_industrial',
       'cat__product_cat_construction', 'cat__product_cat_electronics',
       'cat__product_cat_entertainment', 'cat__product_cat_fashion',
       'cat__product_cat_food_drink', 'cat__product_cat_household',
       'cat__product_cat_miscellaneous', 'cat__product_cat_office',
       'cat__product_cat_pet_shop', 'cat__product_cat_sports_leisure',
       'cat__product_cat_unknown', 'state_income_level_high',
       'state_income_level_mid', 'state_income_level_low', 'high_review_score',
       'medium_review_score', 'low_review_score', 'delay',
       'high_payment_value', 'expensive_freight', 'is_high_price',
       'beyond_one year', 'multiple_payment_methods'],
      dtype='str')

----

# Gini Criterion

## Decision Tree

In [943]:
clf = DecisionTreeClassifier(criterion = "gini", max_depth = 5000, random_state= 42)


clf.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=5000, random_state=42)

In [944]:
ds_list = [
    ("Train", X_train, y_train),
    ("Val", X_val, y_val),
    ("Test", X_test, y_test)
]

for ds_name, ds_x, ds_y in ds_list:
    ds_y_pred = clf.predict(ds_x)

    print(ds_name)
    print('Model F1 score with gini index: {0:0.4f}'. format(f1_score(ds_y, ds_y_pred)))
    print('Model accuracy score with gini index: {0:0.4f}'. format(accuracy_score(ds_y, ds_y_pred)))

    cm = confusion_matrix(ds_y, ds_y_pred)
    print(cm)
    print()

Train
Model F1 score with gini index: 0.9930
Model accuracy score with gini index: 0.9861
[[   27   351]
 [    8 25354]]

Val
Model F1 score with gini index: 0.9936
Model accuracy score with gini index: 0.9872
[[    2    94]
 [  121 16621]]

Test
Model F1 score with gini index: 0.9921
Model accuracy score with gini index: 0.9843
[[    1   101]
 [  164 16573]]

-----

# Random Forest

In [945]:
rfcl = RandomForestClassifier(criterion= "gini", n_estimators=300, 
                               random_state=42, 
                               max_features = 'sqrt',
                               n_jobs=-1, verbose = 1)

# Fit on training data
rfcl.fit(X_train, y_train)

[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  34 tasks      | elapsed:    0.3s
[Parallel(n_jobs=-1)]: Done 184 tasks      | elapsed:    1.7s
[Parallel(n_jobs=-1)]: Done 300 out of 300 | elapsed:    3.2s finished

RandomForestClassifier(n_estimators=300, n_jobs=-1, random_state=42, verbose=1)

In [946]:
train_rf_predictions = rfcl.predict(X_train)
train_rf_probs = rfcl.predict_proba(X_train)

rf_predictions = rfcl.predict(X_test)
rf_probs = rfcl.predict_proba(X_test)

[Parallel(n_jobs=8)]: Using backend ThreadingBackend with 8 concurrent workers.
[Parallel(n_jobs=8)]: Done  34 tasks      | elapsed:    0.0s
[Parallel(n_jobs=8)]: Done 184 tasks      | elapsed:    0.1s
[Parallel(n_jobs=8)]: Done 300 out of 300 | elapsed:    0.3s finished
[Parallel(n_jobs=8)]: Using backend ThreadingBackend with 8 concurrent workers.
[Parallel(n_jobs=8)]: Done  34 tasks      | elapsed:    0.0s
[Parallel(n_jobs=8)]: Done 184 tasks      | elapsed:    0.2s
[Parallel(n_jobs=8)]: Done 300 out of 300 | elapsed:    0.3s finished
[Parallel(n_jobs=8)]: Using backend ThreadingBackend with 8 concurrent workers.
[Parallel(n_jobs=8)]: Done  34 tasks      | elapsed:    0.0s
[Parallel(n_jobs=8)]: Done 184 tasks      | elapsed:    0.2s
[Parallel(n_jobs=8)]: Done 300 out of 300 | elapsed:    0.3s finished
[Parallel(n_jobs=8)]: Using backend ThreadingBackend with 8 concurrent workers.
[Parallel(n_jobs=8)]: Done  34 tasks      | elapsed:    0.0s
[Parallel(n_jobs=8)]: Done 184 tasks      | elapsed:    0.1s
[Parallel(n_jobs=8)]: Done 300 out of 300 | elapsed:    0.2s finished

In [947]:
y_pred = rfcl.predict(X_test)

[Parallel(n_jobs=8)]: Using backend ThreadingBackend with 8 concurrent workers.
[Parallel(n_jobs=8)]: Done  34 tasks      | elapsed:    0.0s
[Parallel(n_jobs=8)]: Done 184 tasks      | elapsed:    0.1s
[Parallel(n_jobs=8)]: Done 300 out of 300 | elapsed:    0.3s finished

In [948]:
print('Model accuracy score with 10 decision-trees : {0:0.4f}'. format(accuracy_score(y_test, y_pred)))

Model accuracy score with 10 decision-trees : 0.9925

In [949]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[    0,   102],
       [   24, 16713]])

---

# Entropy Criterion

----

# Log loss criterion

------
------

# Other ways to do

In [950]:
mis_modelos = [
    ("Tree_gini", DecisionTreeClassifier, {"criterion": "gini", "max_depth": 5, "random_state": 42}),
    ("Tree_entr", DecisionTreeClassifier, {"criterion": "entropy", "max_depth": 5, "random_state": 42})
]

In [951]:
for clf_name, clf_class, hyper_dict in mis_modelos:
    clf = clf_class(**hyper_dict)
    print(clf_name)
    print(clf)

Tree_gini
DecisionTreeClassifier(max_depth=5, random_state=42)
Tree_entr
DecisionTreeClassifier(criterion='entropy', max_depth=5, random_state=42)