In [11]:
import pandas as pd

import numpy as np

import matplotlib.pyplot as plt

import seaborn as sb

In [16]:
Data_90_path = "../Data/churn_dataset_90.csv"

Data_90_test_path = "../Data/churn_test_dataset_90.csv"

In [17]:
Data_90_df = pd.read_csv(Data_90_path) 

Data_90_df

,customer_unique_id,order_purchase_timestamp,customer_city,customer_state,order_status,price,freight_value,payment_value,product_weight_g,product_category_name_english,is_customer,churn_90,payment_sequential,payment_type,payment_installments
0,0000f46a3911fa3c0805444483337064,2017-03-10 21:05:03,sao jose,SC,delivered,69.00,17.22,86.22,1500.0,stationery,1,1,1.0,credit_card,8.0
1,0005e1862207bf6ccc02e4228effd9a0,2017-03-04 23:32:12,teresopolis,RJ,delivered,135.00,15.12,150.12,2250.0,fashion_bags_accessories,1,1,1.0,credit_card,3.0
2,00115fc7123b5310cf6d3a3aa932699e,2017-01-21 21:58:35,brasilia,DF,delivered,59.99,16.12,76.11,525.0,sports_leisure,1,1,1.0,credit_card,1.0
3,0011805441c0d1b68b48002f1d005526,2017-04-24 13:36:48,goianesia do para,PA,delivered,269.00,28.14,297.14,200.0,computers_accessories,0,0,1.0,credit_card,10.0
4,0011857aff0e5871ce5eb429f21cdaf5,2017-06-28 11:08:38,santo andre,SP,delivered,174.33,18.50,192.83,483.0,luggage_accessories,0,0,1.0,credit_card,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14466,ffedff0547d809c90c05c2691c51f9b7,2017-03-30 14:50:26,ribeirao preto,SP,delivered,17.90,14.52,32.42,225.0,housewares,1,1,1.0,credit_card,3.0
14467,ffef0ffa736c7b3d9af741611089729b,2017-05-29 22:07:05,nova venecia,ES,delivered,109.90,29.17,139.07,1136.0,sports_leisure,0,0,1.0,credit_card,1.0
14468,fffcf5a5ff07b0908bd4e2dbc735a684,2017-06-08 21:00:36,sanharo,PE,delivered,1570.00,497.42,4134.84,60000.0,health_beauty,0,0,1.0,credit_card,10.0
14469,ffff371b4d645b6ecea244b27531430a,2017-02-07 15:49:16,sinop,MT,delivered,89.90,22.56,112.46,600.0,auto,1,1,1.0,credit_card,1.0
14470,ffffd2657e2aad2907e67c3e9daecbeb,2017-05-02 20:18:45,campo largo,PR,delivered,56.99,14.57,71.56,400.0,perfumery,0,0,1.0,credit_card,4.0

In [18]:
Data_90_test_df = pd.read_csv(Data_90_test_path)

Data_90_test_df

,customer_unique_id,order_purchase_timestamp,customer_city,customer_state,order_status,price,freight_value,payment_value,product_weight_g,product_category_name_english,is_customer,churn_90,payment_sequential,payment_type,payment_installments
0,0000f46a3911fa3c0805444483337064,2017-03-10 21:05:03,sao jose,SC,delivered,69.00,17.22,86.22,1500.0,stationery,1,1,1.0,credit_card,8.0
1,0005e1862207bf6ccc02e4228effd9a0,2017-03-04 23:32:12,teresopolis,RJ,delivered,135.00,15.12,150.12,2250.0,fashion_bags_accessories,1,1,1.0,credit_card,3.0
2,00115fc7123b5310cf6d3a3aa932699e,2017-01-21 21:58:35,brasilia,DF,delivered,59.99,16.12,76.11,525.0,sports_leisure,1,1,1.0,credit_card,1.0
3,0011805441c0d1b68b48002f1d005526,2017-04-24 13:36:48,goianesia do para,PA,delivered,269.00,28.14,297.14,200.0,computers_accessories,0,0,1.0,credit_card,10.0
4,0011857aff0e5871ce5eb429f21cdaf5,2017-06-28 11:08:38,santo andre,SP,delivered,174.33,18.50,192.83,483.0,luggage_accessories,0,0,1.0,credit_card,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14466,ffedff0547d809c90c05c2691c51f9b7,2017-03-30 14:50:26,ribeirao preto,SP,delivered,17.90,14.52,32.42,225.0,housewares,1,1,1.0,credit_card,3.0
14467,ffef0ffa736c7b3d9af741611089729b,2017-05-29 22:07:05,nova venecia,ES,delivered,109.90,29.17,139.07,1136.0,sports_leisure,0,0,1.0,credit_card,1.0
14468,fffcf5a5ff07b0908bd4e2dbc735a684,2017-06-08 21:00:36,sanharo,PE,delivered,1570.00,497.42,4134.84,60000.0,health_beauty,0,0,1.0,credit_card,10.0
14469,ffff371b4d645b6ecea244b27531430a,2017-02-07 15:49:16,sinop,MT,delivered,89.90,22.56,112.46,600.0,auto,1,1,1.0,credit_card,1.0
14470,ffffd2657e2aad2907e67c3e9daecbeb,2017-05-02 20:18:45,campo largo,PR,delivered,56.99,14.57,71.56,400.0,perfumery,0,0,1.0,credit_card,4.0

In [19]:
Data_90_df["is_customer"].value_counts()

is_customer
0    9224
1    5247
Name: count, dtype: int64

In [24]:
train_X = Data_90_df.drop(columns = ['churn_90', "customer_unique_id"])

train_y = Data_90_df['churn_90']

In [26]:
train_X.shape

(14471, 13)